[Spring 지하철 경로 조회 3단계] 포츈(정윤성) 미션 제출합니다
woowacourse/atdd-subway-path pull request #114
Opened 2021-05-17 06:57 UTC by unluckyjung

음.. 이번 단계는 정말 jpapht 라이브러리가 많은걸 해줘서, 제가 한게 거의 없는 수준 이네요.

좀 추가했으면 좋겠다 싶은부분 있으면 피드백 주세요!

2021-05-18 16:04 UTC, JunHoPark93 requested changes
안녕하세요 포츈!
미션 잘 구현해주셨어요. 코드양이 많지않아 반영보다는 생각해볼 수 있는 것들 몇가지 남겼는데요,
저라면 설계를 이렇게 해봤을거같아요.
스크린샷과 내용 첨부했으니 한번 보시고 같이 고민해봐도 좋을거같네요 🙏

2021-05-18 16:04 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/PathFinder.java
> +    public int getShortestDistance(final Station sourceStation, final Station targetStation) {
이렇게 되면 사용하는 서비스에서는 아래와같이 사용할 수 있겠네요.
<img width="1379" alt="스크린샷 2021-05-19 오전 12 59 06" src="https://user-images.githubusercontent.com/20608121/118684726-6b70c300-b83d-11eb-8106-38d6da1493d6.png">

혹은 이런식으로 프런트에서 넘어온 길찾기 알고리즘 종류를 반영해볼수도있겠구요
<img width="1285" alt="스크린샷 2021-05-19 오전 1 00 03" src="https://user-images.githubusercontent.com/20608121/118684870-8cd1af00-b83d-11eb-92d7-744630fa5000.png">

2021-05-18 16:04 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/PathFinder.java
> +    public int getShortestDistance(final Station sourceStation, final Station targetStation) {
정답은 없으니 포츈이 설계를 어떻게 하면 좋을지 한번 고민해보시는것도 좋을거같네요 :)

2021-05-18 16:04 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/PathGraph.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
이 PathGraph클래스도 위에 말씀드린대로 구조를 고민하시면서 더 좋은 방법이 있다면 리팩토링 도전해봐도 좋구요~

2021-05-19 05:29 UTC, unluckyjung commented on src/main/java/wooteco/subway/path/domain/PathFinder.java
> +    public int getShortestDistance(final Station sourceStation, final Station targetStation) {
라이브러리를 열어보고, 가능하다면 기능별로 주입시키는 방향이 있었네요!
전혀생각해보지 못했던 방향이에요. 정말 많은걸 배우고갑니다 @_@

그리구 지루하지 않았어요. 저 알고리즘은 상당히 좋아하는 편입니다 ㅋㅋ
안그래도, 다익을 매번 진행하면 O(ElgE) 의 복잡도가 M번 진행되고, 만약 노선이 쉽게 잘 바뀌지 않고 요청이 엄청나게 잦은 경우에는
플로이드 워셜로 O(V^3) 로 모든 정점들간의 거리를 구하고 O(1) 에 찾는게 더 좋지 않을까? 라는 생각은 하고 있었어요.

지하철 노선에서 Edge의 가중치가 음수인 경우는 존재하지 않으니, 벨만포드는 고려하지 않아도 될것이고
경우의수가 그렇게 많지 않으니 스타크래프트처럼 휴리스틱하게 길찾는 A-star 알고리즘 까지도 고려하지 않아도 된다고 생각했어요.

그래서 그냥 다익스트라에 종속적인 코드를짯는데, 만약 플와를 적용하고 싶으면 제이가 제시한것처럼 전략패턴을 사용해 외부 주입을 시킬수 있네요 !! 정말 리뷰 좋습니다 👍

2021-05-19 05:31 UTC, unluckyjung commented on src/main/java/wooteco/subway/path/domain/PathGraph.java
> +    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
요것도 멀티그래프여야 하나? 라는 고민이 있었거든요.
저는 기존에는 노선별로 같은 섹션이면 같은 철로를 공유하고 있다고 생각해서, 싱글 그래프를 사용해야 하지 않을까라고 생각했는데  
찾아보니까 국내에선 노선이 다르면 물리적인 철로도 따로 공유 하더라구요 ㅋㅋ 그래서 그냥 멀티 그래프를 사용 했었어요.

이 경우도 만약 다른나라에선 같은 철로를 공유하는경우라면? 이라고 생각한다면 다른 그래프를 넣어주어야겠죠 !
이것도 주입받는쪽으로 바꾸면 좋겠어요!

2021-05-19 07:27 UTC, unluckyjung reviewed
제이 진짜 코드량은 별로 없었지만
그거랑은 관련없이 배워가는게 정말 많았던 리뷰였습니다.

대만족 💯

2021-05-19 07:27 UTC, unluckyjung commented on src/main/java/wooteco/subway/path/domain/StationPathFinder.java
> +public class StationPathFinder {
저도 역간의 경로 탐색이라는것을 좀더 명확하게 알려주는게 옳다고 생각이 들어서 클래스 이름을 바꿔주었어요!

2021-05-19 07:27 UTC, unluckyjung commented on src/main/java/wooteco/subway/path/domain/PathGraph.java
> +        this.graph = graph;
https://github.com/woowacourse/atdd-subway-path/pull/114#discussion_r634923719 에서 언급한 것처럼, 그래프의 경우도 종류가 여러개 있으니, 외부 주입받는게 좋다고 생각이 들어서, pathGrpah를 만드는것도 외부 주입하게 했어요!

2021-05-19 07:27 UTC, unluckyjung commented on src/main/java/wooteco/subway/path/domain/ShortestPathStrategy.java
> +}
https://github.com/woowacourse/atdd-subway-path/pull/114#discussion_r634923065 에서도 감탄했지만
진짜 너무 제대로 배워갑니다 👍 

저는 제이의 리뷰를 받기전까지 **라이브러리 내부를 들여다 보고 종류별로 주입 시킨다는 생각** 자체를 하지 못했어요.
사실 어떤 기능을 제공하고 있나~ 궁금해서 살짝 열어보긴했는데 상위 인터페이스가 뭔지를 파악하고, 그걸 이용해 주입시킨다는 생각을 못했네요.  이래서 인터페이스를 잘 이용한 코드가 아름답다는건가 싶더라구요 ㅎ_ㅎ

예제를 제가 바꿔서 해보는걸 좋아해서, 원래 제이가 제시해준 방향성 말고 인터페이스를 이용한 전략패턴으로 먼저 구현해봤었는데
생각해보니, 같은 경로찾기 알고리즘이 반복되어 사용된다면, 굳이 인터페이스를 implements 한 클래스를 매번 new 하는건 별로인 구조인것 같았어요.

그리고 이 경우에는 해당되지 않지만, 나중에 많은 전략이 추가된다면 클래스를 관리하고 파악하는것도 힘들꺼 같았어요.

Enum을 이용하면 매번 new 할필요 없이 static 하게 관리할 수 있고, 어떤 전략들이 있는지 한눈에 파악이 잘되는것 같아
다 밀어버리고 제이의 방법을 그대로 따라갔어요.

Enum을 이용해 전략패턴을 구현한것도 굉장히 좋은거 같네요!

2021-05-19 07:27 UTC, unluckyjung commented on src/main/java/wooteco/subway/path/domain/StationPathFinder.java
>      }
이제 다양한 길찾기 전략을 수행할 수 있는 `StationPathFinder`가 되었습니다. ㅎ_ㅎ

그리고 저는 StationPathFinder가 line을 상태로 가지고 있을 필요는 없다고 생각했어요!
`StationPathFinder` 는 **무슨 그래프** 를가지고, **무슨 길찾기 알고리즘**을 사용하는것에 관심을 가져야지, 
**무슨 Line**들이 있는지는 굳이 알고, 기억할 필요가 없다고 생각했네요!

2021-05-20 13:46 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/PathGraph.java
> +    private final WeightedGraph<Station, DefaultWeightedEdge> graph;
이부분도 개선해주셨네요 👍
한 가지 더 나아가면 클래스이름이 PathGraph이니 만큼 WeightedGraph보다는 Graph를 필드로 가지는게 나아보여요. 
모든 그래프가 가중치그래프는 아니니까요!
(혹은 클래스이름에 Weighted가 들어가거나요)

2021-05-20 13:46 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/PathFinder.java
> +    public int getShortestDistance(final Station sourceStation, final Station targetStation) {
생각많이해주셨네요! 알고리즘에 대해 다루려는 피드백은 아니었지만 이것저것 많이 생각해보신게 멋지네요 :)
지하철이 아니라 우주정거장이어서 간선과 노선이 매우 많다면,
그리고 노선 변경이 실시간이 아니라 일,혹은 주단위로 일어난다면,
O(V^3) 요계산은 시간적 여유를 두고 뒷단에서 진행시키고 말씀주신 O(1)로 앞단에서 서빙하는 구조가 좋아보이네요 👍
(지하철 노선에 대입하려니 현실적으로 와닿진 않지만 ..)

혹은 자주사용되는 구간에 대해서 캐싱을 하는것도 방법이 되겠네요. 하지만 이방법은 실시간 노선변경이 일어날때 다익스트라 계산시간이 오래걸린다면 캐시에 다시말기까지의 갭을 어떻게 커버할지가 이슈가 될거같아요.

주어진 상황에서 최선의 선택을 하기까지 논의하고 개선하는데 있어서 수학적 사고와 논리력이 매우 중요한데 (저는 그런부분이 떨어지거든요 😢) 포츈은 곧 잘 하실거같아요.

2021-05-20 13:47 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/PathGraph.java
> +        this.graph = graph;
이부분도 코멘트하나 남겼어요!

2021-05-20 13:49 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/StationPathFinder.java
>      }
그렇네요!
기가막힌 지적이었습니다 👍

2021-05-20 13:54 UTC, JunHoPark93 approved these changes
안녕하세요 포츈!
하나를 알려드렸는데 열을 알아오시네요 👍
추후 미션에 많은 도움이 되었기를 바랍니다. 고생많으셨어요!

2021-05-20 13:54 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/StationPathFinder.java
> +    private final ShortestPathStrategy shortestPathStrategy;
👍 lines 걷어내니 역할이 더 확실해졌네요

2021-05-20 13:55 UTC, merged

2021-05-20 14:24 UTC, unluckyjung commented on src/main/java/wooteco/subway/path/domain/PathFinder.java
> +    public int getShortestDistance(final Station sourceStation, final Station targetStation) {
[시간복잡도](https://youtu.be/IEH3YA2Nn4Q) 하면 제이 아닌가요 ㅎㅎ? ㅋㅋ!

2021-05-20 14:42 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/PathFinder.java
> +    public int getShortestDistance(final Station sourceStation, final Station targetStation) {
아완전 잊고있었는데.. 그건 보지마시길바랍니다 😭 (이것도 반영하셔야해요)