[Spring 지하철 경로 조회 3단계] 피케이(박유진) 미션 제출합니다
woowacourse/atdd-subway-path pull request #141
Opened 2021-05-18 22:47 UTC by pkeugine

안녕하세요 김고래! 🙌
이번 단계는 큰 어려움 없이 구현할 수 있었어요.
한 가지 아쉬운 점은, 최단 경로 요청이 올 때마다
매번 새로운 맵을 생성하여 계산을 한다는 점입니다.

리뷰 잘 부탁드려요!! 😁

2021-05-21 03:11 UTC, ep1stas1s requested changes
깔끔하게 잘 해주셨네요 👍 
간단하게 코멘트 남겼으니 참고해주세요ㅎㅎ

2021-05-21 03:11 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/PathService.java
> +public class PathService {
큰 수정없이 깔끔하게 진행해주셔서 리뷰를... 드릴게 없네요ㅎ휴ㅠ
조금 억지로 코멘트를 남기자면, service의 경우 mock을 사용하여 테스트를 진행하니 참고해보셔도 좋을 것 같습니다!

2021-05-24 15:51 UTC, pkeugine commented
안녕하세요 김고래! 🙌
달아주신 리뷰 반영하면서, 몇 가지 추가 구현을 해봤어요!
그리고 그 외로 로깅이나 Optional을 활용했지만, 도입하지 않은 부분도 있습니다.

달라진 점, 그리고 고민했던 점은 다음과 같아요:

### 1. DistanceMap을 StationMap으로 변경했습니다.

`개인적으론 생성자를 통해 초기화하는게 더 명확해보입니다ㅎㅎ`
이 리뷰를 읽고 굉장히 많은 고민을 했어요. 생성자를 통해 초기화를 하는 것도 그렇고,
다익스트라 알고리즘 말고 다른 방식을 이용할 때 확장하기 좋은 구조로 리팩토링을 하고 싶었거든요.
그래서 처음에는 클래스로 역할 분리도 해보고 전략 패턴을 이용해보기도 했습니다.

그러다가 우리가 흔히 사용하는 List의 구현 방식을 활용해보기로 했어요:
```java
List<Something> list = new ArrayList<>();
```
1. 먼저 StationMap 이라는 인터페이스를 만든 후,
2. 구현체들이 공통적으로 필요한 `WeightedMultigraph`를 `AbstractStationMap`으로 만들고,
3. `DijkstraStationMap`과 같은 구현체로 실제 알고리즘을 넣는 방식입니다.

이렇게 해보니까 김고래가 말한 '생성자를 통해 초기화'도 되고, (제 기준) 코드가 훨씬 명확해졌어요.

```java
    public PathResponse shortestPath(Long sourceId, Long targetId) {
        Station source = stationDao.findById(sourceId);
        Station target = stationDao.findById(targetId);
        StationMap stationMap = new DijkstraStationMap(lineDao.findAll());

        Path path = stationMap.pathOf(source, target);
        return PathResponse.of(path);
    }
```

### 2. LoginInterceptor를 만들어서 토큰 검증 책임을 부여했어요.

`/members/me` 관련 api에 비정상적으로 접근하는 (ex: postman) 방식을 막기 위해 LoginInterceptor를 도입했어요.
이 인터셉터에서 토큰의 유효성을 판별하고, AuthController에서는 이제 Member 객체를 직접 사용하지 않고
dto인 LoginMember를 사용합니다! Member 객체를 Controller에서 사용하기엔 도메인 로직이 외부로 노출된다고 생각했어요.

### 3. findByEmailAndPassword() 를 제거했어요.

Member를 찾을 때 그냥 email로 찾은 다음, 그 Member 객체에게 비밀번호가 일치하는지 묻도록 바꿨습니다.
뭔가 이메일을 Dao에서 확인하면 비즈니스 로직을 Dao에서 확인하는 것 같았어요.

### 4. Dao에서 Optional을 활용하지 않았어요.
<img width="800" alt="Screen Shot 2021-05-25 at 12 20 45 AM" src="https://user-images.githubusercontent.com/48251668/119369379-0f031d00-bcef-11eb-88ae-96112912f4dd.png">

사실 저도 김고래의 말에 동의해요! 그리고 이번 미션에서도 Optional로 dao를 다시 구현했다가 롤백했어요.
저번 미션에서는 Optional로 모든 dao를 구현했었습니다!
Optional을 쓰지 않고 구현하면 어떻게 되는지(?) 다양한 시도해보고 싶었어요. 😂

여기서 궁금한 점은, 김고래는 JdbcTemplate을 이용할 때 어떤 방식으로 Optional을 만드시나요?
저는 `queryForObject()`를 `Optional.ofNullable()`로 감싸기도 해보고, `query()`에 `stream()`을 활용해보기도 했는데
결국 가독성을 위해 `query()` 로 List를 먼저 구한 뒤 Optional로 감싸주는 방식을 이용했었어요:
```java
    public Optional<Line> findById(final Long id) {
        final String sql = "SELECT * FROM LINE WHERE id = ?";
        final List<Line> result = jdbcTemplate.query(sql, rowMapper, id);
        return optionalOf(result);
    }

    private Optional<Line> optionalOf(final List<Line> result) {
        if (result.isEmpty()) {
            return Optional.empty();
        }
        return Optional.ofNullable(result.get(0));
    }
```
물론 정답이 있는 질문은 아니지만, 그만큼 다양한 시도를 해보면서 다른 분들은 어떻게 하는지 궁금했어요. 
그래서 김고래의 방식도 궁금합니다 😁

쓰다보니 글이 길어졌네요!
혹시라도 제 질문 / 고민이 이해가 되지 않으면 꼭 알려주세요!!
이번 리뷰도 잘 부탁드립니다 😁

2021-05-25 20:39 UTC, ep1stas1s approved these changes
주관적인 코멘트가 많았는데
여러 가지 고민하여서 잘 반영해주셨네요 👍 👍 
미션 진행하시느라 고생하셨습니다 ^_^

2021-05-25 20:39 UTC, merged

2021-06-16 06:28 UTC, pkeugine commented
# 피케이 학습로그

## HandlerInterceptor
- MVC의 구조에서 만약 예외를 잡는 곳이 없다면 서블릿 컨테이너(우리의 경우 Tomcat)가 예외를 처리하게 된다.
- 하지만 DispatcherServlet은 서블릿 컨테이너로 예외를 던지기 전에 그 예외를 처리할 수 있는지 확인한다.
- Dispatcher의 그 예외 처리 전략이 바로 `HandlerExceptionResolver`. 즉, 컨트롤러에서 생긴 예외를 잡을 리졸버를 찾는 것이다.
```java
public interface HandlerExceptionResolver {

	@Nullable
	ModelAndView resolveException(
                                HttpServletRequest request, 
                                HttpServletResponse response, 
                                @Nullable Object handler, Exception ex);

}
```
- `DispatcherServlet`의 전략이 다 그렇듯, `HandlerExceptionResolver`도 네 가지 구현체가 제공되고 그 중 세 가지는 default로 등록되어 있다.
- 그리고 위의 코드에서 알 수 있듯, 에러가 발생했을 시 따로 그 에러만을 위한 페이지를 `ModelAndView`를 통해 전달할 수 있다.
- default 전략이라고 해도, 내가 직접 만든 구현체를 등록시키면 default가 자동으로 적용되지 않기 때문에 명시적으로 등록해야한다.

### AnnotationMethodHandlerExceptionResolver (default)
- `@ExceptionHandler`를 사용하여 에러를 처리하는 방식이다.
- `@ResponseStatus` 방식보다 손이 많이 가지만 그만큼 더 자율적이다.
기본적인 예시:

```java
    @ExceptionHandler(RuntimeException.class)
    public ResponseEntity<String> handleUnknownException() {
        final String message = "unhandled exception occured";
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(message);
    }
```
- 위의 코드는 애플리케이션에서 **개발자가 예상하지 못한 에러**를 잡을 때 주로 사용하는 방식이다.

### ResponseStatusExceptionResolver (default)
```java
@ResponseStatus(HttpStatus.BAD_REQUEST)
public class RequestException {
    // 예외 구현
}
```
- 커스텀 예외를 만들고, 그 위에 `@ResponseStatus` 어노테이션을 붙여서 예외를 특정 Http 상태코드로 전달해주는 전략:
- 커스텀 예외가 아닌 예외에는 적용할 수 없다. 기존 예외를 처리하려면 `@ExceptionHandler`를 사용해야 한다.

### DefaultHandlerExceptionResolver (default)
- Spring MVC 내부에서 발생하는 에러를 다루는 구현체. 아마 우리가 프로그래밍하면서 생긴 에러 중 일부분을 이 리졸버가 잡아줬을 것. 
- 우리가 직접 던지는 에러를 담당하지는 않는다.
- 대표적으로 [TypeMisMatchException](https://stackoverflow.com/questions/57944251/spring-boot-handle-type-mismatch-errors) 이 있다. 요청으로 들어온 값을 파싱하다가 오류가 생기면 400이 뜬다.

### SimpleMappingExceptionResolver
- 예외가 생겼을 때 보낼 페이지를 지정할 수 있는 리졸버.

## IP 주소
* IP는 Internet Protocol로, TCP/IP 프로토콜의 일부.
* 32비트로 표현된 숫자 집합. 8비트 단위로 마침표 찍어서 보기 쉽게 표현한다. (ex: 192.168.0.1)
* 네트워크부 & 호스트부로 나뉜다.
    * 네트워크부 - 어떤 네트워크인지 표시
    * 호스트부 - 해당 네트워크 내에 있는 컴퓨터 표시
    * IP 주소에서 어디까지가 네트워크부이고 어디까지가 호스트부인지 표시하는 방법:
        * CIDR : '/24'
        * 서브넷 마스크 : 255.255.255.0
* 호스트부의 비트가 모두 1인 주소는 `브로드캐스트 주소`라 불리는 특수한 주소.
    * 브로트캐스트 주소로 패킷을 보내면 네트워크의 모든 호스트에 패킷이 전달된다.
* 호스트부의 비트가 모두 0인 주소는 `네트워크 주소`.

2021-06-18 04:27 UTC, kang-hyungu commented
HandlerInterceptor, HandlerExceptionResolver가 스프링에 포함된 내용이라는 표시를 해주는게 좋겠네요.