[Spring 지하철 경로 조회 3단계] 마크(김병화) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #145
Opened 2021-05-19 08:19 UTC by binghe819

### 안녕하세요 김고래!

<br>

이번 미션도 기존의 라이브러리를 활용해서 금방 구현할 수 있었어요!!!

1,2 단계에서 남겨주신 피드백도 모두 반영하였습니다 :)

이번 리뷰도 잘 부탁드려요~~~

2021-05-21 04:16 UTC, ep1stas1s requested changes
큰 변화없이 잘 구현해주셨네요 👍 
간단한 코멘트 남겼으니 참고해주세요^_^

2021-05-21 04:16 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/PathService.java
> +    private final StationDao stationDao;
service를 참조하지 않고 dao를 사용하신 이유가 있으실까요~?

2021-05-25 15:31 UTC, binghe819 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +    private final StationDao stationDao;
김고래 피드백 감사합니다!!ㅎㅎ

우선 저는 Service에서 도메인을 넘기면 Presentation Layer에 도메인을 노출시키기 때문에 DTO를 반환하는게 타당하다고 생각듭니다!

그러기 위해선 Service 계층에서 가능한 DTO를 반환하게 하는게 맞다고 생각드는데요!

Service에서 Service로 반환할 때는 도메인을 반환해야 하기 때문에, 저는 가능한 복잡한 로직이 중복적으로 Service 계층에서 구현되어 있는 것이 아니라면 DAO를 의존하도록 하는 것이 맞다고 생각들어서 이렇게 구현했습니다 :) 

물론 Service에서 Service로 반환할 때 도메인을 반환하자는 규칙이 잘 지켜진다면 괜찮겠지만 Service의 public API라는 점에서 (미래의 내가, 혹은 다른 팀원 등이) 추후에 해당 API를 Controller에서 사용해버리면 의미가 없어진다고 생각도 들기도 해서요!

하지만 기존 코드를 살펴보니 Service 계층끼리의 의존성도 타당하다고 생각들기도 하네요 :) 리팩토링하여서 리뷰 요청하겠습니다!!

2021-05-27 20:50 UTC, ep1stas1s approved these changes
미션 진행하시느라 고생하셨습니다 👍 
레벨2 마지막 미션도 화이팅하세요~!

2021-05-27 20:50 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/PathService.java
> +    private final StationDao stationDao;
어플리케이션이 커지면 언젠간 facade 형태의 서비스를 필요로 하게되고, 다른 서비스들을 참조해야할 경우가 생길 것 같은데요~ 그때 서비스가 항상 DTO를 반환하면 도메인간 상호작용 전에 불필요한 변환작업(DTO -> domain)이 필요해질 수 있어요
그렇다고 매번 dao를 참조할 경우 불필요한 중복 로직 (또는 메서드)이 생성되겠죠? 이러한 중복이 일어날 수 있는 메서드를 서비스에 구현해놓으면 나중에 서비스-서비스 형태로 리팩토링을 진행할때도 상대적으로 편하게 리팩토링이 가능할 것 같아요

결론적으로 서비스를 참조하는 것이 좋다고 생각하나 이건 단순히 제 의견이고, 마크도 충분히 장단점을 인식하고 계신 것 같으니 상황에 맞게 잘 사용하시면 될 것 같습니다ㅎㅎ

2021-05-27 20:51 UTC, merged