[Spring 지하철 경로 조회 3단계] 코기(김진환) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #149
Opened 2021-05-20 19:47 UTC by ecsimsw

이전

2021-05-21 14:33 UTC, JunHoPark93 requested changes
안녕하세요 코기!
미션 잘 구현해주셨어요!
몇가지 피드백 남겼는데 확인부탁드려요 🙏
질문주신부분도 코멘트로 남겨두었습니다

2021-05-21 14:33 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/Path.java
> +            graph.addVertex(section.getUpStation());
질문주신부분이에요. 좋은지적입니다!
```java
private void addStation(Station station) {
    if (!graph.containsVertex(station)){
        graph.addVertex(station);
    }
}
```
하지만 저는 굳이 이렇게 안해도될거같아요.
외부라이브러리인 addVertex는 주석에도 나와있듯이 이미 vertext가 있을때 같은것을 추가하는 액션이 일어나더라도 변동이 없다라고 명시가 되어있어요. 여기서 충분히 정보를 얻을 수 있어보여요~

2021-05-21 14:33 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/Path.java
> +    private final DijkstraShortestPath dijkstraShortestPath = new DijkstraShortestPath(graph);
dijkstraShortestPath를 필드로 가지고 있을 필요가 있을까요? 🤔
필드를 줄이려면 어떤방법을 써야할지 고민해보면 도움이 될거에요~

2021-05-21 14:33 UTC, JunHoPark93 commented on frontend/src/utils/constants.js
> +    "green darken-2",
노파심에 남기는데 

> 또 js, 프론트엔드를 몰라 원인을 모르는 에러를 잡는데 시간을 많이 썼던 것 같습니다.

프런트엔드에 시간을 쏟지 않으셨으면합니다. (다잘하면 좋겠지만요 😢)
우리의 시간은 한정되어있고 백엔드만 하더라도 할게 많기 때문이에요

2021-05-21 14:33 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/Path.java
> +public class Path {
Path를 잘정의했는지가 의문이라고 말씀주셨어요.

> 다른 것보다 Path를 잘 정의했는지가 가장 큰 고민이었습니다.

어떤 이유에서 고민이 생기셨을까요?
아마 남겨주신 **1) Path의 addSections** 이거 말고도 다른 고민이 있으셨을거같은데요,
그랬다면 코멘트남겨주세요. 당장에 궁금한게 생기면 바로 dm주셔도 좋구요

2021-05-21 14:33 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        final Path shortest = new Path(lineService.findLines());
변수의 이름이 shortest네요. Path를 만들면 항상 shortestPath가 되는걸까요? 
클래스명을 수정하든 추가적인인자를 받는 Path를 개선할 수 있는 방법이 있을까요?

2021-05-21 14:33 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/Path.java
> +            graph.addVertex(section.getUpStation());
하지만 대부분 같은걸로 add를 하면 엎어쳐지는걸 기대할것도 같은데요.
팀내에서 공유가 된다면 상관없지만 누군가에게 인수인계를 해야한다면 주석으로 남겨놓는것도 방법입니다.
주석을 지양하고 코드로 나타내는게 좋지만 이런경우는 경고성의 의미로 남겨놓는것도 괜찮아보여요~
난 분명히 add를 했는데 그래프에 변화가 없다고 생각할 수 도 있으니까요.

2021-05-21 14:33 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        if (memberService.isNotExistUser(tokenRequest.getEmail(), tokenRequest.getPassword())) {
취향차이일수는 있는데 저는 부정문을 꼭 쓰지 않으려고 노력하지는 않아요. isNotExistUser보다 isExists에 !를 붙인게 더 읽기 쉽다고 생각해요!

2021-05-21 14:38 UTC, JunHoPark93 commented
지난 미션마지막에 남겨주신 말때문에 남겨요~
지금도 충분히 잘하고계셔요! 질문많아도 괜찮고 조금이라도 이해안되거나 궁금한게 있으면 언제든 이야기주세요. 
저희역할이니 전혀 부담가지지 않으셔도되어요~

2021-05-21 15:22 UTC, ecsimsw commented on src/main/java/wooteco/subway/path/domain/Path.java
> +    private final DijkstraShortestPath dijkstraShortestPath = new DijkstraShortestPath(graph);
헉.. 놓친 부분입니다!!! 아래처럼 GraphPath를 리턴하는 것으로 수정해보았습니다.

(Path.java -> PathFinder.java)

```java
// PathFinder
public GraphPath shortest(final Station source, final Station target){
    return new DijkstraShortestPath(graph).getPath(source, target);
}
```

```java
//PathService
public PathResponse findShortestPath(final Long sourceId, final Long targetId) {
    final Station source = stationService.findStationById(sourceId);
    final Station target = stationService.findStationById(targetId);

    final PathFinder pathFinder = new PathFinder(lineService.findLines());
    final GraphPath shortest = pathFinder.shortest(source, target);

    return new PathResponse(shortest);
}
```

2021-05-21 15:31 UTC, ecsimsw commented on src/main/java/wooteco/subway/path/domain/Path.java
> +public class Path {
( Path의 이름을 PathFinder로 수정하였습니다. )

경로를 검색할 때마다 모든 역을 읽고 그것들을 추가한 Graph를 새로 생성하는 점이 걸렸습니다.

경로를 추가, 삭제할 때마다만 PathFinder의 생성이 이뤄지게 할 순 없을까 고민 중입니다.

조금 더 생각해보고 결과 남기겠습니다. :)

```java
// PathFinder 전체 코드
public class PathFinder {
    private final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph(DefaultWeightedEdge.class);

    public PathFinder(final List<Line> lines) {
        for (final Line line : lines) {
            addSections(line.getSectionsAsList());
        }
    }

    private void addSections(final List<Section> sections) {
        for (final Section section : sections) {
            graph.addVertex(section.getUpStation());
            graph.addVertex(section.getDownStation());
            graph.setEdgeWeight(graph.addEdge(section.getUpStation(), section.getDownStation()), section.getDistance());
        }
    }

    public GraphPath shortest(final Station source, final Station target){
        return new DijkstraShortestPath(graph).getPath(source, target);
    }
}
```

2021-05-21 15:32 UTC, ecsimsw commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        final Path shortest = new Path(lineService.findLines());
해당 로직 아래처럼 수정해보았습니다.
`Path를 만들면 항상 shortestPath가 되는걸까요?` 생각하지 못했는데, 감사합니다.

```java
public PathResponse findShortestPath(final Long sourceId, final Long targetId) {
    final Station source = stationService.findStationById(sourceId);
    final Station target = stationService.findStationById(targetId);

    final PathFinder pathFinder = new PathFinder(lineService.findLines());
    final GraphPath shortest = pathFinder.shortest(source, target);

    return new PathResponse(shortest);
}
```

2021-05-21 15:36 UTC, ecsimsw commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        if (memberService.isNotExistUser(tokenRequest.getEmail(), tokenRequest.getPassword())) {
저도 사실 ! 붙이는게 더 좋았습니다... ㅎㅎ
리뷰 받을 때마다 사알짝 눈치 보던 부분이었는데, 조금 더 자신감을 가져도 되겠어요!!! 😁

2021-05-21 15:44 UTC, ecsimsw commented on src/main/java/wooteco/subway/path/domain/Path.java
> +            graph.addVertex(section.getUpStation());
정말 좋은 피드백 감사합니다.

`이런경우는 경고성의 의미로 남겨놓는것도 괜찮아보여요`

분명 이런 문제가 아니더라도 협업을 위해 주석을 남겨야할 일이 생길 것도 같은데
지금까지 주석을 남기는 것도 생각해보자는 리뷰를 받아본 적 없어 더 현실적으로 와닿았던 것 같습니다.

아래처럼 주석 달아 보았습니다!!!

``` java
private void addSections(final List<Section> sections) {
    for (final Section section : sections) {
        //  If this graph already contains such vertex, 'addVertex' leaves this graph unchanged.
        graph.addVertex(section.getUpStation());
        graph.addVertex(section.getDownStation());
        graph.setEdgeWeight(graph.addEdge(section.getUpStation(), section.getDownStation()), section.getDistance());
    }
}
```

2021-05-22 17:04 UTC, ecsimsw commented
제이 좋은 말씀 정말 감사합니다.

이번에는 **1. 피드백 반영 2. LineService에서 SectionService 분리 3. NewPathFinder와 NewPathService 고민** 을 하여 다시 리뷰 요청 드리게 되었습니다.

### NewPathFinder와 NewPathService 고민

이전 PathFinder는 최단 거리 검색 시 마다 매번 모든 구간을 받아 그래프를 재생성 해야 했습니다. 
그 부분이 마음에 걸려 NewPathService를 정의하고, 구간에 변경이 있을 때만 그래프를 재생성하는 식으로 수정해보았습니다.

다만, 이렇게 되면 NewPathService는 NewPathFinder를 '변경되는 상태'로써 갖는다는 점이 마음에 안들었고, LineService에서 NewPathService의 상태를 직접 다룬다는 점이 마음에 걸렸습니다.

가능한, 특히 빈으로 관리되는 컴포넌트는 상태가 없도록 만들고 싶었는데 
이번 리팩토링에서 그 부분이 깨져 바람직한 구조라는 확신이 서지 않아 비교를 요청드리기 위해 기존의 PathFinder와 PathService를 따로 남겨 두었습니다.

제이가 보시기에는 어떠신가요?
저의 고민이 유의미한지, 제이라면 어떤 구조를 더 선호하실지 여쭤보고 싶습니다.

2021-05-24 15:08 UTC, JunHoPark93 approved these changes
안녕하세요 코기!
피드백 반영하시느라 고생많으셨습니다 🙇‍♂️
질문에 대한것은 코멘트 남겨두었어요
다음 미션도 화이팅입니다 🥳

2021-05-24 15:08 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/application/NewPathService.java
> +        pathFinder = pathFinder.update(lineDao.findAll());
상태가 변경되는 액션은 좋지 않다고 생각해요. 하나의 빈으로 관리가 되는 친구의 속성이 변경이된다면 의도치 않은 결과가 나올수있어요. 지금은 요청올때마다 계산하는 구조가 더 안정적이라고 생각해요.
한번계산한것을 어떻게 재사용할지는 다른 방식으로 고민을 하셔야될것으로 보여요!
여력이 되시면 고민해보시고 고민하신부분에 대해서 궁금증이 있다면 다시 말씀주세요 🙏

2021-05-24 15:08 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/application/NewPathService.java
> +        pathFinder = pathFinder.update(lineDao.findAll());
상태가 변경되는 액션은 좋지 않다고 생각해요. 하나의 빈으로 관리가 되는 친구의 속성이 변경이된다면 의도치 않은 결과가 나올수있어요. 지금은 요청올때마다 계산하는 구조가 더 안정적이라고 생각해요.
한번계산한것을 어떻게 재사용할지는 다른 방식으로 고민을 하셔야될것으로 보여요!
여력이 되시면 고민해보시고 고민하신부분에 대해서 궁금증이 있다면 다시 말씀주세요 🙏

2021-05-24 15:08 UTC, merged