[Spring 지하철 경로 조회 - 3단계] 파피(김태완) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #152
Opened 2021-05-23 06:20 UTC by TaewanKimmmm

안녕하세요, 코니!

모든 피드백 반영하였습니다.

ArgumentResolver에서 만들어 넘겨주는 LoginMember에 담아야 하는 정보 그리고 token에 어떤 정보를 담아야 하는 지에 대해 고민을 할 수 있었고, 두 개가 일맥상통하다는 생각이 들었습니다!

---

그런데, 토큰에조차 비밀번호같은 중요한 정보는 담지 말라고 하잖아요...

그렇다면 현재 토큰을 발급하고자 요청할 때 email이랑 password를 전송하고 있는데 이건 괜찮은 건가요? 새로운 미션에서 TLS를 배웠는데 TLS를 적용하면 해결되는 문제일까요?

---

많은 피드백 부탁드립니다! 소중한 시간 내어주셔서 감사합니다 🙏😀🙏

2021-05-24 11:13 UTC, choihz requested changes
안녕하세요, 파피!

지하철 경로 조회 미션 3단계도 잘 구현해 주셨네요 👍 피드백 보시고 궁금한 점 또는 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2021-05-24 11:13 UTC, choihz commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findShortestDistancePath(source, target));
`findShortestPath()`만으로도 의미가 충분히 전달되는 것 같아요!

2021-05-24 11:13 UTC, choihz commented on src/main/java/wooteco/subway/line/dao/SectionDao.java
> +    }
지금 구조는 이해하기도 쉽지 않고, `SectionDao`가 `Station`을 아는 것이 과연 적절한가 하는 고민도 드네요. 더 좋은 방법이 없을까요?

2021-05-24 11:13 UTC, choihz commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        GraphPath shortestPath = path.calculateShortestPath(sourceId, targetId);
타입 파라미터를 명시해 주세요!

2021-05-24 11:13 UTC, choihz commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        return new PathResponse(stationResponses, shortestDistance);
`PathResponse`가 `List<StationResponse>` 대신 `List<Station>`을 바로 받을 수 있다면 어떤 장점이 있을까요?

2021-05-24 11:13 UTC, choihz commented on src/main/java/wooteco/subway/path/domain/ShortestDistanceStrategy.java
> +    }
매번 `stations`를 탐색해야만 할까요? 어떻게 하면 `id`만으로 `Station`을 바로 찾을 수 있을까요?

2021-05-24 11:13 UTC, choihz commented on src/main/java/wooteco/subway/path/domain/ShortestDistanceStrategy.java
> +public class ShortestDistanceStrategy implements PathStrategy {
전략 패턴 👍

2021-05-24 11:17 UTC, choihz commented
> 그런데, 토큰에조차 비밀번호같은 중요한 정보는 담지 말라고 하잖아요...
> 그렇다면 현재 토큰을 발급하고자 요청할 때 email이랑 password를 전송하고 있는데 이건 괜찮은 건가요? 새로운 미션에서 TLS를 배웠는데 TLS를 적용하면 해결되는 문제일까요?

토큰에 중요한 정보를 담지 말라는 이유는, 로컬 스토리지 또는 쿠키에 저장된 토큰이 탈취될 위험이 있고, JWT의 특성상 토큰을 얻으면 안에 담긴 정보를 바로 볼 수 있기 때문이지요!

[프론트에서 안전하게 로그인 처리하기 (ft. React)](https://velog.io/@yaytomato/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%90%EC%84%9C-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)
[JWT는 어디에 저장해야할까? - localStorage vs cookie](https://velog.io/@0307kwon/JWT%EB%8A%94-%EC%96%B4%EB%94%94%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C-localStorage-vs-cookie)

위 글들을 읽어 보시면 어느 정도 이해에 도움이 되지 않을까 해요. 언급하신 TLS도 공부해 보시면 좋구요~

2021-05-25 17:24 UTC, TaewanKimmmm commented on src/test/java/wooteco/subway/line/SectionAcceptanceTest.java
>  import static wooteco.subway.station.StationAcceptanceTest.지하철역_등록되어_있음;
기존에 public static으로 설정되어 있어서 코드 제공의 의도로 받아들였었네요. 따로 가지고 있도록 수정하겠습니다.

2021-05-25 17:35 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +                .orElseThrow(AuthorizationException::new));
null에 과몰입했었네요 감사합니다!!

2021-05-25 17:38 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        if (jwtTokenProvider.validateToken(token)) {
맞습니다 수정했습니다!

2021-05-25 17:39 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findShortestDistancePath(source, target));
findShortestTimeDistancePath 등이 추가될 가능성이 있다고 생각하여 네이밍했었는데, 너무 앞서나간 것 같기도 하네요 ㅎㅎ 수정하겠습니다~

2021-05-25 17:42 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        GraphPath shortestPath = path.calculateShortestPath(sourceId, targetId);
넵 명시했습니다..!

2021-05-25 18:24 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/line/dao/SectionDao.java
> +    }
SectionDao 대신 LineService를 사용하게 함으로써 삭제하게 되었습니다!

2021-05-25 18:34 UTC, TaewanKimmmm commented
안녕하세요, 코니!!!!!! 주셨던 피드백 모두 반영하였습니다.

좋은 구조에 대해 고민할 수 있었고, 내가 짠 코드를 너무 믿지 말자는 교훈을 얻었어요 😂

코니의 꼼꼼함을 흡수해가겠습니다..

소중한 시간 내어주셔서 감사합니다!!🙏😀🙏

2021-05-26 13:42 UTC, choihz approved these changes
안녕하세요, 파피!

피드백을 잘 반영해 주셨네요 👍 지하철 경로 조회 미션은 여기서 마무리하도록 할게요. 그동안 고생 많으셨고, 다음에 또 만나요~ 👋

2021-05-26 13:42 UTC, choihz commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    }
"each"라는 단어가 여기서 적절한지 모르겠네요 🤔 역시 네이밍이 제일 어렵죠?

2021-05-26 13:42 UTC, choihz commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        Station target = stationDao.findById(targetId);
존재하지 않는 역 ID를 입력하면 어떻게 될까요?

2021-05-26 13:42 UTC, choihz commented on src/test/java/wooteco/subway/auth/AuthAcceptanceTest.java
> +    public static ExtractableResponse<Response> 회원_등록되어_있음(String email, String password, Integer age) {
`@Test` 붙은 메서드가 아래로 내려간 게 아마 포매터 이슈로 보이는데, 테스트 메서드가 위에 있는 게 좋겠죠?

2021-05-26 13:42 UTC, choihz commented on src/test/java/wooteco/subway/auth/AuthAcceptanceTest.java
> +        params.put("password", password);
`Map` 대신 `TokenRequest`를 직접 이용하는 게 더 좋을 것 같아요.

2021-05-26 13:42 UTC, merged

2021-05-30 06:22 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    }
고민해보겠습니다..ㅎㅎ

2021-05-30 06:23 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        Station target = stationDao.findById(targetId);
예외처리가 되어 있지 않았네요..! 런타임 에러가 발생할 수 있겠네요..!

2021-05-30 06:23 UTC, TaewanKimmmm commented on src/test/java/wooteco/subway/auth/AuthAcceptanceTest.java
> +    public static ExtractableResponse<Response> 회원_등록되어_있음(String email, String password, Integer age) {
넵 시정하겠습니다!!!!!

2021-05-30 06:23 UTC, TaewanKimmmm commented on src/test/java/wooteco/subway/auth/AuthAcceptanceTest.java
> +        params.put("password", password);
매우 동의합니다!