[Spring 지하철 경로 조회 - 3단계] 중간곰(양승현) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #155
Opened 2021-05-27 12:46 UTC by ggyool

**안녕하세요 코니 🖐**

1~2단계 머지된 지가 12일 지났는데 이제야 제출하네요..
밀려있던 이전 미션과 페어와 함께하는 다음 미션을 먼저 하다가 늦게 내게 됐습니다. 😢
늦었지만 고민하며 꼼곰히 만들려고 노력했습니다. 편하게 의견 주시면 감사하겠습니다 !
이번 미션에서 중점적으로 고민하고 시도한 내용을 적어가며 궁금한 점을 질문드리려고 해요.

## 경로 조회 기능 구현에 대한 구조
미션을 처음 시작했을 때 길찾기 전략을 외부에서 주입하고 싶었어요.
대충 아래 같은 느낌으로 예전 자동차 미션 때 이동 전략 만들었던 것처럼 하려고 했어요.
```java
pathService.findPath(Lines, dijkstraStrategy);
```
Lines를 이용하여 그래프를 만들고 주입받은 전략을 이용하고 싶었는데 Dijkstra가 graph에 의존하고 있어서 어렵더라고요..
```java
public DijkstraShortestPath(Graph<V, E> graph)
```
고민하다가 시도한 방향은 Bean을 등록하여 의존성을 관리하는 방향이에요.

```jgrapht```의 ```Multigraph```와 ```ShortestPathAlgorithm```를 ApplicationConfig.class에 Bean으로 등록했습니다. 

### 선택한 이유
- ShortestPathAlgorithm에 다양한 구현체들이 있는데 Bean 등록 부분을 바꾸면 쉽게 갈아낄 수 있다고 생각
- 노선도라는 도메인은 싱글톤으로 관리하는게 좋다고 생각
- Service, Dao, Controller 이외의 Bean을 등록해본 적이 없어서 만들어보고 싶었다.

```java
 jgrapht 라이브러리에 많은 부분을 의존하고 있다는 생각이 드는데, 다른 요구 사항이 없어서 상상하며 만들려니 와닿지도 않고 
인터페이스를 잘 안 써봐서 쉽게 만들지는 못하겠더라고요. 개선점을 살짝 알려주시면 반영해보겠습니다.
```
### 구현하며 경로 조회 관련 두 패키지가 생겼습니다.
- path 패키지: 경로 조회를 담당
- routemap 패키지: 노선도 관리를 담당

### 질문. 레이어 분류에 어색함이 없을까요?

- **PathRouter domain이 아닌 application 패키지에 위치**
    - 이유는 빈으로 관리하는 객체를 Domain에 넣어본적이 없어서 어색함
    - PathService에서 필드로 PathRouter를 가지고 있는데, 이제까지 필드에 도메인을 넣은적이 없었음
    - 외부 라이브러리에 의존적인 필드만 하나가지고 있음 (ShortestPathAlgorithm)
    - 적다보니 infra 패키지에 넣고 싶은데 findShortestPath() 라는 로직스러운 것을 가지고 있어서 domain에 넣어야 될 것 같기도 하고.. 모르겠습니다.
- **RouteMap을 domain이 아닌 infrastructure에 위치**
    - 필드로 가지고 있는 graph를 db라고 생각하면 DAO의 느낌이 난다.

<br>

## 예외 처리에 대한 내용
### 질문. 예외 메시지는 누구를 위해 만드는지 궁금합니다.
저는 1번을 염두하고 만들었습니다.
1. 프론트에서 바로 사용할 목적
2. 프론트에서 바로 사용하지는 않지만 상황을 알려주기 위해
3. 백엔드에서 메시지를 깔끔하게 보려고

### 질문. 현재 예외처리를 하는 방식이 괜찮은지
너무 많은 커스텀 예외가 생기는 것을 좋아하지 않아서 각각 도메인 패키지에 예외를 만들지 않고
subway 바로 아래 exception 패키지를 만들어 예외를 관리하고 있습니다.
예외들은 SpecificExceptionHandler.java 에서 핸들링 하고 있습니다.

- RuntimeException
    - BusinessRelatedException (application에서 사용, 400 error)
        - DomainArisenException (domain에서 사용) 
        - ValidationFailureException(application, domain에서 사용) 
        - RoutingFailureException (path.application에서 사용)
- ObjectNotFoundException (Application, Domain에서 사용, 404 error)
- AuthorizationException (auth 패키지에서 사용, 401 error)
 
지금 기준에는 RoutingFailureException이 없고 BusinessRelatedException를 사용해야 일관성 있다고 생각합니다.
예외처리 구조를 잡기 전에 path 부분을 만들어서 남아있다고 생각해 주세요.

**특별히 이상한지 궁금한 부분**
- DomainArisenException이 BusinessRelatedException을 상속받은 부분 ( 다른 계층 간 상속으로 계층 구조)
- LineService에서 일일이 DataAccessException을 catch 하여 application 예외로 변환하는 부분: Dao에서 발생한 예외에 적절한 메시지를 주고 싶어서 이렇게 만들었는데 중복코드가 많이 생기는 느낌이 들었습니다.

2021-05-29 18:49 UTC, choihz requested changes
안녕하세요, 중간곰!

지하철 경로 조회 미션 3단계도 잘 구현해 주셨네요 👍 오랜 시간을 들이신 티가 많이 나는 것 같아요 ㅎㅎ 피드백 보시고 궁금한 점 또는 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2021-05-29 18:49 UTC, choihz commented on src/main/java/wooteco/subway/exception/BusinessRelatedException.java
> +package wooteco.subway.exception;
> 질문. 예외 메시지는 누구를 위해 만드는지 궁금합니다.
> 저는 1번을 염두하고 만들었습니다.
> 1. 프론트에서 바로 사용할 목적
> 2. 프론트에서 바로 사용하지는 않지만 상황을 알려주기 위해
> 3. 백엔드에서 메시지를 깔끔하게 보려고

상황에 따라 다르고, 협의하기 나름이지 않을까 해요. 제 경험으로 한정짓자면 백엔드에서 던진 예외 메시지를 프론트에서 직접 사용한 경우는 없었던 것 같아요.

2021-05-29 18:49 UTC, choihz commented on src/main/java/wooteco/subway/exception/BusinessRelatedException.java
> +package wooteco.subway.exception;
> 질문. 현재 예외처리를 하는 방식이 괜찮은지
> 너무 많은 커스텀 예외가 생기는 것을 좋아하지 않아서 각각 도메인 패키지에 예외를 만들지 않고
> subway 바로 아래 exception 패키지를 만들어 예외를 관리하고 있습니다.
> 예외들은 SpecificExceptionHandler.java 에서 핸들링 하고 있습니다.
>
> - RuntimeException
>     - BusinessRelatedException (application에서 사용, 400 error)
>         - DomainArisenException (domain에서 사용) 
>         - ValidationFailureException(application, domain에서 사용) 
>         - RoutingFailureException (path.application에서 사용)
> - ObjectNotFoundException (Application, Domain에서 사용, 404 error)
> - AuthorizationException (auth 패키지에서 사용, 401 error)

간혹 다른 예외 메시지가 필요할 때마다 새로운 예외를 만드는 경우를 보는데, 그런 것보다는 적절히 포괄적인 예외를 만드는 편이 좋다고 생각하긴 해요. 그런데 예외 처리라든가 패키지 구조 등은 워낙 자유도도 높고 선호하는 방식도 달라서, 특별히 뭐가 낫다는 식으로 조언을 드리기는 어려운 부분입니다. 지금은 스스로 여러 가지 방식을 시도해 보고 장단점을 느끼는 것이 중요하지 않을까요?

2021-05-29 18:49 UTC, choihz commented on src/main/java/wooteco/subway/exception/DomainArisenException.java
> +public class DomainArisenException extends BusinessRelatedException {
`DomainArisenException`이 따로 존재할 때의 효용이 무엇인지 궁금합니다. 도메인 객체에서 예외를 발생시킬 때 사용하는 것 같은데, 별도 분리했을 때의 장점이 있나요?

2021-05-29 18:49 UTC, choihz commented on src/main/java/wooteco/subway/line/application/LineService.java
>      }
> LineService에서 일일이 DataAccessException을 catch 하여 application 예외로 변환하는 부분: Dao에서 발생한 예외에 적절한 메시지를 주고 싶어서 이렇게 만들었는데 중복코드가 많이 생기는 느낌이 들었습니다.

중복이 발생해도 필요한 작업은 해야 하겠지요. 다만, 예외 처리는 꼭 필요한 곳에서만 해도 된다고 생각해요. 언제 필요한지 판단은 뭐... 앞으로 계속 배워가실 부분인 것 같아요 😉

2021-05-29 18:49 UTC, choihz commented on src/main/java/wooteco/subway/routemap/infrastructure/RouteMap.java
> +public class RouteMap {
`PathRouter`는 적절한 위치에 있는 것 같은데, `RouteMap`은 잘 모르겠네요. `필드로 가지고 있는 graph를 db라고 생각하면 DAO의 느낌이 난다`고 하셨는데 DDD에서 말하는 infrastructure에 이런 개념도 해당되는지는 조금 애매한 것 같아요. 제가 DDD를 잘 모르기도 해서 우선은 언급만 하고 넘어갈게요.

2021-05-29 18:49 UTC, choihz commented on src/main/java/wooteco/subway/config/ApplicationConfig.java
> +    }
> jgrapht 라이브러리에 많은 부분을 의존하고 있다는 생각이 드는데, 다른 요구 사항이 없어서 상상하며 만들려니 와닿지도 않고 
인터페이스를 잘 안 써봐서 쉽게 만들지는 못하겠더라고요. 개선점을 살짝 알려주시면 반영해보겠습니다.

지금도 충분히 잘하신 것 같아요. 라이브러리 의존을 제거하기 위해 한 단계 더 추상화할 수도 있겠지만 지금 굳이 고려하실 부분은 아니라고 생각해요. 변경에 열려 있도록 설계하는 게 중요하긴 하지만 일어나지 않을 일을 먼저 지나치게 고민할 필요도 없죠. 물론 이 경계라는 게 애매하다는 게 문제지만요 😅

2021-06-03 04:40 UTC, ggyool commented on src/main/java/wooteco/subway/line/application/LineService.java
>      }
기억이 잘 안 나는데..  코드가 너무 🐶판 인 것 보니
대충 저런 느낌으로 만들어야지 하고 대략적으로 적어 놓고, 잊고 넘어가지 않았나 생각합니다. (아니라면 😱)
해당 부분 수정하고, 새로운 구간을 추가하는 addLineStation 메서드에도 검증 추가했습니다.

2021-06-03 04:42 UTC, ggyool commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Station downStation = stationService.findStationById(request.getDownStationId());
stationDao.findById(id) 를 Optional을 반환하게 만들고, service에는 findExistentStationById 를 만들어서 구체적인 메시지를 만들어 주었습니다. 
지금은 StationController에 **GET /stations/{id}** 가 없기 때문에 현재 구조를 손쉽게 만들 수 있었는데요. 만약 만들어야 하는 상황이 생겼다면 해당 요청은 NotFound를 응답하고 싶을 거라 생각합니다. 그런 상황이라면 아래와 같이 StationService에 예외의 종류만 다른 두 가지 findById를 만들 것 같은데 괜찮겠죠?😄 사실 어떻게 할지 몰라서 질문드리려고 했는데 적다가 생각이 나서 확인만 받고 싶습니다 !

```java
public Station findStationById(Long id) {
    return stationDao.findById(id)
        .orElseThrow(() -> new ObjectNotFoundException("역ID: " + id));
}

public Station findExistentStationById(Long id) {
    return stationDao.findById(id)
        .orElseThrow(() -> new NonexistentTargetException("역ID: " + id));
}

2021-06-03 04:42 UTC, ggyool commented on src/main/java/wooteco/subway/line/domain/Sections.java
>      }
꼼꼼한 피드백 감사합니다 😁
해당 메서드 아래에 있는 replaceSectionWith~~ 메서드도 순서가 바뀌어 있어서 수정했습니다!

2021-06-03 04:46 UTC, ggyool commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +    public ResponseEntity<PathResponse> findShortestPath(
1. 라이브러리의 graphPath.getEdgeList() 를 간선들을 얻어내고 간선의 Source를 사용하면 역 정보를 경로 순서대로 나온다고 추측해버렸네요. 간선의 순서는 보장되지만 Source와 Target이 바뀌어 있을 수 있어서 Path 생성 시 vertex도 전달하도록 수정했습니다.
2. 라인 insert 수정하면서 만든 findExistentStationById를 사용하도록 바꿨습니다.
3. 추가로 PathService에서 출발ID와 도착ID가 같은 경우 검증 추가
4. 추가로 경로가 없는 경우의 처리가 제대로 되고 있지 않아 수정했습니다.
(PathRouter.findByShortest 호출 시 graphPath가 null이면 경로 없음)

2021-06-03 04:49 UTC, ggyool commented on src/test/java/wooteco/subway/line/domain/LinesTest.java
> +        stationD = new Station(4L, "stationD");
실제 역을 바탕으로 구성한다고 해도 테스트하는 데이터의 상황이 현실의 노선과 같은 모양으로 만들기는 어렵다고 때문에 더 혼동이 온다고 생각했습니다. 지하철 노선도에 빠삭한 사람이라면 기존 알고 있던 노선 정보와의 불일치 때문에 헷갈리고 모르는 사람이면 차라리 A -> B -> C 로 만들어서 이름으로 순서를 파악할 수 있게 하고 싶었습니다. 하지만 Fixture를 실제처럼 만든다면 해결될 문제라고 생각합니다.

저번에는 이렇게 생각했었는데, 이번에 실제 역 이름으로 바꾸고 나니까 이해하기 편한 것 같아요!

2021-06-03 04:52 UTC, ggyool commented on src/test/java/wooteco/subway/line/domain/LinesTest.java
> +    }
@BeforeEach도 내리는 것은 어떻게 생각하시나요 ?
setUp에서 사용하기 위해 만들어진 메서드라 아래에 두는 게 어색하다는 생각이 듭니다.
테스트 코드를 이해한 상황이라면 걸리적거리는 존재가 될 수 있지만, 테스트 코드를 처음 읽는 상황이라서 setUp을 읽어야 하는데 @Test가 꽤 많은 상황이라 아래쪽에 내려가 있으면 불편할 것 같습니다.

2021-06-03 04:53 UTC, ggyool commented on src/test/java/wooteco/subway/path/domain/PathTest.java
> +        );
메서드 분리했습니다. 훨씬 좋네요👍

2021-06-03 04:55 UTC, ggyool commented on src/test/java/wooteco/subway/path/application/PathRouterTest.java
> +    }
역의 순서도 검증하도록 수정하였고, 기타 예외 상황에 대한 코드와 테스트를 추가했습니다.
다양한 테스트를 생성해보라고 하셨는데 구체적으로 특이한 상황이 떠오르지 않네요 🤔

2021-06-03 04:56 UTC, ggyool commented on src/main/java/wooteco/subway/exception/BusinessRelatedException.java
> +package wooteco.subway.exception;
프론트 협업 미션에서 1번으로 사용했어서 궁금해서 질문드렸었습니다.
2번 관점이 가장 크다고 생각하여 해당 관점으로 리팩터링 했습니다.

2021-06-03 04:59 UTC, ggyool commented on src/main/java/wooteco/subway/routemap/infrastructure/RouteMap.java
> +public class RouteMap {
저도 DDD 개념은 모르는데 기존에 있던 패키지 구조에 적용하려다 보니 고민했었는데 추측해 버린 것 같네요.  RouteMap이라는 이름을 보면 Domain 넣는 게 좋아 보여서 이동했습니다.

2021-06-03 05:01 UTC, ggyool commented on src/main/java/wooteco/subway/config/ApplicationConfig.java
> +    }
넵 😀  다음에 기회가 있을 테니, 나중을 노려야겠습니다.

2021-06-03 05:13 UTC, ggyool commented on src/main/java/wooteco/subway/exception/DomainArisenException.java
> +public class DomainArisenException extends BusinessRelatedException {
## 이번 미션에서 예외 처리에 대한 생각의 변화

### 기존 생각1 - 포괄적인 예외의 단점

‘포괄적인 예외를 사용하면 예외의 수는 적어지지만 어디에서 발생하는 예외인지 한눈에 알기 어렵다.’ 라는 생각을 가지고 있었습니다. 예를 들어서 “노선을 찾지 못했습니다.” 라는 에러 메시지를 봤을 때 Dao에서 발생한 예외를 Service에서 잡은 건지 Domain에서 로직을 돌다가 발생한 예외인지 어렵다? 그런 생각을 가지고 있었습니다.

예를 들면 현재 Sections.java에서 발생하는 예외들을 ValidationFailureException 이라는 예외에 메시지만 다르게 하여 처리하고 있는데 해당 Exception은 application, domain layer 둘 다 사용되므로 그 점이 걸렸습니다.




### 기존 생각2 - 계층 구조의 사고와 맞지 않음

기존 controller > service > dao 계층에서의 사고 (하위 계층에서 상위 계층을 의존하지 않음) 때문에 Dao에서 커스텀 예외로 throw 하지 않고 Service에서 catch 한 점, 노골적으로 HttpStatus에 관련된 이름으로 예외를 짓지 못한 점 등 불편한 부분이 있었습니다. 이 점이 기존 제출 때 족쇄처럼 작용했고, 며칠 뒤 코드를 보니 이해하기 어려운 구조를 가지고 있었습니다.

### 리팩터링하며 든 생각

계층에 대한 생각을 버리고 예외 처리를 하는 본질에 대해 생각해 봤습니다. 클라이언트에게 예외에 따른 적절한 응답을 해주면 되고 코드가 깔끔한 게 우선이라는 생각을 가지고 리팩터링 했습니다. 만들고 나니까 훨씬 이해하기 쉬운 구조가 되었다는 생각이 들고 예외 처리는 응답하는 방향이니까 Dao > Service > Controller 순으로 계층이 뒤집히는 걸까 생각이 들기도 하고, 기존 코드에 비해 이해하기도 쉽고 처리도 깔끔한 구조가 됐다고 생각합니다.

현재 예외는 아래 구조입니다.

- SubwayException : 처리하기를 원하는 가장 상위 예외
- exception.web 패키지 : Http 기준으로 묶은 예외
- exception.application 패키지 : 앱 전반적으로 사용하는 포괄적인 예외
- 각 도메인 패키지 내부 예외 : 포괄적인 예외로 표현하기 어렵다고 생각하는 예외

```
코니가 보기에 제가 이상한 말을 했다던가, 코드가 어색하다 싶은 부분이 있으면 꼭 알려주세요! 
```

2021-06-03 05:14 UTC, ggyool commented on src/main/java/wooteco/subway/exception/BusinessRelatedException.java
> +package wooteco.subway.exception;
아래 커멘트에 예외 처리에 대한 생각을 적었습니다.

2021-06-03 05:18 UTC, ggyool commented on src/main/java/wooteco/subway/line/application/LineService.java
>      }
계층에 대한 생각을 버리니 Dao에서 적절한 예외로 변환시켜주는 게 당연해 보였습니다.
또한 Unique 제약 위반한 경우 DuplicateKeyException 를 잡아서 처리했는데, Jpa에서는 다른 예외를 발생시킨다는 내용을 봤습니다. 그래서 처리할 수 있는 부분은 Dao에서 처리해야 한다는 생각으로 바뀌었습니다.

2021-06-03 05:25 UTC, ggyool commented
꼼꼼한 피드백 감사합니다 🙇‍♂️
저번 제출 때 많은 테스트를 하지 못하고 낸 점 죄송합니다 😅
프론트 협업 미션 후 이번 미션을 했던지라 프론트에서 테스트할 수 있다는 사실을 잊고 있었네요..
리팩터링하며 기존 코드나 제가 만든 코드나 신경 쓰지 않고 예측 가능한 예외 상황을 최대한 꼼꼼하게 처리하려고 노력했습니다.
더 처리해야 할 예외가 있거나 의아하게 처리한 부분이 있다면 알려주세요! 
또한 예외 처리 구조를 개선했습니다. 이 부분도 또한 부탁드립니다!

2021-06-04 17:01 UTC, choihz commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Station downStation = stationService.findStationById(request.getDownStationId());
예외를 다르게 던지기 위해 두 메서드를 만드는 게 좋은 방법인지는 고민이 좀 더 필요할 것 같아요. 둘의 차이를 인지하기 힘들어서 결국 아무거나 쓰게 될 것 같은데 🙄 저라면 그냥 `findStationById()`만 놔둘 것 같네요.

2021-06-04 17:02 UTC, choihz commented on src/test/java/wooteco/subway/line/domain/LinesTest.java
> +        stationD = new Station(4L, "stationD");
> 지하철 노선도에 빠삭한 사람이라면 기존 알고 있던 노선 정보와의 불일치 때문에 헷갈리고 모르는 사람이면 차라리 A -> B -> C 로 만들어서 이름으로 순서를 파악할 수 있게 하고 싶었습니다.

이런 측면도 있을 수 있겠네요. 다른 크루들을 보니 `중간곰역` 같은 걸 만들어 사용하던데 이런 방법도 나쁘지 않다고 생각합니다 😊

2021-06-04 17:10 UTC, choihz commented on src/test/java/wooteco/subway/path/domain/PathTest.java
> +        );
이 코멘트의 의도는 `setUp()` 메서드의 모든 부분을 메서드로 분리하라는 건 아니었고 테스트 메서드에서의 직접 참조가 없는, 그리고 이번 테스트 맥락에서는 크게 중요치 않으면서 초기화 로직이 복잡한 부분만 분리하시라는 의미였어요.

> 테스트 코드를 이해한 상황이라면 걸리적거리는 존재가 될 수 있지만, 테스트 코드를 처음 읽는 상황이라서 setUp을 읽어야 하는데 `@test`가 꽤 많은 상황이면 아래쪽에 내려가 있으면 불편할 것 같습니다.

중간곰도 말씀하신 것처럼 테스트 코드를 파악하려면 결국엔 다 읽어야 해서 메서드로 분리를 해도 아래로 갔다 와야 하죠 😢 이런 단점도 있고 수정된 테스트 코드는 서초, 교대, 강남 등 인지하기 쉬운 데이터를 이용하도록 바뀌었으니 이젠 그냥 `setUp()`에 다 있어도 될 것 같기도 하고... 🙄 정답이 없는 문제이므로 중간곰이 스스로 느끼기에 더 좋은 방법을 선택하시면 될 것 같아요.

2021-06-04 17:11 UTC, choihz commented on src/test/java/wooteco/subway/path/application/PathRouterTest.java
> +    }
(수정된 코드로 보자면) 서초 → 강남 외의 더 다양한 케이스를 고려해 보시라는 의미였어요!

2021-06-04 17:18 UTC, choihz approved these changes
안녕하세요, 중간곰!

피드백을 아주 잘 반영해 주셨네요 👍 더이상 피드백 드릴 부분은 없어 보이고 머지되어도 충분한 것 같아요! 다만 (의지가 넘치시는 상황이니) 추가 학습하다가 궁금한 점이 있으시다면 언제든 DM 주세요 ㅎㅎ 그동안 정말 고생 많으셨어요. 언젠가 다시 만나요~ 👋

2021-06-04 17:18 UTC, merged