[Spring 경로 조회 - 1단계] 라쿤(이병훈) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #195
Opened 2022-05-18 05:26 UTC by nbalance97

안녕하세요 에단!! 만나뵙게 되어 반갑습니다😊

이번 미션의 경우, 외부 라이브러리를 사용하게 되어 구현 자체는 빠르게 끝마칠 수 있었습니다😀

부족한 코드이지만 잘 봐주셨으면 좋겠습니다😀

2022-05-18 13:49 UTC, Laterality requested changes
안녕하세요 라쿤.

리뷰어 에단입니다 👋 

간단한 피드백을 남겨드렸어요. 확인 부탁드려요.

궁금하신 점은 언제든 DM 주세요 :)

2022-05-18 13:49 UTC, Laterality commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    public void update(Long id, Line line) {
`line`에 `id`가 있는데 `id` 파라미터를 별도로 받는 이유가 있을까요?

2022-05-18 13:49 UTC, Laterality commented on src/main/java/wooteco/subway/domain/FareCalculator.java
> +            return DEFAULT_FARE + SURCHARGE_PER_UNIT * 8 + (int) (
`8`은 매직넘버일까요?

2022-05-18 13:49 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
필요한 생성자일까요?

2022-05-18 13:49 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Section.java
> +    private Long downStationId;
이 필드들은 박스타입으로 선언하신 이유가 있을까요?

2022-05-18 13:49 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Section.java
> +    public boolean isMoreDistance(Section currentSection) {
`isLongerDistance`는 어떨까요?

2022-05-18 13:49 UTC, Laterality commented on src/main/java/wooteco/subway/ui/ErrorControllerAdvice.java
> +        return ResponseEntity.badRequest().header("error", exception.getMessage()).build();
응답 바디 대신 헤더에 오류 메시지를 넣으신 이유가 있을까요?

2022-05-18 13:49 UTC, Laterality commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +import static org.springframework.test.annotation.DirtiesContext.MethodMode.BEFORE_METHOD;
불필요한 import는 제거해주세요~

2022-05-19 02:32 UTC, nbalance97 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    public void update(Long id, Line line) {
생각해보니 정말 그렇네요😅 line에 id까지 넣어서 보내주는 방식이 훨씬 명확할 거 같아요! 이 부분은 수정했습니다~!

2022-05-19 04:30 UTC, nbalance97 commented on src/main/java/wooteco/subway/domain/FareCalculator.java
> +            return DEFAULT_FARE + SURCHARGE_PER_UNIT * 8 + (int) (
8도 상수로 뺄 수 있겠네요! 상수로 빼서 처리하였습니다~😊

2022-05-19 04:33 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/ErrorControllerAdvice.java
> +        return ResponseEntity.badRequest().header("error", exception.getMessage()).build();
오류가 발생하였을 때 더 명확하게 오류 메시지를 보기 위해서 헤더에 두었습니다!

더 생각해 보니.. `에러 메시지` 자체는 응답 바디에 들어가는 것이 더 명확해 보이네요😥

2022-05-19 05:05 UTC, nbalance97 commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +import static org.springframework.test.annotation.DirtiesContext.MethodMode.BEFORE_METHOD;
제거했습니다!! 😅

2022-05-19 05:21 UTC, nbalance97 commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
@RequestBody에서 사용하기 위해 dto에 기본 생성자를 만들어 주었는데, 

그 때와 혼동하여 도메인에도 기본 생성자를 만들었었네요😅 도메인 뿐 아니라 response에서도 기본 생성자를 제거해 주었습니다~!

2022-05-19 05:30 UTC, nbalance97 commented on src/main/java/wooteco/subway/domain/Section.java
> +    public boolean isMoreDistance(Section currentSection) {
아하! 거리니까 More보다 Longer이 더 직관적인 표현인거 같습니다!! 

메서드 명을 짓는게 뭔가 정말 어렵게 느껴지는거 같아요😅 수정하였습니다!!

2022-05-19 06:46 UTC, nbalance97 commented on src/main/java/wooteco/subway/domain/Section.java
> +    private Long downStationId;
박싱 타입으로 선언해 둔 이유는 기존에 제공된 DTO가 박싱 타입으로 제공되었기 때문입니다! 
이를 맞추어주기 위해 박싱 타입으로 선언해 두었었는데, 지금 보니 굳이 박싱타입으로 해두어야 했었나 싶네요😅

이는 박싱 타입을 기본 타입으로 풀었습니다!

2022-05-19 14:56 UTC, Laterality approved these changes
안녕하세요 라쿤.

피드백을 빠르게 반영해주셨네요.

이번 단계는 이만 머지하도록 할게요.

남겨드린 코멘트는 다음 단계 진행하시면서 참고해주세요.

추가로, 일부 테스트가 실패하고 있는데 이 부분도 함께 확인 부탁드려요 :)

수고 많으셨습니다.

2022-05-19 14:56 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Section.java
> +    private Long downStationId;
메서드의 인자와 반환 타입들은 여전히 박싱타입을 사용하고 있네요. 이 부분도 변경하면 어떨까요?

2022-05-19 14:56 UTC, Laterality commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private boolean isExistById(Long id) {
사용되는 곳이 모두 부정형(`!isExistById(id)`)으로 사용하고 있네요. 존재하는지 여부 대신 존재하지 않는지 여부를 반환하면 어떨까요?

2022-05-19 14:56 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Line.java
> +    private int extraFare;
2단계의 요구사항이 미리 반영된 걸까요?

2022-05-19 14:56 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Path.java
> +    public List<Long> calculateShortestPath(Long source, Long target) {
반환되는 `List<Long>`이 무엇을 의미하는지 나타낼 수 있는 방법이 있을까요?

2022-05-19 14:56 UTC, Laterality commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void update(final long id, final LineRequest lineRequest) {
이전에 드린 코멘트와 비슷하네요. `id`가 DTO에 포함돼 있지 않은 것은 `LineRequest`를 생성과 수정 양쪽에서 재사용하기 위함일까요?

2022-05-19 14:56 UTC, Laterality commented on src/main/java/wooteco/subway/ui/ErrorControllerAdvice.java
> +        return ResponseEntity.internalServerError().body(exception.getMessage());
DB 쿼리 중에 예외(e.g., `DataIntegrityViolationException`)가 발생하면 예외 메시지에 쿼리 내용이 들어있는 경우도 있는데요. 이를 사용자에게 그대로 노출해도 괜찮을까요?

2022-05-19 14:56 UTC, Laterality commented on src/main/resources/line.sql
> +create table Line(
`schema.sql`과는 다른 용도의 쿼리일까요?

2022-05-19 14:56 UTC, merged

2022-05-20 00:30 UTC, nbalance97 commented on src/main/java/wooteco/subway/domain/Line.java
> +    private int extraFare;
1단계의 API 명세에 extrafare이 존재하여 LineRequest에서 받아온 데이터를 Line에 넣어 주었습니다😊

2022-05-20 00:37 UTC, nbalance97 commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void update(final long id, final LineRequest lineRequest) {
id는 url의 query string으로 들어오고, 이외의 데이터는 body로 들어와서 이를 합쳐주는 것을 Service에서 하기로 결정하여 

DTO 자체에는 id를 포함하지 않았습니다!😄

2022-05-20 00:37 UTC, nbalance97 commented on src/main/java/wooteco/subway/domain/Section.java
> +    private Long downStationId;
변경이 덜 된 부분이 있었군요! 수정했습니다~!🙂

2022-05-20 00:40 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/ErrorControllerAdvice.java
> +        return ResponseEntity.internalServerError().body(exception.getMessage());
아하 맞네요!! getMessage를 body에 실어서 보내는건 예측 가능한 예외에 해당하고, 예측 불가능한 예외에 대해서는 

getMessage를 보내주지 않는 것이 좋겠네요😄

2022-05-20 00:41 UTC, nbalance97 commented on src/main/resources/line.sql
> +create table Line(
dao 테스트에서 모든 테이블을 추가할 필요는 없어 보여서 테스트에서 사용하기 위해 개별 sql을 구성했습니다!!

2022-05-20 01:24 UTC, nbalance97 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private boolean isExistById(Long id) {
부정형으로 쓰는게 이해가 어려울 수도 있겠네요! isExistById를 isNotExistById로 바꿔 주었습니다!

2022-05-22 05:13 UTC, nbalance97 commented on src/main/java/wooteco/subway/domain/Path.java
> +    public List<Long> calculateShortestPath(Long source, Long target) {
List<Long>이 무엇을 의미하는지가 애매하게 느껴지는 것 같아 List<Station>으로 리턴하도록 변경하였습니다!!😊