[Spring 경로 조회 - 1단계] 오찌(오지훈) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #226
Opened 2022-05-18 09:05 UTC by Ohzzi

안녕하세요 제이! :) 저는 오찌라고 합니다!
이번에 경로 조회 미션으로 처음 만나게 되어 반갑습니다 ㅎㅎ
코드에 대해 많은 이야기를 나누고 싶어요!
잘부탁드립니다 😄

2022-05-19 13:10 UTC, JunHoPark93 requested changes
안녕하세요 오찌! 리뷰어 제이입니다.
1단계 빠르게 잘 해주셨네요.
간단하게 몇가지 남겼는데 확인부탁드려요~

2022-05-19 13:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/PathService.java
> +                       PathStrategy pathStrategy, FareStrategy fareStrategy) {
파라미터 개행 기준은 어떤식으로 정하셨나요?!

2022-05-19 13:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/ui/PathController.java
> +                                                 @RequestParam int age) {
이부분은 반영하지 않아도 되지만 파라미터를 한번에 받을 수 있는 방법이 있을지 찾아보셔도 좋을거같아요!

2022-05-19 13:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/strategy/DijkstraPathStrategy.java
> +public class DijkstraPathStrategy implements PathStrategy {
구현체가 하나인데 인터페이스로 관리하게된 계기가 있을까요?

2022-05-19 13:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/PathService.java
> +                fareStrategy.calculateFare(path.getDistance()));
리턴문 안에서 해주는 작업들의 가독성을 높여보면 어떨까요?

2022-05-19 13:10 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +    void showShortestPath() {
테스트가 부족한것같아요. 좀 더 추가해보면 어떨까요?

2022-05-20 03:03 UTC, Ohzzi commented on src/main/java/wooteco/subway/service/PathService.java
> +                       PathStrategy pathStrategy, FareStrategy fareStrategy) {
원래는 따로 개행 하지 않고 기준(아마 120자였던 것 같은데요)을 넘어가면 자동으로 개행되는 IDE의 기능을 사용하고 있었는데요, 이 부분에서는 페어 코드를 가져오다 보니까 두 개씩 나눠진 것 같아요...! 저는 다시 제 방식대로 바꾸겠습니다!

2022-05-20 03:05 UTC, Ohzzi commented on src/main/java/wooteco/subway/domain/strategy/DijkstraPathStrategy.java
> +public class DijkstraPathStrategy implements PathStrategy {
지금은 다익스트라 알고리즘을 이용한 최단거리 경로를 구하지만 지하철 경로는 최소환승, 최소요금 등의 방식이 있을 것 같다는 의견에서 추상화를 하기로 합의했었습니다!

2022-05-20 03:06 UTC, Ohzzi commented on src/main/java/wooteco/subway/service/PathService.java
> +                fareStrategy.calculateFare(path.getDistance()));
매개변수 분리와 적절한 개행으로 해볼게요!

2022-05-21 23:37 UTC, JunHoPark93 approved these changes
안녕하세요 오찌!
리뷰 반영하느라 고생많으셨습니다.
코멘트 몇가지 추가로 남겨두었는데 다음단계 진행할때 확인부탁드려요~

2022-05-21 23:37 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/ui/PathController.java
> +        System.out.println(pathRequest);
반영해보셨네요 👍 
sysout은 제거해도될거같아요!

2022-05-21 23:37 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +        Long samjeonId = requestPostStationAndReturnId(new StationRequest("삼전역"));
테스트 중복에 대해서 어떻게 줄일수있을지 고민해보셔도 좋을거같아요

2022-05-21 23:37 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return stations;
stream으로 개선해볼수있을거같아요!

2022-05-21 23:37 UTC, merged