[Spring 경로 조회 - 1단계] 차리(이찬주) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #235
Opened 2022-05-19 02:03 UTC by cjlee38

안녕하세요~ 처음 뵙겠습니다.

부족한 코드 리뷰해주셔서 감사하다는 말씀 드립니다.

아직 도메인이나 테스트 쪽에 부분적으로 수정해야 할 부분이 있긴 한데, 우선 기초적인 완성은 했다고 생각이 들어서, 리뷰어분과 같이 풀어나가면 좋을 것 같아 제출드립니다.  감사합니다!

p.s. 리뷰요청을 드렸다고 생각했는데 깜빡했습니다. 양해를 구합니다 ㅠㅠ

2022-05-20 14:07 UTC, JunHoPark93 requested changes
안녕하세요 차리! 리뷰어 제이입니다.
1단계 미션 잘해주셨어요. 
몇 가지 코멘트 남겼는데 확인하시고 의견 및 반영 부탁드려요~

2022-05-20 14:07 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +public class PathAcceptanceTest extends AcceptanceTest {
깨지는 테스트가 있는지 다시 확인 부탁드려요

2022-05-20 14:07 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +    public static PathFinder from(LineSeries lineSeries) {
생성자는 private이 되어야 되지 않을까요?

2022-05-20 14:07 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +        return new PathFinder(graph);
stream을 사용해보는건 어떨까요?

2022-05-20 14:07 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/PathService.java
> +public class PathService {
애노테이션이 의도치 않게 달린거같아요

2022-05-20 14:07 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/ui/PathController.java
> +        @RequestParam Long age) {
파라미터를 한번에 묶어볼수도있을까요?
(이 부분은 반영하지 않아도 되지만 생각해보면 좋을거같아서 남겨요~)

2022-05-20 14:07 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +        return foundPath;
Optional을 사용해보면 어떨까요?

2022-05-20 14:07 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +            throw throwPathNotFound(source, destination);
path를 총 두 번 계산하는것으로 보여요. 비용절감을 위해 Path를 한번만 계산하게 할 수 있을까요?
구조도 좀 더 개선될거에요.

2022-05-21 08:17 UTC, cjlee38 commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +public class PathAcceptanceTest extends AcceptanceTest {
<img width="716" alt="image" src="https://user-images.githubusercontent.com/52564093/169642682-a60c3e02-74aa-429e-b000-4c407ad903cd.png">

제 로컬에서는 잘 동작하는 것을 확인했는데, 혹시 어떤 부분에서 깨지는지 한번 확인 부탁드려도 될까요 ?

2022-05-21 08:17 UTC, cjlee38 commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +public class PathAcceptanceTest extends AcceptanceTest {
<img width="716" alt="image" src="https://user-images.githubusercontent.com/52564093/169642682-a60c3e02-74aa-429e-b000-4c407ad903cd.png">

제 로컬에서는 잘 동작하는 것을 확인했는데, 혹시 어떤 부분에서 깨지는지 한번 확인 부탁드려도 될까요 ?

2022-05-21 08:17 UTC, cjlee38 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +    public static PathFinder from(LineSeries lineSeries) {
그렇네요.. 해당 부분 반영하였습니다!

2022-05-21 08:19 UTC, cjlee38 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +        return new PathFinder(graph);
stream 을 통해 불필요한 side-effect를 만드는 것은 함수형 프로그래밍의 취지에 어긋난다고 생각해서 의도적으로 for문을 사용하였습니다 ! 구조를 개선해서 stream을 활용하는 방법도 고민해봤는데 아직 떠오르지 않네요..

2022-05-21 08:19 UTC, cjlee38 commented on src/main/java/wooteco/subway/service/PathService.java
> +public class PathService {
헉 ㅋㅋ 이게 무슨일이죠.. 바로 수정하였습니다.

2022-05-21 08:20 UTC, cjlee38 commented on src/main/java/wooteco/subway/ui/PathController.java
> +        @RequestParam Long age) {
`@ModelAttribute` 어노테이션을 통해 `PathRequest` 라는 클래스로 받아낼 수 있도록 수정하였습니다~

2022-05-21 08:26 UTC, cjlee38 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +        return foundPath;
> API Note:
Optional is primarily intended for use as a method return type where there is a clear need to represent "no result," and where using null is likely to cause errors.

내부적으로 null에 대한 여부를 체크하기 위해 Optional을 사용하는 것은 불필요한 연산이라고 생각했습니다. 또한, Optional을 return한다면 호출하는쪽에서 이를 핸들링해줘야 하는데, "경로가 존재하지 않는다" 라는 같은 맥락을 별도의 메소드에서 처리할 필요가 없을 것 같아 `findPath` 내부적으로 처리하는 것이 타당하다고 생각했습니다 !

현재는 null에 대한 모든 검증이 `findPath` 내부적으로 동작하도록 변경하였습니다.

```java
private GraphPath<Station, DefaultWeightedEdge> findPath(Station source, Station destination) {
    try {
        final GraphPath<Station, DefaultWeightedEdge> foundPath = dijkstraPath.getPath(source, destination);
        return Objects.requireNonNull(foundPath);
    } catch (IllegalArgumentException | NullPointerException e) {
        throw throwPathNotFound(source, destination);
    }
}
```

2022-05-21 08:27 UTC, cjlee38 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +            throw throwPathNotFound(source, destination);
처음에는 Graph로 여러가지 연산을 할 수 있다는 생각(2단계 때 유연하게 대처할 수 있지 않을까 하는 막연한 생각이었습니다 ㅎㅎ)으로 graph 그 자체를 갖도록 하였는데, 이에 관련한 것은 추후 요구사항이 변경되었을 때 대처할 사항이지, 현재 당장 고민할 문제는 아닌 것 같습니다.

따라서 현재는 초기 객체 생성 당시 `DijkstraShortestPath` 까지 만들도록 변경하였습니다.

2022-05-22 00:23 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +        return foundPath;
null이면 문제가 발생해서 api note에 말씀주신 내용을 충족시키는거같은데요, 아래와같이 개선해볼수있을거같아요.
```
return Optional.ofNullable(dijkstraPath.getPath(source, destination))
                    .orElseThrow(() -> throwPathNotFound(source, destination));
```

2022-05-22 00:26 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +            throw throwPathNotFound(source, destination);
음 PathService의 findPath메서드보시면 메서드내 로직을 수행하면서 findPath가 두번불리는거같은데요, getDistance메서드내에서 계산된 path를 넘겨주면 계산을 다시 할 필요가 없지 않을까에 대한것이었어요.
이 부분 다시 한번 확인부탁드리고 다음단계에 의견 부탁드려요~

2022-05-22 00:27 UTC, JunHoPark93 approved these changes
안녕하세요 차리!
리뷰반영하느라 고생하셨어요.
남겨주신 내용에 코멘트 달아두었는데 다음단계 진행할때 확인부탁드려요~

2022-05-22 00:27 UTC, merged