[Spring 경로 조회 - 1단계] 헌치(박지우) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #236
Opened 2022-05-19 02:12 UTC by BETTERFUTURE4

에단, 안녕하세요~!

저번 지하철 미션의 호호 코드를 가져와 미션 진행했습니다!
테코톡과 병행해 준비하다보니 도메인 리팩토링을 못한 채로 제출하게 됐네요ㅠㅠ
리뷰 잘 부탁드립니다!
궁금한게 있다면 코멘트로 따로 남길게요!ㅎㅎ

2022-05-19 15:26 UTC, Laterality requested changes
안녕하세요 헌치. 

리뷰를 맡은 에단입니다. 

깔끔하게 구현해주셨네요 👍 

몇가지 코멘트 남겨드렸어요. 확인 부탁드릴게요.

궁금하신 점은 언제든 DM 주세요 :)

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +    private SectionEntity toSectionEntity(long id, SectionEntity section) {
`save` 메서드에서만 호출되는 메서드네요. 관련된 메서드끼리 모여있도록 `save` 아래에 두면 어떨까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/dao/entity/SectionEntity.java
> +    private final Long downStationId;
엔티티의 `id`는 새로 생성된 경우 null로 나타내기 위해 `Long` 타입을 사용하신 걸로 생각했는데요. 다른 필드도 `Long`으로 나타낼 필요가 있을까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Section.java
> +    private void validate(int distance) {
무엇을 validate하는지 혹은 어떤 조건을 validate하는지 메서드명에 나타내보면 어떨까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Sections.java
> +    public List<Section> findUpdateSections(Section section) {
Update는 동사인데, `updatedSections`를 찾는 메서드일까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private List<Section> fillSection(List<Section> sections, Station next) {
메서드를 호출하는 입장에서는 `next` 파라미터가 무엇을 의미하는지 알 수 있을까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private Station findNextStation(List<Section> sections, Station next, List<Section> result) {
`find` 뿐만 아니라 인자로 받은 `result`에 `add`도 하고 있네요. 이 메서드에 더 적절한 이름이 있을까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/domain/SubwayGraph.java
> +        return (int) ((Math.ceil((distance - 50 - 1) / 8) + 1) * 100) + 2050;
매직 넘버는 상수로 분리하면 어떨까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +public class LineRepository {
DB 엔티티와 도메인 객체 사이의 변환을 책임지는 계층인가보네요 💯 

이 영역을 별도로 두었을 때 어떤 장점이 있었나요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void updateById(Long id, LineUpdateRequest request) {
`id`가 `LineUpdateRequest` 내에 포함되면 어떨까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/service/dto/request/PathsRequest.java
> +    private final int age;
2단계 요구사항이 반영된 걸까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/service/dto/response/LineResponse.java
> +
불필요한 변경사항일까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/ui/SubwayControllerAdvice.java
> +        log.debug(e.getMessage());
예기치 못한 곳에서 예외가 발생하면 로그만 보고 어느 부분을 수정해야 하는지 파악할 수 있어야 할 텐데요. 예외의 메시만으로 충분할까요?

2022-05-19 15:26 UTC, Laterality commented on src/main/java/wooteco/subway/ui/SubwayControllerAdvice.java
> +        return ResponseEntity.badRequest().body(new ErrorResponse("서버 에러가 발생했습니다."));
💯 

예외 중에는 사용자에게 노출되면 곤란한 메시지를 담고 있는 경우도 있습니다. 이런 경우에는 사용자에게는 적당한 메시지를 보여주고 상세 정보를 로그로 남기는 게 중요합니다 :)

2022-05-19 15:26 UTC, Laterality commented on src/test/java/wooteco/subway/domain/JGraphTest.java
> +public class JGraphTest {
학습테스트 👍

2022-05-21 14:12 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +    private SectionEntity toSectionEntity(long id, SectionEntity section) {
메소드 순서를 연관된 메소드끼리 인접하도록 재배치 했습니다!

2022-05-21 14:15 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/dao/entity/SectionEntity.java
> +    private final Long downStationId;
이미 값이 station 등에서 엔티티로 들어올 때 
Long형태로 들어오기 때문에 그대로 박싱된 타입을 썼었어요.
오토박싱/언박싱 과정에서 시간이 소요될 것 같아서요.
혹시 현재 박싱된 클래스를 쓴다면 어떤 문제들이 생길 수 있는지 알 수 있을까요?

2022-05-21 14:20 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/domain/Section.java
> +    private void validate(int distance) {
validateMinDistance로 메서드명 수정했습니다!

2022-05-21 14:20 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    public List<Section> findUpdateSections(Section section) {
네! 문법에 맞게 이름 수정했습니다!

2022-05-21 14:24 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private List<Section> fillSection(List<Section> sections, Station next) {
첫 상행역을 입력받아야 해서 firstStation으로 파라미터명을 변경했습니다!

2022-05-21 14:56 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private Station findNextStation(List<Section> sections, Station next, List<Section> result) {
생각해봤는데 메소드 안에서 두가지 기능이 동시에 있고, 
명령-쿼리 원칙에 위배되는 것 같아 
메소드를 분리했습니다!

2022-05-21 15:24 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/domain/SubwayGraph.java
> +        return (int) ((Math.ceil((distance - 50 - 1) / 8) + 1) * 100) + 2050;
요금 관련 기능들을 분리하며 매직넘버도 상수로 따로 뺐습니다!

2022-05-21 15:45 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +public class LineRepository {
페어의 코드를 통해 해당 부분들을 적용시켰습니다.
DB를 통해 가져온 entity를 도메인으로 변환하는 과정을 분리하고, 
그 과정에서 추가적인 검증 로직을 넣을 수 있어 좋았어요!

혹시 레포지토리와 Dao를 나누는 과정에서 추가적으로 고려해야할 사항들이 있을까요?

2022-05-21 15:52 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void updateById(Long id, LineUpdateRequest request) {
setter를 추가해 LineUpdateRequest에 아이디를 이후에 설정해줄 수 있도록 코드 수정했습니다!

2022-05-21 15:54 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/service/dto/request/PathsRequest.java
> +    private final int age;
경로조회 api 스펙에 나이가 포함되어있어 우선 request에 추가했습니다!

2022-05-21 15:59 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/service/dto/response/LineResponse.java
> +
앞으로는 커밋 목록을 보며 좀더 신경쓸게요!

2022-05-21 16:04 UTC, BETTERFUTURE4 commented on src/main/java/wooteco/subway/ui/SubwayControllerAdvice.java
> +        log.debug(e.getMessage());
log.error("error : ", e); 형식으로 수정해 에러 발생이유 및 위치를 확인할 수 있도록 수정했습니다!

2022-05-21 16:18 UTC, BETTERFUTURE4 commented
안녕하세요 에단!
피드백 반영해 리팩토링 진행했습니다!
앞의 피드백 답변들 중 궁금한 부분들은 👀 이모지를 추가해 체크해뒀습니다!

### 추가 구현사항
- 요금정책 분리 및 1차 리팩토링

### 피드백 반영
- [x] 한번만 쓰이는 private 메소드의 경우 쓰이는 곳 밑에 두기
- [x] 엔티티의 id는 새로 생성된 경우 null로 나타내기 위해 Long 타입을 사용 -> 다른 필드도 Long으로 나타낼 필요가 있을까요?
    - 이미 값이 엔티티에 들어올 때 Long으로 들어오기 때문에 그대로 뒀다. 오토박싱/언박싱 과정에서 시간이 소요될 것 같았다.
    - 혹시 그럼에도 박싱된 클래스를 쓰지 않는 편이 낫다면 그 이유는 무엇인가요?
- [x] 무엇을 validate하는지 혹은 어떤 조건을 validate하는지 메서드명에 나타내보면 어떨까요?
- [x] Update는 동사인데, updatedSections를 찾는 메서드일까요?
- [x] 메서드를 호출하는 입장에서는 next 파라미터가 무엇을 의미하는지 알 수 있을까요?
- [x] find 뿐만 아니라 인자로 받은 result에 add도 하고 있네요. 이 메서드에 더 적절한 이름이 있을까요?
- [x] 매직 넘버는 상수로 분리하면 어떨까요?
- [x] DB 엔티티와 도메인 객체 사이의 변환을 책임지는 계층을 별도로 두었을 때 어떤 장점이 있었나요?
- [x] id가 LineUpdateRequest 내에 포함되면 어떨까요?
- [x] 2단계 요구사항이 반영된 걸까요?
- [x] 예외 시 log.error(); 추가

궁금한 부분들은 커멘트로 남기겠습니다! 
잘 부탁드려요! 감사합니다🥺

2022-05-22 04:11 UTC, Laterality approved these changes
안녕하세요 헌치.

코멘트가 많았는데, 잘 반영해주셨네요 👍 

이번 단계는 이만 머지하도록 할게요.

고생 많으셨습니다 :)

2022-05-22 04:11 UTC, Laterality commented on src/main/java/wooteco/subway/service/dto/response/LineResponse.java
> +
저도 커밋하기 전에 변경한 파일들을 다시 살펴보는 습관이 있는데요. 작성 중에 남겨뒀던 주석이나 불필요한 코드, IDE에서 만들어진 의미 없는 변수명 등이 있는지 다시 한 번 살펴보는 습관을 들이시면 도움이 될 거라 생각해요 :)

2022-05-22 04:11 UTC, Laterality commented on src/main/java/wooteco/subway/service/dto/request/PathsRequest.java
> +    private final int age;
스펙에 있던 내용이군요. 이해했습니다 🆗

2022-05-22 04:11 UTC, Laterality commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +public class LineRepository {
검증 로직을 추가하다보면 서비스나 도메인에서 검증해야 할 것들이 무심코 들어가는 경우도 생길 수 있을 것 같아요.

그런 부분만 주의하시면 큰 문제는 없어보여요 👍

2022-05-22 04:11 UTC, Laterality commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void updateById(Long id, LineUpdateRequest request) {
setter를 어떻게 하면 제거할 수 있을지 고민해보시는 것도 도움이 될 거에요 :)

2022-05-22 04:11 UTC, Laterality commented on src/main/java/wooteco/subway/dao/entity/SectionEntity.java
> +    private final Long downStationId;
오토박싱/언박싱 비용도 고려할 만한 부분이에요. null이 들어가게 될 가능성이 생긴다는 점이 더 큰 문제점이라고 봐요.

변수에 null 값은 가급적 들어가지 않도록(혹은 들어갈 수 없도록) 하는 것이 좋습니다. 기본값이나 null을 대신할 값을 사용할 수 있다면 그것도 좋겠고요(e.g., `id`에 null 대신 0을 사용한다던지, `String` 필드에 null 대신 빈 문자열을 사용하는 등).

`SectionEntity`의 경우 생성자에서 `id`를 제외한 필드는 `long` 타입으로 선언돼 있는 걸로 봐서는 null을 허용할 필요는 없어보이기도 하네요.

2022-05-22 04:12 UTC, merged