[Spring 경로 조회 - 2단계] 판다(김건웅) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #245
Opened 2022-05-19 07:32 UTC by woong7

안녕하세요 앨런, 판다입니다!

2단계 추가기능을 마저 구현해서 제출합니다. 

1단계에서 피드백 주셨던 사항들에 대한 수정을 포함하였습니다. 

굳이 필요하지 않은 것이 아닌가 하는 고민은 있었지만, 구간 관련 기능들과 최단경로 탐색 기능들을 인터페이스를 통해 구현하여, 다형성을 얻어 보고자 하였습니다. 

요금 계산 부분에 있어서, 거리 관련 계산 로직과 연령 관련 계산 로직을 각각 enum을 사용하여 분리하였습니다. 
전반적으로 과설계가 되어있지 않은지 궁금합니다. 

전체적인 도메인이 아직 db 의존적으로 설계되어 있는 것 같다는 생각이 계속 드는 것 같습니다. 
피드백 주실 사항에 더해서, 좀 더 도메인 중심적인 방향으로 설계를 변경해보겠습니다. (ex. Line이 List<Section>을 필드로 갖도록 하기)

자세한 피드백 감사드립니다!

2022-05-20 18:16 UTC, hongbin-dev requested changes
안녕하세요 판다!
2단계 미션 구현 잘해주셨군요! 특히 나이별 요금, 거리별요금을 전략으로 나눠주신 게 인상적이네요 💯
ControllerAdvice에서 모두 400으로 응답하고있는데 이 부분도 세분화하면 좋겠네요.
추가로 코멘트와 질문남겼으니 확인해주세요~

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/fare/Age.java
> +    }
중요한 비즈니스로직이라서 테스트를 작성해보면 좋을 것 같아요.

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/fare/Age.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당하는 연령대가 없습니다."));
어떨값으로 예외가 발생했는지 알려주면 좋을 것 같네요.

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/fare/Distance.java
> +        return Arrays.stream(Distance.values())
이 부분도 중요한 비즈니스로 보이는데요~ 테스트 작성해보면 좋을 것 같아요.

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/path/Path.java
> +    private final GraphPath<Long, PathEdge> graphPath;
도메인코드가 외부라이브러리에 의존하고있는데요.
이 부분을 개선할 수 없을까요? 그래프관련 라이브러리가 변경되면 도메인코드도 변경되어야할까요?

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/path/Path.java
> +    public static Path of(Graph<Long, PathEdge> graph, Long source, Long target, PathFindingStrategy pathFindingStrategy) {
PathFindingStrategy를 인터페이스로 분리하신 이유가 있을까요?

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/path/SubwayFactory.java
> +    public static Graph<Long, PathEdge> from(List<Section> sections) {
이쪽도 마찬가지입니다. 도메인패키지에 둔다면 약간어색한거같네요.

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/service/PathService.java
> +    public PathResponse searchPath(PathRequest pathRequest) {
https://github.com/woowacourse/atdd-subway-path/pull/172#discussion_r876037209

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/dto/PathRequest.java
> +    }
```suggestion
    private PathRequest() {
    }
```

2022-05-20 18:16 UTC, hongbin-dev commented on src/main/java/wooteco/subway/dto/PathRequest.java
> +    private int age;
입력의 대한 검증이 잘 안되고있는데요!  여기도 validation annotioan으로 입력검증을 해볼 수 있을 것 같네요

2022-05-21 14:27 UTC, woong7 commented on src/main/java/wooteco/subway/service/PathService.java
> +    public PathResponse searchPath(PathRequest pathRequest) {
PathRequest에서 age값에 대한 null 체크를 하고, 파라미터로 pathRequest를 넘기도록 하였습니다. 
혹시 이렇게 되면 age에 대한 wrapping이 없어도 괜찮을까요?

2022-05-21 18:39 UTC, woong7 commented
안녕하세요 앨런! 

첫 번째 리뷰 요청을 드린 이후로, 도메인 중심적인 설계로 전체적인 리팩토링을 진행해 보았습니다. 
이 과정에서 Service, Repository, domain, dao 등 각각의 레이어의 역할에 대해 고민을 많이 하게 되었습니다. 

특히, Entity나 Repository의 역할을 하는 무언가의 필요성을 느끼고 이를 도입하게 되었습니다. 

프로젝트의 전체적인 구조는 Controller - Service - Repository - DAO 의 순서로 되어 있는데, 

Contoller <-> Service 는 Request / Response 의 DTO 를, 
Service -> Repository 와 Repository -> DAO 는 Entity 객체를,
DAO -> Repository 와 Repository -> Service 는 Domain 객체를 각각 주고받고 있습니다. 

또한, 하나의 Service 객체는 하나의 Repository 객체에 대응하고, Repository 객체가 여러 DAO를 갖는 구조로 구현하였습니다. 
(ex. LineService는 LineRepository 만을 갖지만, LineRepository는 SectionDao, StationDao, LineDao 를 모두 갖는다. )

이러한 구조가 적절한지 여쭤보고 싶습니다!

피드백 주신 사항에 대한 반영으로는, 
1. Age / Distance 관련 로직에 대한 테스트 코드 추가
2. PathRequest에 Validation 추가.
3. Path가 외부 라이브러리에 의존하지 않도록 PathFactory 인터페이스를 상속하는 JgraphtPathFactory 구현체를 작성하여 주입받도록 구조 변경.

등이 있습니다. 

도메인이 db나 프레임워크에 의존하지 않도록 설계하는 것을 목표로 리팩토링을 진행한 결과, 코드가 전반적으로 많이 달라진 것 같습니다. 
많은 피드백 부탁드립니다. 감사합니다!

2022-05-22 12:48 UTC, hongbin-dev commented on src/test/java/wooteco/subway/domain/fare/AgeTest.java
> +class AgeTest {
👍

2022-05-22 12:48 UTC, hongbin-dev commented on src/main/java/wooteco/subway/service/PathService.java
> +    public PathResponse searchPath(PathRequest pathRequest) {
네 확인해보니 리터럴타입도 호환하는 것 같군요 👀

2022-05-22 12:59 UTC, hongbin-dev commented
우선 DAO와 Repository는 둘 중 하나만 사용해주셨으면 좋겠습니다. 도메인객체를 영속성레이어에서 가져오는 패러다임이 겹치는 것 같아요. 개인적으로 레이어가 한 단계 늘어나서 코드파악이 어려운점이 있었습니다.

또 도메인객체는 엔티티가 될 수 없나요? 엔티티를 별도로 분리해봤을 때, 어떤 장단점이 있었는지 말씀해주시면 좋을 것 같아요.

2022-05-22 13:00 UTC, hongbin-dev requested changes
안녕하세요 판다!
피드백 잘 적용해주셨군요! 코멘트관련된 답변과 추가 의견남겼으니 확인해주세요~ 🙂

2022-05-22 13:00 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/path/PathEdge.java
> +public class PathEdge extends DefaultWeightedEdge {
`public class PathEdge extends DefaultWeightedEdge {`
아직 여기 jgrapht의존이 남아있네요.

2022-05-22 17:02 UTC, woong7 commented
안녕하세요 앨런, 판다입니다! 

피드백 주신 사항이 많지 않아서 빠르게 반영해서 다시 제출합니다. 

1. Repository를 모두 제거하고, Service가 Dao 를 바로 갖도록 리팩토링하였습니다. 
2. PathEdge 도메인을 제거하고, 그래프가 Section을 edge로 바로 갖도록 변경하였습니다. 이에 따라 라이브러리 의존성 역시 제거되었습니다. 

감사합니다!

2022-05-23 16:32 UTC, hongbin-dev commented
> Service 레이어를 무작정 가볍게 만들고 싶은 욕심에 Repository와 Dao를 모두 사용했는데, 리팩토링을 진행하고 보니 둘 중 하나만 있는 것이 더 가독성이 좋은 것 같습니다.

DAO에서 책임을 나누다가 Repository라는 네이밍이 나온 것 같은데, 이 부분에 오해가 생길 수도 있어 제거요청드렸습니다. 제거하니 더 나은 것 같네요. 

또 도메인과 엔티티객체를 나눈것도 인상적이네요. 개인적으로 들이는 공(?)에 비해 아직까지 큰 이점을 느끼진 못했는데요. 판다는 도메인모델과 엔티티로 나누면서 어떠셨는지 공유해주셔도 좋을 것 같아요.

2022-05-23 16:36 UTC, hongbin-dev approved these changes
안녕하세요 판다!
피드백 반영해주신 거 잘 봤습니다! 도메인객체가 외부에 의존하지않도록 잘 반영해주셨군요 💯
이만 머지하겠습니다~!

2022-05-23 16:36 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/path/Path.java
> +        this.stations = stations;
```suggestion
    private Path(List<Section> sections, List<Station> stations) {
        this.sections = sections;
        this.stations = stations;
```
정적팩토리로 사용을 유도하시려면 private으로 막는게 좋겠네요~

2022-05-23 16:36 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/path/factory/JgraphtPathFactory.java
> +    }
현재 객체는 JgraphtPath객체, 이 메서드의 반환객체이름은 ShortestPath라는 네이밍은 어떨까요?

2022-05-23 16:36 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/line/Line.java
> +        this(null, name, color, extraFare, sections);
도메인을 저장할때 엔티티로 저장시키면, 이 생성자는 불필요하지 않을까요?

2022-05-23 16:36 UTC, hongbin-dev commented on src/main/java/wooteco/subway/domain/path/factory/JgraphtPathFactory.java
> +    private final PathFindingStrategy pathFindingStrategy;
저수준모듈은 도메인 밖의 다른 패키지로 옮겨도 좋을 것 같네요~

2022-05-23 16:36 UTC, merged

2022-05-23 16:48 UTC, woong7 commented
> > Service 레이어를 무작정 가볍게 만들고 싶은 욕심에 Repository와 Dao를 모두 사용했는데, 리팩토링을 진행하고 보니 둘 중 하나만 있는 것이 더 가독성이 좋은 것 같습니다.
> 
> DAO에서 책임을 나누다가 Repository라는 네이밍이 나온 것 같은데, 이 부분에 오해가 생길 수도 있어 제거요청드렸습니다. 제거하니 더 나은 것 같네요.
> 
> 또 도메인과 엔티티객체를 나눈것도 인상적이네요. 개인적으로 들이는 공(?)에 비해 아직까지 큰 이점을 느끼진 못했는데요. 판다는 도메인모델과 엔티티로 나누면서 어떠셨는지 공유해주셔도 좋을 것 같아요.

초기 코드는 도메인이 DB와 컨택하기 위한 구조로 설계되어 있었던 것 같습니다. 이에 따라 도메인이 수행해야 할 비즈니스 로직의 상당 부분이 DB로부터 데이터를 가져와야 작동할 수 있게 되었고, 서비스 레이어의 역할이 늘어날 수 밖에 없었습니다. 
이를 리팩토링 하는 과정에서, 도메인과 DB 테이블의 구조가 달라지게 되었습니다. 이 때 DAO에 도메인의 필드를 꺼내어 넘겨 줄 수도 있었지만, 이는 DAO가 받는 파라미터가 중구난방이 되는 것 같다는 느낌을 받았습니다. 
이를 해결하기 위해, 도메인과 대응하는 엔티티를 생성해서, DB와 컨택하기 위한 객체로 사용하였습니다. 
혹시나 로직이 변경되어 DAO에 넘겨주는 값이 달라지게 되더라도, DAO를 직접 수정하지 않고 엔티티만 수정해도 된다는 생각이 들었습니다. 
사실 가장 큰 부분은 코드가 깔끔하고 읽기 쉬워 보인다고 느낀 것이었습니다!

2022-05-26 17:04 UTC, hongbin-dev commented
경험 공유 감사합니다. 미션 고생많으셨어요!