[Spring 경로 조회 - 2단계] 배카라(박성우) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #256
Opened 2022-05-21 16:26 UTC by seong-wooo

# 안녕하세요 토니

2단계 미션 제출합니다 !

저를 혼내주세요.

2022-05-23 00:06 UTC, toneyparky requested changes
안녕하세요 배카라~! 리뷰 보내주신거 주말 동안 잘 확인했어요. 조금 답변이 늦어서 죄송해요 😭

이번 단계 미션 잘 확인해주셔서 혼낼(?) 부분은 없었어요. 다만 코드를 읽는 사람에게 도움이 될만한 가독성 측면에서 피드백 몇가지를 남겨봤으니 확인해보고 반영 부탁드릴게요! 

한주의 시작 화이팅이에요 😬

2022-05-23 00:06 UTC, toneyparky commented on docs/README.md
> +  - [x] 아기 (6세 미만) : 무료
기존 요구사항에 없는 새로운 요구사항을 도출했네요~!
기획 요구사항이 완벽하지 않기에 배카라가 해준 것 처럼 부족한 부분을 보충하고 기획자에게 공유해서 더 나은 프러덕을 만들어야해요!
너무 좋네요 💯

2022-05-23 00:06 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/AgeGroup.java
> +        public static final int TEENAGER_DC_RATE = 5;
RATE이라는 이름으로 상수가 명명되어 있네요. 하지만 할인율이라기에 약분이 되어 있어서 코드를 읽는 사람이 이해하는 데에 직관적이지 않다 생각해요.

`value - (value - COMMON_DC_FARE) * TEENAGER_DC_RATE` 이런 느낌으로 가되 `TEENAGER_DC_RATE`를 `0.2`정도로 둔다면 이해하기 더 쉬워질까요?

2022-05-23 00:06 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Fare.java
> +    public int getDiscountValue(AgeGroup ageGroup) {
해당 메서드를 사용하는 입장에서 할인할 값을 가져온다고 생각할까요 할인된 값을 가져온다고 생각할까요? 
모호하다 느껴져요 😬

2022-05-23 00:06 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Line.java
> +    private void validateArgument(String name, String color, int extraFare) {
메서드명에 argument가 없어도 충분히 이해가 잘 될거 같아요..!

2022-05-23 00:06 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Line.java
> +        }
도메인단에서 프로젝트의 요구사항에 대한 유효성 검사를 잘 진행해주셨네요..! 너무 잘 해주셨어요. 

한 단계 더 나아가볼게요. 컨트롤러 단에서 `@Valid` 를 이용하여 유효성 검사를 추가해주면 어떨까요?

배카라가 적용해보고 컨트롤러, 도메인, DB(글자수 제한, null 여부) 세 곳 모두에서 유효성 검사를 해줬을 때 어떤 장점이나 단점이 있는지 댓글로 남겨주세요!

2022-05-23 00:06 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Section.java
> +    public boolean isSameSection(Long stationId1, Long stationId2) {
1, 2 보다 의미있는 변수명이 있을까요?

2022-05-23 00:06 UTC, toneyparky commented on src/test/java/wooteco/subway/domain/AgeGroupTest.java
> +    public void checkChildren() {
테스트를 잘 표현하는 메서드명으로 바꿔주죠!

2022-05-23 00:06 UTC, toneyparky commented on src/test/java/wooteco/subway/domain/AgeGroupTest.java
> +    public void checkFare() {
위의 `checkChildren`도 그렇고 이 테스트도 여러 개의 고정된 값을 테스트하고 있네요. ParameterizedTest 를 활용하여 리팩터링 해볼까요?

2022-05-23 00:06 UTC, toneyparky commented on src/main/java/wooteco/subway/service/PathService.java
> +    private int getExtraFare(Sections sections, List<Long> path) {
해당 메서드는 private 메서드라 클래스 내부에서만 사용되고 쉽게 내부 구현을 확인할 수 있어요! 하지만 메서드를 사용하는 사람이 메서드 이름만 보고 여러 `Line` 중 최대 추가 금액을 가져온다는 사실을 알 수 있을까요?

2022-05-23 00:06 UTC, toneyparky commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +    public void chargeMaxAdditionalFare() {
이 테스트에서 배카라는 여러 개의 노선을 지나며 가장 비싼 추가 요금이 적용되는 경우를 확인하고 싶으셨군요!

하지만 테스트 내부에서는 다른 컨텍스트도 포함되어 있어서 본질을 확인하는 데에 방해가 되어요. 예를들면 나이와 관련된 정책도 함께 테스트한다는 점을 들을 수 있어요.

가장 비싼 추가 요금이 적용된다는 사실을 명확히 확인할 수 있도록 테스트를 수정해볼까요?

2022-05-23 03:50 UTC, seong-wooo commented on docs/README.md
> +  - [x] 아기 (6세 미만) : 무료
뿌듯하네요 💯

2022-05-23 03:58 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/AgeGroup.java
> +        public static final int TEENAGER_DC_RATE = 5;
변수명에 맞게 값과 식을 변경했습니다! 보는 사람이 조금 더 이해하기 쉬울 것 같아요 !

2022-05-23 04:12 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/Fare.java
> +    public int getDiscountValue(AgeGroup ageGroup) {
discountedValue로 이름을 변경하여 할인된 값을 가져온다고 생각하게 끔 만들었습니다.

2022-05-23 04:12 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/Line.java
> +    private void validateArgument(String name, String color, int extraFare) {
validate로 변경하였습니다 !

2022-05-23 07:15 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/Line.java
> +        }
장점 :
데이터가 전달될 때 세 곳에서 검사를 실행해주기 때문에  데이터의 유효성이 더 잘 보장된다.

단점: 
유효성 검사를 여러 곳에 구현해야한다. -> 중복된 로직을 여러 곳에 작성해야한다.
도메인 로직을 컨트롤러가 알게 된다.

2022-05-23 07:29 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/Section.java
> +    public boolean isSameSection(Long stationId1, Long stationId2) {
고민을 해보았는데 순서가 없는 두 개의 stationId를 어떤 이름으로 설정해야할 지 모르겠어서
stationId와 otherStationId로 변경하였습니다. 막 되게 만족스럽지는 않네요

2022-05-23 07:41 UTC, seong-wooo commented on src/test/java/wooteco/subway/domain/AgeGroupTest.java
> +    public void checkFare() {
ParameterziedTest를 사용하도록 변경하였습니다 !

2022-05-23 07:42 UTC, seong-wooo commented on src/test/java/wooteco/subway/domain/AgeGroupTest.java
> +    public void checkChildren() {
전체 연령대를 확인하는 의미가 담긴 이름으로 변경하였습니다 !

2022-05-23 07:49 UTC, seong-wooo commented on src/main/java/wooteco/subway/service/PathService.java
> +    private int getExtraFare(Sections sections, List<Long> path) {
좀 더 명확하게 느껴지도록 이름을 변경하였습니다 !

2022-05-23 08:02 UTC, seong-wooo commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +    public void chargeMaxAdditionalFare() {
가장 비싼추가 요금만을 확인하는 테스트로 변경하였습니다 !

2022-05-24 11:28 UTC, toneyparky commented on build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:4.4.0'
인덴트를 맞춰주죠~

2022-05-24 11:28 UTC, toneyparky commented on docs/README.md
> +  - 50km 초과: 8km 까지 마다 100원 추가
아직 하루의 시간이 더 남았기에 테스트 가독성을 높힐 수 있는 방식을 소개해드릴게요!

현재 배카라가 작성한 테스트는 평평한 테스트에요. 하나의 테스트가 하나의 컨텍스트를 담고 있다는 의미입니다. 이를 `@Nested`라는 어노테이션을 활용하여 입체감있게 표현할 수 있어요. 그러면 테스트가 구조화되고 테스트를 읽는 사람이 보다 쉽게 테스트를 파악할 수 있다는 장점이 있어요.

아래의 글을 읽어보고 `SectionsTest`에 describe - context - it 패턴을 적용해보죠! 적용 후에 어떤 느낌이 드셨는지 댓글로 남겨주세요!

https://johngrib.github.io/wiki/junit5-nested/

2022-05-24 11:28 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/AgeGroup.java
> +        public static final int TEENAGER_DC_RATE = 5;
네, 이런 복잡한 로직은 명확한 이름을 지어줘야 코드를 읽는 사람이 파악하기 쉽습니다~ 수정한 내용 확인했어요!

2022-05-24 11:28 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Fare.java
> +    public int getDiscountValue(AgeGroup ageGroup) {
굳굳~

2022-05-24 11:28 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Line.java
> +        }
도메인 레이어는 프로젝트의 핵심이 되는 친구기에 유효성 검사를 필수적으로 해줘야하죠. 그리고 컨트롤러는 클라이언트마다 다르게 구현될 수 있으니 각 상황에 맞는 유효성 검사를 추가해줄 수 있어요. 그리고 앞단에서 검사를 해주기에 DB나 내부 도메인단까지 들어가지 않아도 되기에 효율적이라는 장점도 있답니다. 

마지막으로 해당 어노테이션에 의해 발생하는 예외는 어떤 형식일까요? 핸들러에서 처리해줘볼까요?

2022-05-24 11:28 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Section.java
> +    public boolean isSameSection(Long stationId1, Long stationId2) {
1과 2보다는 나은 것 같아요. 그냥 upStationId, downStationId도 괜찮다고 생각이 드네요.

2022-05-24 11:28 UTC, toneyparky commented on src/test/java/wooteco/subway/domain/AgeGroupTest.java
> +    public void checkFare() {
확인했어요~! ParameterziedTest가 항상 좋다고 볼 수는 없지만 테스트 관리하기에는 더 쉬운거 같아요.

2022-05-24 11:28 UTC, toneyparky commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +    public void chargeMaxAdditionalFare() {
네, 코드가 많을 수록 테스트를 읽는 사람에게 부담이 되어요. 그렇기에 테스트에서 검증해야하는 핵심 로직을 담는편이 좋습니다!

2022-05-24 11:29 UTC, toneyparky requested changes
안녕하세요 배카라~ 리뷰 반영 잘 해주셨군요! 감사해요. 

리뷰를 통해 정확한 명칭의 중요성을 학습하셨길 바라요. 머지할까 했지만 아직 시간이 조금 있어서 간단한 리뷰 하나 더 드렸으니 반영 부탁드려요.

마지막까지 화이팅~!

2022-05-24 16:28 UTC, seong-wooo commented on build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:4.4.0'
제 로컬에서는 인덴트가 맞네요..

2022-05-24 16:29 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/Line.java
> +        }
처리 완료입니다 😎

2022-05-24 16:31 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/Section.java
> +    public boolean isSameSection(Long stationId1, Long stationId2) {
다시 upStationId, downStationId으로 변경해보았습니다 !

2022-05-25 05:23 UTC, seong-wooo commented on docs/README.md
> +  - 50km 초과: 8km 까지 마다 100원 추가
중복되는 로직을 줄여주고 어떤 테스트를 작성 하였는 지 더 쉽게 알아볼 수 있다는 점에서 좋은 것 같습니다! 
지금부터 사용해보면서 이 방식에 익숙해져야 이 방식의 장점을 더 느낄 것 같아요 !

2022-05-25 12:34 UTC, toneyparky commented on docs/README.md
> +  - 50km 초과: 8km 까지 마다 100원 추가
네, 추후에 비슷한 경우가 발생하면 사용해보세용. 한가지 상황을 가정하고 하위에 어려 베리에이션이 있을 경우에 사용하면 좋습니다!

2022-05-25 12:34 UTC, toneyparky commented on build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:4.4.0'
엇 그런가용 제가 잘못 봤나보네요 😂

2022-05-25 12:34 UTC, toneyparky approved these changes
안녕하세요 배카라~ 

제가 드릴 리뷰는 더 이상 없어요. 이번 미션 잘 구현해주셨습니다! 지하철 미션을 하며 학습한 내용을 바탕으로 다음 미션도 재미있게 개발하시길 바라요! 

고생 많았어요 😁

2022-05-25 12:35 UTC, merged