[Spring 경로 조회 - 2단계] 베루스(정진혁) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #262
Opened 2022-05-22 06:14 UTC by wilgur513

안녕하세요 토니~~ 😄
이전 단계의 피드백 반영과 2단계 미션 구현했습니다 ㅎㅎㅎㅎ
피드백에 대한 답변은 여기에 쓰기에는 너무 많은 피드백을 주셔서... 여기에 쓰지 않았습니다.
이전 PR에 답변 남겨뒀습니다 ㅎㅎ 확인 부탁드립니다~~

#239

2022-05-23 01:12 UTC, toneyparky requested changes
안녕하세요 베루스~! 1단계 미션의 리뷰 잘 반영해주셨어요! 감사합니다. 답변 달아주신 내용도 잘 확인했고 저도 답변을 달았답니다. 

이번 단계에서는 몇가지 요구사항에 대한 내용과 가독성에 대한 내용을 남겼으니 가볍게 확인 부탁드려요! 구현 잘 해주셔서 크게 수정할 부분은 없다는 생각이 드네요. 

오늘도 즐거운 하루 보내세용~~

2022-05-23 01:12 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
>      void searchPath() {
인수 테스트의 변수를 한글로 수정해주신 이후의 코드가 개인적으로 눈에 더 잘 들어오네요! 리뷰 반영을 잘 해주셨어요.
요런 부분은 베루스가 팀에 들어가면 기존의 코딩 컨벤션을 따라야하기에 항상 적용할 수 있는 부분은 아니라고 생각해요. 하지만 신규 프로젝트라거나 기존 프로젝트 리팩터링을 통해서 적용해볼 수 있겠죠? 다만, 함께 협업하는 팀원분들을 대상으로 관련 내용을 잘 설득하고 함께 결정해야해요.

2022-05-23 01:12 UTC, toneyparky commented on src/main/java/wooteco/subway/application/JGraphtSubwayGraph.java
> +public class JGraphtSubwayGraph implements SubwayGraph {
요 부분은 기존의 어댑터라는 명칭도 좋다고 생각해요. 

베루스는 디자인 패턴이란 무엇이고 왜 사용한다고 생각하세요?

2022-05-23 01:12 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/FareCalculator.java
> +    private int extraLineFare(Path path) {
해당 메서드는 private이라 클래스 내부에서만 사용 가능하고 쉽게 세부 구현을 확인할 수 있죠! 하지만 세부 구현을 확인하지 않더라도 여러 라인의 추가 금액 중 `가장 비싼` 금액을 반환한다는 의미를 드러내면 어떨까요?

2022-05-23 01:12 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Passenger.java
> +public enum Passenger {
흥미롭네요! 요구사항을 담을 수 있는 적절한 객체라고 생각해요 💯

2022-05-23 01:12 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Passenger.java
> +    private final BigDecimal discountAmount;
해당 변수는 할인에 대한 내용인가요 공제에 대한 내용인가요? 

> 청소년: 운임에서 350원을 공제한 금액의 20%할인
> 어린이: 운임에서 350원을 공제한 금액의 50%할인

2022-05-23 01:12 UTC, toneyparky commented on src/test/java/wooteco/subway/domain/FareCalculatorTest.java
> +    @DisplayName("추가 요금이 있는 노선의 요금 계산")
> 경로 중 추가요금이 있는 노선을 환승 하여 이용 할 경우 가장 높은 금액의 추가 요금만 적용

위와 같은 경우에 대해서도 테스트할 필요가 있을까요?

2022-05-23 01:12 UTC, toneyparky commented on src/main/resources/schema.sql
>      name varchar(255) not null unique,
사용자가 255자가 넘는 이름으로 역, 노선을 생성하려한다면 어떤 메시지를 확인할 수 있을까요?  

`@Valid` 어노테이션에 대해서 학습해보고 적용해보죠!

2022-05-23 01:12 UTC, toneyparky commented on src/main/java/wooteco/subway/application/PathService.java
> +    public PathResponse searchPath(Long source, Long target, int age) {
age의 값이 -1로 들어온다면 베루스가 만든 지하철 경로 조회 프로그램은 어떤 값을 반환하나요?

2022-05-25 06:32 UTC, verus-j commented on src/main/java/wooteco/subway/domain/Passenger.java
> +    private final BigDecimal discountAmount;
`discountAmount`는 공제금 350원을 의미하고, `inverseOfDiscountRate`는 할인율의 역산을 의미해요.
조금 의미가 애매한 부분이 있는 거 같아서 `deductionAmount`와 `discountRate`로 변수를 변경하고, 할인율 역산을 추가로 계산해서 할인된 요금을 계산하도록 변경했습니다.

2022-05-25 06:36 UTC, wilgur513 commented on src/test/java/wooteco/subway/domain/FareCalculatorTest.java
> +    @DisplayName("추가 요금이 있는 노선의 요금 계산")
노선별 추가 요금이 있는 경우와 없는 경우를 구분하는 것이 의미있을 것 같아요. 노선별 추가 요금이 없는 경우에는 단순 거리에 따른 추가 요금 로직만 점검할 수 있고, 이후 노선별 추가 요금 기능을 이어서 단계적으로 검증할 수 있어서 좋은 것 같아요.

2022-05-25 08:10 UTC, wilgur513 commented on src/main/java/wooteco/subway/application/JGraphtSubwayGraph.java
> +public class JGraphtSubwayGraph implements SubwayGraph {
현재 직면한 문제를 다루는데 디자인 패턴이 도움이 된다고 생각해요. 유사한 문제를 만났을 때 그 문제를 해결하기 위한 패턴을 적용하면서 손쉽게 해결 방안을 찾아볼 수 있다고 생각합니다 ㅎㅎ 그리고 패턴을 통해서 다른 개발자들과 효율적인 의사소통을 할 수 있다고 생각이 들어요. 세세한 구조를 설명할 필요 없이 어댑터 패턴을 적용했다 한마디로 현재의 설계를 대략적으로 설명할 수 있을 것 같아요.

2022-05-25 13:07 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    @DisplayName("지하철 노선 이름은 255자이하여야 한다.")
굳굳 테스트케이스까지 깔끔하네요!

2022-05-25 13:07 UTC, toneyparky commented on src/main/java/wooteco/subway/application/JGraphtSubwayGraph.java
> +public class JGraphtSubwayGraph implements SubwayGraph {
베루스의 생각을 잘 적어주셨네요! 저도 패턴을 이용하여 소통하면 서로 불필요한 설명이 줄어든다는 장점이 있다고 생각해요. 다만 패턴은 절대적인 정답이 없고 상황에 맞춰 사용하면 좋은 정도라는 점을 기억하면 좋겠어요!

2022-05-25 13:07 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Passenger.java
> +    private final BigDecimal discountAmount;
좋네요! 공제라는 용어를 명확히 표현해주셨네요! 할인율의 역산이라는 복잡한 의미의 변수도 바꿔줬구요. 
프로젝트를 개발하며 사용하는 용어는 기획자, 개발자, 디자이너 모두 충분히 소통한 후에 공유하는 단어를 사용하면 좋아요. 그러기 위해서는 용어를 명확히 결정해야 하구요. 리팩터링 잘 해주셨어요 😉

2022-05-25 13:07 UTC, toneyparky commented on src/test/java/wooteco/subway/domain/FareCalculatorTest.java
> +    @DisplayName("추가 요금이 있는 노선의 요금 계산")
적어주신대로 비즈니스 요구사항을 테스트로 명시한다는 측면에서 작성하면 좋다고 생각해요. 코드를 처음 보는 사람도 이런 로직이 있구나를 명확히 파악할 수 있으니까요. 지금은 아니지만 특정 로직이 상위의 로직을 테스트하며 내포되어 테스트 되어진다면 하위 로직을 따로 분리하여 검증해야하는 힌트일 수 있어요.

2022-05-25 13:08 UTC, toneyparky approved these changes
베루스~ 안녕하세요! 토니에요.

지하철 경로 조회 1, 2 단계 미션 잘 마무리해주셨네요. 내일부터 협업 미션인 장바구니 미션이 시작되고 추가적으로 피드백 드릴 부분이 없어서 머지하도록 할게요!
궁금한 사항이나 이야기 나누고 싶은 내용은 DM 언제든 주세요.

고생 많으셨고 하루 마무리 즐겁게 하세요😀

2022-05-25 13:08 UTC, merged