[Spring 경로 조회 - 2단계] 알렉스(이영환) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #270
Opened 2022-05-22 12:07 UTC by yxxnghwan

안녕하세요 던! 2단계로 찾아뵙게 되었네요!

저번 리뷰에서 주신 피드백 반영 및 2단계 구현 해보았습니다!

2단계 관련하여 요구사항이 헷갈리는 것이 있어서 질문 드릴까 하는데요,
나이에 따른 할인이 적용될 때 `기본 운임 요금(1250 + 노선 추가 요금)`에 대해서 할인을 넣고 거리에 따른 추가 요금은 온전히 계산해야 하는 지,
아니면 거리에 따른 추가 요금까지 전부 계산한 후에 할인을 적용시켜야 하는 지 헷갈리더라구요.

구현은 전자로 했고, 리드미에 기재하였습니다! 만약에 제가 틀리게 구현 했다면 지적 부탁드려요!

2022-05-22 12:21 UTC, yxxnghwan commented on src/main/java/wooteco/subway/domain/Section.java
>      }
생성자와 완전히 같은 정적 팩토리 메서드를 쓰고 있었네요,,😅
해당 클래스는 id 없이 생성될 수 있는 클래스여서 생성자를 쓰면서 id에 null을 매 번 넣어주기 보단 정적 팩토리 메서드를 사용해서 id없이 인스턴스를 생성할 수 있는 수단을 제공하는 것으로 변경했습니다.

2022-05-22 12:21 UTC, yxxnghwan commented on src/main/java/wooteco/subway/domain/LineSections.java
>      }
처음 개발할 때 일단 자바에서 제공하는 표준 예외를 사용하다가 추후에 커스텀 예외를 정의하고 컨트롤러 어드바이스에선 커스텀 예외를 처리하도록 해서 해당 어플리케이션에서 생각할 수 있는 예외를 처리할 수 있게 구조를 변경했는데요,

변경 중에 빼먹고 표준 예외를 덜 걷어낸 것 같아요. 찾아서 수정 했습니다!

자바의 표준 예외는 개발자가 개발을 잘못 해서 발생할 수도 있기 때문에 에러 메시지로 어디서 어떤 부분 때문에 예외가 발생했는 지 알 수는 있지만, 
발생한 예외를 캐치해서 컨트롤러 어드바이스로 전달해서 예외 핸들러 메소드로 전달할 때 응답으로 4XX이나 5XX을 정의하기 애매한 부분이 있는 것 같아요.
커스텀 예외를 사용한다면 좀 더 구체적인 상황에 맞는 상태 메시지와 상태코드를 응답할 수 있을 것 같습니다!

2022-05-22 12:21 UTC, yxxnghwan commented on src/main/java/wooteco/subway/service/StationService.java
>                  .collect(Collectors.toList());
매번 id마다 쿼리를 실행해서 Station을 가져오지 않고 전체 Station을 조회한 다음에 필터를 사용해서 존재하는 id를 골라내는 방식으로 변경했는데요, 이 때 사용되는 `List<Long> stationIds`는 제가 원하는 순서대로 맞춰져있는 데 filter로 걸러낸 `List<Station>`의 경우엔 순서가 보장되지 않는 문제가 발생했었어요.

부득이하게 Map컬렉션에 담은 다음에 `stationIds`에서 다시 스트림을 사용해 순서를 유지하며 Map에서 id가 맞는 걸 꺼내오는 방식으로 변경했습니다!

2022-05-23 02:54 UTC, gch01410 requested changes
안녕하세요 알렉스!
이번에도 깔끔하게 구현해주셨네요! 👍 
추가로 개선해보면 좋을것 같은 부분이 보여서 피드백 드렸습니다!
확인 부탁드릴게요!~

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/service/StationService.java
>                  .collect(Collectors.toList());
> 매번 id마다 쿼리를 실행해서 Station을 가져오지 않고 전체 Station을 조회한 다음에 필터를 사용해서 존재하는 id를 골라내는 방식으로 변경했는데요, 이 때 사용되는 List<Long> stationIds는 제가 원하는 순서대로 맞춰져있는 데 filter로 걸러낸 List<Station>의 경우엔 순서가 보장되지 않는 문제가 발생했었어요.

👍  따로 설정을 안한다면 findAll메서드로 가져온 Station은 pk 오름차순으로 정렬되어서 조회됩니다!
그리고 전체 Station을 조회해서 필터링하지 않고 stationIds에 해당하는 Station만 조회해볼 수 있을까요?
where 조건에서 in 키워드를 사용하면 됩니다!

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/DiscountPolicy.java
> +    OTHER(age -> !isChildrenAge(age) && !isTeenagerAge(age), money -> money);
할인정책을 enum으로 관리하셨군요! 👍 
다만 지금 구조로는 할인정책이 동시에 여러개 적용되어야하는 케이스는 대응하기 어려워보이네요.
미션 요구사항에서는 나이와 관련한 할인만 있어서 이대로도 충분하지만, 할인정책이 여러개 중복 적용될 수 있도록 개선해볼 수 있을까요? `할인정책은 중복으로 적용가능하다`라는 요구사항으로 확장될 여지가 충분히 있어보이네요. 여러개 중복으로 적용된다면 할인정책 적용 순서도 고려해야할꺼에요. 여러 방법이 있겠지만 전략패턴을 이용할 수도 있겠어요.

이건 선택사항으로 남겨둘게요!ㅎ 반드시 반영안하셔도 됩니다.

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/DiscountPolicy.java
> +    }
상수화해서 어린이 나이 기준이라고 더 명확하게 의미를 드러낼 수 있겠네요!

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/dao/JdbcLineDao.java
>      }
Line이 없는 경우에는 Optional을 반환하도록 하면 어떨까요?
데이터가 없어도 예외를 발생시키지 않고 로직을 계속 수행해야할 경우도 있을 것 같은데, dao에서 예외를 발생시키면 dao를 사용하는 곳에서 try-catch로 예외처리를 해서 처리해야하는 번거러움이 생길 것 같아요.
dao에서 Optional로 반환한다면 데이터가 존재하지않을 경우의 처리를 dao를 호출하는곳으로 위임할 수 있어보여요.

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/dao/JdbcSectionDao.java
>      }
쿼리에 `limit 1` 조건을 걸어서 조회된 데이터가 있는지를 확인하면 테이블 전체 데이터를 확인하지않고서도 데이터가 존재하는지를 확인할 수도 있습니다! (찾는 데이터가 없다면 테이블 전체를 확인하겠지만요,,)

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/service/SectionService.java
>      }
리스트의 인덱스를 통해 가져올때보다 훨씬 의미가 더 명확해졌네요! 👍

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/service/PathService.java
> +        final Fare fare = Fare.of(shortestPath.getTotalDistance(), maxExtraFare, discountPolicy);
이 로직은 요금 계산하는 역할로만 쓰이고 있네요! 메서드로 따로 분리해주면 좋을 것 같아요!

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/DiscountPolicy.java
> +    }
DiscountPolicy의 할인로직에 대해서도 테스트 코드를 작성하면 좋을 것 같아요!

2022-05-23 02:54 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/DiscountPolicy.java
> +public enum DiscountPolicy {
> 나이에 따른 할인이 적용될 때 기본 운임 요금(1250 + 노선 추가 요금)에 대해서 할인을 넣고 거리에 따른 추가 요금은 온전히 계산해야 하는 지,
> 아니면 거리에 따른 추가 요금까지 전부 계산한 후에 할인을 적용시켜야 하는 지 헷갈리더라구요.

듣고보니 저도 햇갈리네요 👀  이번 미션에서 중요한 부분은 아니라서 지금 구현하신대로 유지하셔도 될 것 같습니다!

2022-05-23 06:28 UTC, yxxnghwan commented on src/main/java/wooteco/subway/dao/JdbcSectionDao.java
>      }
해당 쿼리는 있는 지 아닌 지만 확인하면 되니까 limit 조건을 거는 게 전체 데이터를 보지 않을 수 있으니 조금 더 성능이 좋겠네요! 감사합니다!

2022-05-23 06:30 UTC, yxxnghwan commented on src/main/java/wooteco/subway/dao/JdbcLineDao.java
>      }
데이터를 단건 조회하는 메서드에선 Optional을 반환하도록 변경했습니다! dao를 사용하는 곳에선 찾는 데이터가 존재할 경우와 없을 경우에 따라 Optional의 기능들을 통해 유연하게 처리할 수 있을 것 같아요! 현재 상태로는 없을 경우에 예외를 발생시키는 기능만 있으면 되기 때문에 사용하는 곳에선 `orElseThrow()`메서드를 사용했어요!

2022-05-23 06:31 UTC, yxxnghwan commented on src/main/java/wooteco/subway/domain/DiscountPolicy.java
> +    }
각각 매직넘버를 의미를 가지는 상수로 뽑았습니다!

2022-05-23 06:36 UTC, yxxnghwan commented on src/main/java/wooteco/subway/domain/DiscountPolicy.java
> +    OTHER(age -> !isChildrenAge(age) && !isTeenagerAge(age), money -> money);
여러 할인 정책이 적용되게 하기 위해 DiscountPolicy를 인터페이스를 추상화하고 순서에 맞게 정렬된 `List<DiscountPolicy>`를 Fare 에서 파라미터로 받아서 순서대로 할인을 적용시키도록 바꿨습니다. 만약 할인 정책이 추가되고 동시에 여러 할인을 적용시켜야한다면, 새로운 할인 정책 구현체를 작성하고 파라미터에 포함시키면 될 것 같아요!

2022-05-23 07:11 UTC, yxxnghwan commented
안녕하세요 던! 피드백 반영해서 다시 제출합니다!

수정해야할 부분이나 고민해야할 부분 있다면 엄격하게! 지적 부탁드려요!

2022-05-23 13:13 UTC, gch01410 requested changes
안녕하세요 알렉스!
피드백 잘 적용해주셨어요! 💯 
할인정책 추가하는것과 관련한 피드백 하나 남겼습니다!
아직 미션기간이 조금 남았으니 더 고민해봐요!
궁금하신것 있으시면 편하게 DM주세요~

2022-05-23 13:13 UTC, ghost commented on src/main/java/wooteco/subway/service/PathService.java
> +    }
할인 중복적용 관련 피드백을 선택사항으로 남겨둔다고했던 이유는 알렉스 생각처럼 지금 미션에서는 오버엔지니어링이 될 수도 있고 빈 주입에 대해서 조금 더 이해가 있어야했습니다. 
그치만 이번 미션에서 가장 중요한건 다른것들보다 `새로운 요구사항이 추가될때마다 어떻게 처리하는게 좋을지에 대해 고민` 하는것이라고 생각해요. 그래서 아래 내용을 알아두면 앞으로 도움될 것 같아서 조금 더 말씀드릴게요!

```java
@Service
public class PathService {
     ...
    private List<DiscountPolicy> discountPolicies;

    public PathService( ... , List<DiscountPolicy> discountPolicies) {
        this.discountPolicies = discountPolicies;
    }
}
```
위 처럼 DiscountPolicy 인터페이스 타입의 빈을 주입받는다고 선언하면 discountPolicies에는 어떤 객체들이 주입될까요?

그리고 아래처럼 인터페이스를 선언해서 요금을 계산하는 로직을 살짝 변경하면 할인정책이 추가되더라도 DiscountPolicy 인터페이스를 구현하는 새로운 클래스만 추가하면 될 것 같아요. 할인적용하는 로직은 수정하지않고요!

```java
public interface DiscountPolicy {
    boolean accept(DiscountCondition discountCondition);
    int getPriority();
    int applyDiscount(final int money);
}
```

로또미션에서 사용했던 전략패턴과 동일합니다. 다만, 하나가 아니라 여러 전략을 동시에 사용할 수도 있어요!
이번 미션기간이 아직 남았으니 조금 더 고민해봐요! ㅎㅎ
(사실 미션기간이 얼마 안남은지 알아서 예시 코드를 다 작성했다가 생각보다 기간이 꽤 남아서 일부 코드는 지웠습니다 ㅎㅎ;)

2022-05-23 13:13 UTC, gch01410 commented on src/main/java/wooteco/subway/dao/JdbcStationDao.java
>      }
in 쿼리 사용 👍

2022-05-24 10:46 UTC, yxxnghwan commented on src/main/java/wooteco/subway/service/PathService.java
> +    }
인터페이스를 구현하는 구현체가 여러 개 빈으로 등록되어 있을 시 List의 형태로 주입받을 수 있는 줄 몰랐네요! 알려주셔서 감사합니다!
`@Order` 어노테이션을 이용해서 리스트로 주입받을 때의 순서를 정해줄 수 있었어요. 만약 할인정책이 추가 된다면 새로운 할인정책 클래스를 구현만 하고 빈으로 등록하면서 순서만 조정해주면 될 것 같네요!

주신 코드에서 힌트를 얻어서 DiscountPolicy를 상속 받는 AgeDiscountPolicy로 한 단계 더 추상화해서 어떤 기준으로 할인을 정하는 지 군집시켜서 사용할 상수를 모으고 각각 ChildrenDiscountPoilicy와 TeenagerDiscountPolicy를 구현해서 빈으로 등록했습니다!

2022-05-24 10:49 UTC, yxxnghwan commented
안녕하세요 던! 이번에는 

- 피드백 반영한 내용
- 도메인 이해를 잘 못하고 있어서 도메인 규칙을 수정한 내용 
- 다익스트라 라이브러리를 전략패턴을 사용해서 Path 객체에서 의존을 제거한 것
- 다익스트라에서 제공되는 `DefaultWeightEdge`를 상속받아서 제가 쓰기 좋은 클래스를 정의하여 구조 변경한 것

정도가 있네요. 다시 따끔한 피드백 부탁드립니다!😁

2022-05-25 16:47 UTC, gch01410 approved these changes
안녕하세요 알렉스!
피드백 잘 반영해주셨네요! 💯 
잘 구현해주셔서 피드백 더 드릴것이 없네요.
수고하셨습니다!

2022-05-25 16:47 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/discount/age/ChildrenDiscountPolicy.java
> +@Order(1)
`@Order` 로 할인순서를 적용하셨군요! 👍 
이 방법도 좋네요!

2022-05-25 16:47 UTC, merged