[Spring 경로 조회 - 2단계] 아리(양유림) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #274
Opened 2022-05-22 15:05 UTC by ulimy

안녕하세요 던! 아리입니다👋
요금정책기능 추가와 함께 돌아왔습니다!
부족하지만 이번 리뷰도 잘 부탁드립니다. 감사합니다🙇🏻‍♀️

2022-05-23 03:35 UTC, gch01410 requested changes
안녕하세요 아리!
빠르게 2단계 구현해주셨네요! 👍 
코멘트 남겼으니 확인 부탁드릴게요~

2022-05-23 03:35 UTC, gch01410 commented on src/main/java/wooteco/subway/dto/response/PathResponse.java
> +    }
사용하지 않는 생성자는 삭제해주세요!

2022-05-23 03:35 UTC, gch01410 commented on src/main/java/wooteco/subway/dto/response/LineResponse.java
>      }
사용하지 않는 생성자는 삭제해주세요~

2022-05-23 03:35 UTC, gch01410 commented on src/main/java/wooteco/subway/util/FareCalculator.java
> +    }
영유아, 청소년, 어린이를 if문으로 확인하고 요금계산하고 있네요!
if문을 없애볼 수 있을까요??
enum 혹은 인터페이스를 사용해볼 수 있을 것 같아요!

2022-05-23 03:35 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/line/LineSeries.java
> +    }
이름이 중복되는지 확인하기 위해 `매번 테이블 전체 데이터를 조회해서 확인하는 방법` 은 `특정 name으로 조회해서 데이터가 존재하는지 확인하는 방법` 에 비해서 어떤 문제점이 있을지 고민해볼 수 있을까요?

2022-05-23 03:35 UTC, gch01410 commented on src/main/java/wooteco/subway/util/FareCalculator.java
> +package wooteco.subway.util;
FareCalculator는 상태가 없고 static 메서드만 가지고 있어서 util이라고 생각할 수는 있지만 util과는 살짝 성격이 다른것 같아요!
보통 util은 비즈니스 로직과는 관련없이 단순 작업만을 의미해요! FareCalculator는 비즈니스 로직(비즈니스 요구사항) 자체를 담고 있지않을까요?

2022-05-24 11:43 UTC, ulimy commented on src/main/java/wooteco/subway/dto/response/PathResponse.java
> +    }
사실 이 생성자는 테스트의 SimpleRestAssured.toObject()에서 response를 알맞는 객체로 매핑해줄 때 이용되고 있습니다. 테스트만을 위한 코드라는 사실 인지하고 있지만 해당 방법을 사용하지 않고 어떻게 응답객체를 검증하는 방법을 찾지 못했습니다ㅠㅠㅠㅠ 혹시 제가 모르는 방법이 있을까요...?ㅠㅠㅠ

2022-05-24 11:44 UTC, ulimy commented on src/main/java/wooteco/subway/dto/response/LineResponse.java
>      }
https://github.com/woowacourse/atdd-subway-path/pull/274#discussion_r880400341 이 부분과 같은 내용입니다ㅠ!

2022-05-24 11:44 UTC, ulimy commented on src/main/java/wooteco/subway/util/FareCalculator.java
> +    }
클래스였던 Age를 enum으로 선언하여 할인 금액을 반환해주는 방식으로 수정했습니다!

2022-05-24 11:51 UTC, ulimy commented on src/main/java/wooteco/subway/domain/line/LineSeries.java
> +    }
전자의 방법이 현재, 후자의 방법이 제가 지하철 노선도 미션에서 이용했던 방법인 것 같아요. 

- 매번 테이블 전체 데이터를 조회해서 확인한다면 이름 중복 검사로직이 오직 LineSeries에만 존재하게 됩니다. 하지만 매번 전체 데이터를 조회하고, 해당 요청이 끝나면 테이블을 갱신하는 비용이 필요합니다. 
- 특정 name으로 조회해서 데이터가 존재하는지 확인한다면 전자의 방법에서 필요했던 비용이 없어지지만 서비스에서 Repository에게 존재여부를 묻고, 해당 결과를 도메인에게 보내줌으로써 중복확인이라는 책임이 서비스와 도메인에 분리된다고 생각합니다.

이렇듯 두가지 방법 모두 장단점이 존재하기에 어느쪽이 맞다, 틀리다 라고 결정짓기가 힘들었습니다. 다만, 이번 코드의 전체적인 구조를 살펴보면 비용이 조금 발생하더라도 도메인의 책임이 되도록 설계되어있다고 생각합니다. 따라서 해당 방법을 선택했습니다!

2022-05-24 11:59 UTC, ulimy commented on src/main/java/wooteco/subway/util/FareCalculator.java
> +package wooteco.subway.util;
던이 예상하신바와같이 상태가 없고 static 메서드만 존재하기 때문에 당연히 util 클래스라고 생각했던 것 같아요. 하지만 다시 생각해보니 제가 util 클래스를 구분하는 기준을 잘못 가지고있었네요! 요구사항에 맞춰 요금을 계산하는건 비즈니스 로직이네요..ㅎㅎ 수정했습니다!

2022-05-25 17:10 UTC, gch01410 approved these changes
안녕하세요 아리!
피드백 잘 반영해주셨습니다! 👍 
간단한 코멘트 남겼으니 확인 부탁드릴게요~
이번 미션은 여기서 머지하겠습니다.
수고 많으셨습니다!

2022-05-25 17:10 UTC, ghost commented on src/main/java/wooteco/subway/domain/line/LineSeries.java
> +    }
> 해당 결과를 도메인에게 보내줌으로써 중복확인이라는 책임이 서비스와 도메인에 분리된다고 생각합니다.

도메인에게 보내준다는게 어떤 의미인지 잘 이해가 안되네요 😢 

실제 서비스라면 where 조건이 없이 테이블 전체 데이터를 조회하는 행위는 아주 위험합니다. 
테이블의 데이터 수가 많다면 조회쿼리가 오래걸려서 커넥션을 오래동안 점유하고 있게되어서 다른 쿼리에 영향을 줄 수 있고, 데이터를 조회해서 메모리에 가져와서도 데이터 수가 많아서 메모리 부족으로 서버가 죽을 수 있거든요.
우테코 미션처럼 실제 서비스 안하는 프로그램에서만 사용가능한 방법이에요.
이번 미션에서는 지금처럼 적용하셔도 괜찮지만 앞으로 고민해주시면 좋을 것 같아요!

2022-05-25 17:10 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/property/Age.java
> +    ADULT(19, 200, (fare) -> 0);
Age 이넘이 할인정책도 갖고 있는다면 property라고 보기 어려울 것 같네요..ㅎ
AgeDiscountPolicy 정도로 이름변경하는건 어떨까요~?

2022-05-25 17:10 UTC, gch01410 commented on src/main/java/wooteco/subway/dto/response/PathResponse.java
> +    }
<img width="1217" alt="스크린샷 2022-05-10 오후 6 32 37" src="https://user-images.githubusercontent.com/26810182/170320298-b63859b7-ffbb-4ceb-b171-728b9b1691c3.png">

테스트 코드를 빌드할 때 어떤 빌드 도구를 사용하는지에 따라 살짝 다릅니다.
이미지처럼 gradle 로 빌드하도록 변경하면 됩니다.

gradle로 변경하면 왜 생성자가 없어도 작동하는지는 아리가 알아볼 수 있을까요?
제가 이전 미션에서 이브 크루한테 설명드렸어서 이브한테 물어보는것도 방법이겠네요 ㅎㅎ;

2022-05-25 17:10 UTC, merged

2022-05-26 06:58 UTC, ulimy commented on src/main/java/wooteco/subway/dto/response/PathResponse.java
> +    }
이브의 도움으로 해결해보았습니다! 내용은 다음과 같습니다.
org.springframework.boot:spring-boot-starter-web 라는 의존성을 추가하면 jackson 라이브러리가 함께 추가됩니다.
이때 jackson 라이브러리의 버전이 2.x.x 이상이라면 기본생성자 없이 값을 바인딩하는 ParameterNamesModule이 등록되어 있기 때문에 기본생성자가 없어도 됩니다. 다만 이는 gradle로 빌드해야만 등록됩니다. 따라서 Run test using을 gradle로 변경해주니 정상적으로 작동함을 확인했습니다. 😃

2022-05-26 07:00 UTC, ulimy commented on src/main/java/wooteco/subway/domain/line/LineSeries.java
> +    }
데이터 수에 따른 메모리 부족 문제는 생각해보지 못했네요ㅜㅜ 더 고민해보겠습니다!

2022-05-26 07:01 UTC, ulimy commented on src/main/java/wooteco/subway/domain/property/Age.java
> +    ADULT(19, 200, (fare) -> 0);
헉 너무 좋은 생각입니다...!