[Spring 경로 조회 - 2단계] 썬(윤선용) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #281
Opened 2022-05-23 05:41 UTC by syoun602

안녕하세요 닉! 2단계 끝내고 PR 보냅니다. 😎
지난 1단계에서 받은 질문에 대한 답변은 코멘트로 남기겠습니다.

고칠 부분이 있다면 모두 지적해주세요!!! 
빠르게 공부해보고 반영하겠습니다! 잘 부탁드립니다  🙏

2022-05-23 06:05 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/PathController.java
>      }
Controller에서 도메인 객체를 알게 된다면 어떤 문제가 있을까요?

제가 생각하는 단점은 다음과 같습니다!

Domain이 Controller 단까지 넘어올 경우 Controller에서 Domain 의존성이 높아질 수 있다.
또한, 요청/응답에 대한 처리만 해야 하는 Controller에서 DTO로의 변환하는 로직을 지니게 된다.
여러 도메인을 조합해서 반환해야 하는 경우, 각각의 서비스에서 여러 도메인을 받아와야 한다.
사실 지금까지는 Service에서 도메인을 반환해야 한다고 생각했는데요. 이유는 다음과 같습니다.
Controller에서 DTO로 변환할 경우, Controller가 View와 통신하는 목적에 맞는 책임을 부여받을 수 있습니다. 만약, 여러 종류의 Controller가 존재한다고 가정했을 때, 같은 비즈니스 로직을 불러와도 Service에서 동일한 Domain을 반환해주기 때문에 Controller에서 목적에 부합하는 DTO로 변환해줄 수 있다는 장점이 있습니다.

만약, Service에서 DTO로 변환한다면 핵심 로직만을 포함해야 하는 Service Layer가 여러 DTO로의 변환에 의해 자칫 무거워질 수 있습니다. 또한, Service가 또 다른 Service를 내포할 경우가 생긴다면 여러 개의 Controller에서 Service의 메서드를 호출할 경우, Domain을 반환하지 않았기 때문에 공통적으로 사용할 수 없게 됩니다. Domain의 데이터만 가진 DTO를 반환할 수도 있지만, 그렇게 된다면 또 다른 DTO로 변환해야 하고 이는 결국 Domain 그 자체를 반환한 것과 별반 차이가 없게 됩니다.

다만, 미션을 진행하며 최근에는 여러 도메인을 가공해야할 일이 생각보다 많아져 서비스에서 dto를 반환해주는 것이 편하다는 것을 느꼈습니다. 특히 Path의 경우 station, line, section이 모두 사용되어 말씀해주신 것처럼 서비스에서 dto를 반환하도록 변경했습니다!

2022-05-23 06:09 UTC, syoun602 commented on src/main/java/wooteco/subway/domain/Path.java
기존에는 `Path`에서 `Fare`를 가지고 있도록 설계했었는데, 2단계를 구현하다보니 `Fare` 자체를 가지고 있기보다는 거리에 비례한 금액을 반환하는 단순한 작업만 필요하다고 생각되어 정적 유틸리티 클래스가 로 변경했습니다.

2022-05-24 14:40 UTC, wbluke requested changes
2단계 구현 잘 해주셨네요 👍 
몇 가지 고민해 볼 포인트 남겼으니 확인 부탁드려요 🙂

2022-05-24 14:40 UTC, wbluke commented on src/main/java/wooteco/subway/ui/PathController.java
> +        );
Request에 필드가 많아질수록 메서드 파라미터도 같이 늘어나야 할 것 같은데요.
Service 레이어 쪽에 DTO가 있고 Request 끼리 변환해서 넘겨주는 방식은 어떨까요?

```java
service.findShortestPath(request.toServiceRequest());
```

2022-05-24 14:40 UTC, wbluke commented on src/main/java/wooteco/subway/ui/PathController.java
>      }
네 맞아요. 말씀해주신 내용에 더해 더 중요한 문제가 있는데요.
Service 레이어의 역할 중 하나는 **단위 기능의 트랜잭션 보장**인데, 도메인이 web 계층에 노출될 경우 이미 처리가 완료된 상태인데도 도메인 로직이 노출됨에 따라 의도하지 않은 응답이 내려갈 수 있습니다.
사용하는 쪽에서 어떻게 사용하는지에 따라 내부 동작 의도와 다르게 판단될 수 있는 여지가 생기는 것이죠 ㅎㅎ

2022-05-24 14:40 UTC, wbluke commented on src/main/java/wooteco/subway/service/PathService.java
> +    public PathResponse createPath(final long sourceId, final long targetId, final int age) {
트랜잭션 잘 설정해 주셨네요 ㅎㅎ
저는 조회전용 트랜잭션의 누락을 방지하기 위해 클래스 레벨에 readOnly 트랜잭션을 걸고,
CUD 작업에 메서드 레벨 트랜잭션을 다시 걸고 있어요 :)

2022-05-24 14:40 UTC, wbluke commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +    void createPath_throwsExceptionOnInvalidRequest(final Long source,
validation test 잘 추가해주셨네요 ㅎㅎ
사실 제가 의도한건 인수테스트보다는 mockMvc를 활용한 Controller 단위테스트였는데요.
인수테스트는 애플리케이션을 블랙박스 처리해놓고, 사용자 행위에 대한 시나리오를 가지고 테스팅을 하는거라서 각 요청에 대한 validation 테스트는 다른 곳에서 이루어지는게 더 맞을 것 같아요.
해당 테스트 내용을 Controller 단위테스트로 다시 작성해보면 어떨까요? :)

2022-05-24 14:40 UTC, wbluke commented on src/main/java/wooteco/subway/domain/strategy/DijkstraStrategy.java
>                  Optional.ofNullable(dijkstraShortestPath.getPath(source, target));
결론적으로 path를 만들기 위함이니 메서드로 추상화하면 어떨까요? :)

2022-05-24 14:40 UTC, wbluke commented on src/main/java/wooteco/subway/domain/AgeDiscountPolicy.java
> +    }
매직넘버!

2022-05-24 14:40 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Path.java
음 네네. 사실 알고 있으면 좋은게, **자바에서 static은 기본적으로 안티패턴**입니다.
상태를 가지지 않아 OOP적인 설계를 방해하니까요.
아니면 의도하신대로 계산만 하길 바란다면 이름을 조금 더 수정하고, 정적 클래스 대신 Bean instance로 만들어서 사용하는 것도 방법일 것 같아요 :)

2022-05-24 14:40 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Line.java
> +        return extraFare == line.extraFare && Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
식별자(id) 필드의 의미를 생각해본다면 eq & hc를 어떻게 바꾸면 좋을까요? :)

2022-05-25 02:09 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/PathController.java
> +        );
해당 방식으로 수정했습니다! 받아온 요청을 그대로 서비스로 넘겨줘도 됐는데, 굳이 한번 꺼내서 주고 있었네요.

적용 과정에서 질문이 하나 있습니다! 그냥 웹으로부터 받아온 request를 또 한번 service dto로 변환해주어야 하는 이유가 있을까요?

2022-05-25 02:22 UTC, syoun602 commented on src/main/java/wooteco/subway/service/PathService.java
> +    public PathResponse createPath(final long sourceId, final long targetId, final int age) {
와 해당 방식을 이용하면 조회전용 트랜잭션을 놓치지 않고 넣어줄 수 있겠네요! 추후에도 미션 및 프로젝트에서 사용하도록 하겠습니다.

2022-05-25 04:27 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/PathController.java
> +        );
`Controller`와 `Service`의 의존 관계를 끊기 위함일까요?

2022-05-25 05:52 UTC, syoun602 commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +    void createPath_throwsExceptionOnInvalidRequest(final Long source,
비슷한 내용의 검증과 같은 결과들은 `Controller` 단위 테스트로 옮겨봤습니다! 인수 테스트와 컨트롤러 테스트에 대한 경계가 그동안 애매했었는데, 최근에 강의를 통해서 조금은 이해하게 되었습니다!

2022-05-25 05:57 UTC, syoun602 commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +    void createPath_throwsExceptionOnInvalidRequest(final Long source,
다만 아직도 불분명한 점이 있어서 질문 남깁니다. 제가 생각한 두 테스트의 차이점은 다음과 같습니다.
인수 테스트
- 블랙박스 처리로 사용자 행위에 대한 시나리오로 테스트한다.
- 여러가지 요청과 응답이 있을 수 있다.

단위 테스트
- 컨트롤러 한 단위에 대한 테스트를 진행한다. 
- 하나의 요청에 대한 테스트를 진행한다.

다만 한가지 불분명한 점이 있습니다. 하나의 요청에 대한 테스트는 시나리오가 될 수도 있으므로 인수테스트 및 컨트롤러 테스트 둘 다에 해당하는데, 그렇다면 이러한 단순한 테스트는 인수 테스트에 두어야 할까요 아니면 단위 테스트에 두어야 할까요? (ex. 노선을 등록한다) 또한, `사용자가 잘못된 요청으로 입력할 경우 예외를 발생한다` 도 하나의 시나리오가 될 수 있는게 아닌가요?!

2022-05-25 06:11 UTC, syoun602 commented on src/main/java/wooteco/subway/domain/strategy/DijkstraStrategy.java
>                  Optional.ofNullable(dijkstraShortestPath.getPath(source, target));
넵 경로를 생성한다는 의미의 메서드로 추출해봤습니다!

2022-05-25 06:29 UTC, syoun602 commented on src/main/java/wooteco/subway/domain/AgeDiscountPolicy.java
> +    }
앗 주의깊게 보지 않았네요😅 제거했습니다! 다만, 나이는 그대로 두는게 더 직관적인 것 같아서 상수로 따로 처리하지 않았습니다!

2022-05-25 08:12 UTC, syoun602 commented on src/main/java/wooteco/subway/domain/Line.java
> +        return extraFare == line.extraFare && Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
저도 domain과 entity가 합쳐진 객체를 사용하고 있어서 eq & hc에서 id를 빼도 되나를 고민했었습니다. 다만 식별자로 생각하고 domain 또는 VO로 본다면 id를 빼는게 맞다고 생각되서 제거했습니다!

한가지 궁금증이 있는데, eq & hc에서 모든 필드를 비교하지 않아도 될까요? 아니면 id만 특별하게 식별자이므로 비교를 안해도 되는 대상인건가요?

2022-05-25 08:13 UTC, syoun602 commented
안녕하세요 닉! 리뷰 반영해서 다시 돌아왔습니다!
몇 가지 질문은 위 코멘트에 남겨두었습니다!!!

더 고쳐야할 부분이 있다면 알려주세요! 빠르게 반영하겠습니다 😁

2022-05-26 04:50 UTC, syoun602 commented on src/main/java/wooteco/subway/domain/Path.java
넵 안티패턴임을 인지하고 정적 클래스에서 상태를 가질 수 있는 일반적인 VO로 변경해봤습니다!!!

2022-05-26 12:41 UTC, wbluke approved these changes
리팩토링 하면서 든 고민에 대해 잘 정리해 주셔서 인상적이네요 👍 
답글 남겼으니 확인해주시고, 경로 미션 고생 많으셨어요-! 🙂

2022-05-26 12:41 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Line.java
> +        return extraFare == line.extraFare && Objects.equals(name, line.name) && Objects.equals(color, line.color);
> 저도 domain과 entity가 합쳐진 객체를 사용하고 있어서 eq & hc에서 id를 빼도 되나를 고민했었습니다. 다만 식별자로 생각하고 domain 또는 VO로 본다면 id를 빼는게 맞다고 생각되서 제거했습니다!
> 
> 한가지 궁금증이 있는데, eq & hc에서 모든 필드를 비교하지 않아도 될까요? 아니면 id만 특별하게 식별자이므로 비교를 안해도 되는 대상인건가요?

오, 아니에요. 제가 의도한건 id만 남기는 것이었어요 ㅎㅎ
인스턴스의 동등성을 보장하는 식별자를 두는 순간 모든 필드를 대표하는 값이기 때문에, 식별자가 같으면 같은 인스턴스로 보겠다는 의미라고 생각해요 :)
하지만 말씀하신대로 domain, entity를 구분한다면 각각이 다를 수 있을 것 같네요! 👍

2022-05-26 12:41 UTC, wbluke commented on src/test/java/wooteco/subway/controller/PathControllerTest.java
> +class PathControllerTest {
> 다만 아직도 불분명한 점이 있어서 질문 남깁니다. 제가 생각한 두 테스트의 차이점은 다음과 같습니다.
인수 테스트
> 
> - 블랙박스 처리로 사용자 행위에 대한 시나리오로 테스트한다.
> - 여러가지 요청과 응답이 있을 수 있다.
> 
> 단위 테스트
> 
> - 컨트롤러 한 단위에 대한 테스트를 진행한다.
> - 하나의 요청에 대한 테스트를 진행한다.
> 
> 하나의 요청에 대한 테스트는 시나리오가 될 수도 있으므로 인수테스트 및 컨트롤러 테스트 둘 다에 해당하는데, 그렇다면 이러한 단순한 테스트는 인수 테스트에 두어야 할까요 아니면 단위 테스트에 두어야 할까요? (ex. 노선을 등록한다) 또한, 사용자가 잘못된 요청으로 입력할 경우 예외를 발생한다 도 하나의 시나리오가 될 수 있는게 아닌가요?!
> 
> 시나리오 vs. 단위라는 것은 이해가 가는데, 시나리오=단위일 경우가 조금 모호하게 느껴집니다.😢
> 
> 추가) 컨트롤러에 단위 테스트도 진행하고 인수테스트도 진행해서 두 가지 경우를 모두 테스트해야 하나요? 기존에 서비스까지 단위 테스트를 모두 진행했다면, 인수테스트를 할때 컨트롤러가 테스트되므로 조금 중복되는게 아닌가? 라는 생각을 하게 되었습니다.
> 
> 다만, 만약 top-down방식의 테스트를 진행했다면, 인수테스트가 가지는 의미가 있을 것 같은데 제가 bottom-up 방식으로 tdd를 진행해서 모호하게 느끼는 것일까요?

오 좋은 질문이에요 👍 
저도 동의하고, 말씀하신대로 회색 지대인 부분도 있다고 보여집니다.

사실 둘 다 테스트하는 것은, (하면 좋겠지만) 테스트도 비용이기 때문에 잘 생각해야 할 것 같은데요.
어디에서 validation 테스트를 할지는 도메인 특성에 따라 달리 결정될 수 있을 것 같아요.
예를 들어 사용자향 서비스가 아닌 뒷단 서비스, 백오피스 프로젝트 같은 경우는 인수테스트가 큰 의미가 없을 수 있기 때문에 아예 작성하지 않을 수도 있고요.
반대로 validation 상황 자체가 중요한 시나리오인 사용자향 서비스라면 인수테스트에서 해당 검증을 진행할 것 같네요.
만약 둘 다 비슷한 중요도를 가진다면, 더 가벼운 테스트인 단위테스트 쪽에서 검증할 것 같고요!
정답이 정해져 있는 문제는 아닌 것 같아요 :)

2022-05-26 12:41 UTC, wbluke commented on src/main/java/wooteco/subway/ui/PathController.java
> +        final PathResponse response = pathService.createPath(pathRequest.toPathServiceRequest());
> 해당 방식으로 수정했습니다! 받아온 요청을 그대로 서비스로 넘겨줘도 됐는데, 굳이 한번 꺼내서 주고 있었네요.
> 
> 적용 과정에서 질문이 하나 있습니다! 그냥 웹으로부터 받아온 request를 또 한번 service dto로 변환해주어야 하는 이유가 있을까요?
> 
> Controller와 Service의 의존 관계를 끊기 위함일까요?

정확하십니다 💯  잘 캐치하셨네요 ㅎㅎ

2022-05-26 12:41 UTC, merged