[Spring 경로 조회 - 2단계] 더즈(이동규) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #283
Opened 2022-05-23 06:42 UTC by ldk980130

안녕하세요 로운! 2단계 기능 구현 및 1단계 피드백 반영해서 왔습니다. 1단계 PR 코멘트에도 답글들을 달아 놓았고 답글 달지 않은 부분은 여기서 제 생각을 말씀드리겠습니다.

### 테스트 픽스처
sql 파일로 픽스처를 생성할까도 고민했지만 `test` 파일 안에 픽스처를 만들어 주는 클래스를 두어 생성하도록 해봤습니다.

### ControllerTest
처음엔 단순히 인수 테스트가 있으니 `ControllerTest`를 만들지 않았습니다. 하지만 로운 말처럼 인수 테스트는 시나리오 기반의 통합 테스트이기 때문에 `Controller`를 테스트 하는 테스트 클래스도 필요하다고는 느꼈습니다.

하지만 의문이었던 것은 `Contrller`를 통합 테스트로 해야할까라는 거였습니다. 저는 이미 `ServiceTest`들을 통합 테스트로 만들어 놓았습니다. 비즈니스 로직이 DB까지 잘 연동된 것을 확인하기 때문에 `ControllerTest`에서는 `Service`를 `mock`으로 사용하여 `WebMvcTest`로 테스트를 진행했습니다.

로운은 `SpringBootTest`를 사용하는 전체 통합 테스트와 슬라이스 테스트 중에 어떤 상황에서 무엇을 사용하시나요? 제가 느낀 바로는 `Controller`나 `Service `둘 중 한 곳에서는 반드시 SpringBootTest는 필요하지만 둘 다 해야할까라는 의구심이 들었습니다. 테스트 픽스처 만드는 게 `SpringBootTest`에서는 더 작업이 많아지기도 하니까요

2022-05-23 07:02 UTC, lowoon commented
네 더즈가 말한게 맞습니다! 
유지관리가 쉽지 않을 수 있기 때문에 `Controller` 혹은 `Service` 둘 중 한 곳에서만 `SpringBootTest`를 진행을 하는데요.
저는 **개인적으로** `Service`에서 mock 테스트를 진행하고, `Controller`에서 통합테스트를 진행하는 것 같아요.
`Service`가 비지니스 로직을 담당하고 있기 때문에, 다른 연결된 부분은 정상적으로 동작한다고 가정하고 `Service`가 실제로 해야하는 로직이 제대로 동작하는지 테스트하는 것에 관점을 두어야한다고 생각하기 때문입니다!
단위 테스트라는 것이 해당 메서드가 제대로 동작하는지에 관점을 두고, 통합테스트는 전체적으로 정상적을 동작하는지에 관점을 두기 때문에 어느 클래스에서 어디에 관점을 두는 것이 맞을지 고민해보고 더즈만의 기준을 잡으면 좋을것 같아요!

2022-05-23 09:44 UTC, lowoon requested changes
반가워요 더즈! 2단계도 잘 부탁해요 😄 
1단계 코멘트에 질문 남겼고, 질문에 답변달았습니다~
남긴 코멘트 확인해주세요ㅎㅎ
궁금한 점이 생기면 언제든지 DM 혹은 댓글남겨주세요 ^-^

2022-05-23 09:44 UTC, lowoon commented on src/main/java/wooteco/subway/controller/LineController.java
>  	@PostMapping
ControllerAdvice에 수정사항이 없어 여기에 코멘트 남깁니다.
`IllegalArgumentException`의 경우, 입력이 잘못되었다고 내려가고 있는데요.
로그인의 경우, id가 잘못되었는지, password가 잘못되었는지 알지 못하면 불편하지 않았나요?
에러를 발생시킬때 자세한 내용을 입력하는데 그 내용을 전달하도록 하면 더 명확하지 않을까요?

2022-05-23 09:44 UTC, lowoon commented on src/main/java/wooteco/subway/controller/PathController.java
>  		Station source = stationService.findOne(pathRequest.getSource());
**개인적인 의견입니다~ 반영하지는 않으셔도 돼요**
`findStationIdIn` 메서드를 만들어 여러 id를 입력받아 한번에 조회하도록 할 수도 있을 거 같아요~

2022-05-23 09:44 UTC, lowoon commented on src/main/java/wooteco/subway/service/PathService.java
> +		return new SubwayShortestPath(lineRepository.findAll())
new로 변수를 선언하고 정보를 찾고 할인을 하는 식으로 한줄씩 진행하는 것이 더 명확할 거 같아요!

2022-05-23 09:44 UTC, lowoon commented on src/main/java/wooteco/subway/domain/path/SubwayShortestPath.java
> +				.forEach(section -> values.put(section, line));
forEach보다는 for문이 더 명확하답니다~
stream을 사용하고 싶다면 stream으로 map을 return 하는 형태가 더 좋을 거 같아요

https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/

2022-05-23 09:44 UTC, lowoon commented on src/main/java/wooteco/subway/domain/fare/FareConstant.java
> +	public static final int BASIC_FARE = 1250;
상수만 따로 관리하게 되면 관리포인트가 한군데 더 늘어나게 되는 것 같고 책임에 맞나 싶은데요.
나이 기준이면 나이 할인 정책에서 기준 나이를 관리하고, 거리 기준이면 거리 할인 정책에서 기준 거리를 관리해야하지 않을까요?
객체 지향적으로 봤을때 현재의 클래스구조가 맞을까요?
다른 할인 정책이 늘어나는 것을 고려했을 때 어떻게 하는것이 변경이 여러군데에 생기지 않는, 다른 곳에 영향이 적은 구조일까요??

2022-05-24 00:50 UTC, ldk980130 commented on src/main/java/wooteco/subway/domain/fare/FareConstant.java
> +	public static final int BASIC_FARE = 1250;
원래는 `Enum` 상수 안에 매직 넘버를 없애고 싶었는데 상수 처리가 안 되서 다른 클래스에서 `static `상수로 처리해서 사용 했었습니다. 지금은 `Enum `안에 `inner class` 안에 상수를 만들어 사용하도록 변경하였습니다. 괜찮은 방법일까요?

2022-05-24 05:03 UTC, ldk980130 commented
> 저는 개인적으로 Service에서 mock 테스트를 진행하고, Controller에서 통합테스트를 진행하는 것 같아요

저도 로운의 생각에 동의해요! 둘 중 한 곳에 통합 테스트를 해야 한다면 `Controller`에서 진행하고 `Service`는 `Mockito`나 `fake repository`를 통해서 슬라이스 테스트를 하고 싶은 것 같아요.그렇게 하는 게 전체 테스트를 돌릴 때 더 가벼운 테스트가 될 것 같기도 하고요. 
지금은 `Service`가 통합 테스트여서 `Controller`를 슬라이스 테스트 했지만 다음부터는 인수 테스트가 있더라도 `controller `테스트에서 통합을 진행하고 `service`는 로직만 확인하는 가벼운 테스트로 하면 좋을 것 같다는 생각이 들었습니다.

2022-05-25 05:55 UTC, lowoon commented on src/main/java/wooteco/subway/domain/fare/FareConstant.java
> +	public static final int BASIC_FARE = 1250;
이거는 선택일거 같아요!
더즈가 한 방법을 사용하거나, Predicate를 enum에 static 메서드로 만들어서 사용하거나, 아래와 같은 방법, 각 전략을 클래스로 만들어서 활용하는 방법이 있을거 같은데요.
```java
public enum AgeDisCountPolicy implements DiscountPolicy,AgeCriteria {
        ADULT(19,
		fare -> fare
	) {
		@Override
		public boolean needToDiscount(int value) {
			return value >= ADULT.age;
		}
	},
	TEENAGER(13,
		fare ->
			fare.subtract(Constant.DEDUCTED_AMOUNT)
				.multiple(Constant.TEEN_DISCOUNT_RATE)
				.sum(Constant.DEDUCTED_AMOUNT)
	) {
		@Override
		public boolean needToDiscount(int age) {
			return age >= TEENAGER.age && age < ADULT.age;
		}
	},
...
```
어떠한 방법이 이해하기 편하고 나은 방법일지 고민해보고 더즈가 선택하면 될 것 같아요!

2022-05-25 10:09 UTC, lowoon approved these changes
안녕하세요 더즈!😄
이제 그만 spring 경로조회 미션을 마무리해도 될 것 같아요.
간단한 코멘트만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 spring 경로조회 미션 수고하셨습니다!

2022-05-25 10:09 UTC, lowoon commented on src/main/java/wooteco/subway/domain/fare/Fare.java
> +			return Math.min(800, (int)(Math.ceil((distance - 10) / PER_DISTANCE_OVER_TEN) + 1) * INCREASE_FARE);
할증에 대한 부분도 전략으로 만들어서 활용하면 좀 더 변경에 유연한 코드가 될 것 같아요!

2022-05-25 10:09 UTC, merged