[Spring 경로 조회 - 2단계] 차리(이찬주) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #285
Opened 2022-05-23 07:39 UTC by cjlee38

안녕하세요 제이~ 리뷰이 차리입니다.

우선, 지난번에 피드백 주신 내용 두 가지에 대해서 다음과 같은 개인적인 결론을 내렸습니다.

## 피드백
1. Optional 관련 (https://github.com/woowacourse/atdd-subway-path/pull/235#discussion_r878775111)

: 제가 개인적으로 이해하고 있는 '올바른 Optional 사용법' 은, 저희가 어떤 메소드를 호출했을 때 그 결과값이 null 일 수 있음을 명시하기 위함으로 알고 있는데요. 즉, 어떤 라이브러리의 메소드를 호출했고, 그 결과로 null이 생길수 있는데, 사용자는 그 사실을 몰랐기 때문에 NPE가 발생하는 불상사를 방지하기 위함으로 알고 있습니다.

즉, 이상적으로는 현재 jgrapht 라이브러리에 대해 사용하는 `getPath` 메소드가 null일 가능성이 있기 때문에 Optional로 돌려줘야 하지만, 모종의 이유로 그렇지 않기 때문에 NPE가 발생할 수 있는 우려가 존재합니다. 만약, findPath는 단순히 getPath를 호출하는 역할만하고, null일 경우에 호출한 쪽에서 처리해주기를 바란다면 해당 객체를 Optional로 감싸서 return하는것 또한 방법이구요.

그런데 현재는 findPath가 getPath를 호출한뒤, 적절하지 않은 경로인 경우에 대해서 예외를 처리해주고 있습니다. 즉, "항상 올바른 경로만 돌려주는 것"이 findPath가 하는 일인데요. 따라서 null인지 아닌지 내부적으로 확인하고, 처리하는 작업을 하고 있습니다. 그리고, 이렇게 확인하는 과정에서 비용이 비싼 Optional을 굳이 사용해야할까? 제작자의 의도와 부합하지 않는 API를 사용해도 괜찮을까? 라는 의문이 들어 사용하지 않았었습니다. 

2. path 중복 계산 관련 (https://github.com/woowacourse/atdd-subway-path/pull/235#discussion_r878775295)

: 처음에는 경로/거리에 대한 각각의 public 호출에 대해 대응할 수 있도록 findPath를 매번 다르게 계산하도록 했었는데요. PathFinder가 돌려줘야 할 객체가 늘어남에 따라, 각각의 메소드에서 처리하기보다 `Path`라는 클래스로 한번에 묶어서 돌려주는 것이 더 효율적이지 않을까 싶어 해당 구조로 변경하니 자연스럽게 한번만 호출할 수 있도록 변경되었습니다.

## 질문 
- 노선별 추가 금액을 계산하기 위해 DefaultWeightedEdge를 상속한 ExtraFareEdge 클래스를 만들어 사용하였는데요. 라이브러리를 사용하는 것 자체도 어색한 상황에서, 상속까지 하고 나니 뭔가 '라이브러리에 너무 의존적인가?' '이래도 괜찮나?' 라는 의문이 들었는데요. 혹시 관련해서 해주실 조언 있으시면 남겨주시면 감사하겠습니다.

부족한 코드 리뷰해주셔서 감사하다는 말씀 다시드립니다. 오늘도 좋은 하루 되세요~ ☺️

2022-05-25 00:56 UTC, JunHoPark93 requested changes
안녕하세요 차리!
2단계 잘 구현해주셨어요~
변경된 코드의 양이 많지는 않네요.
질문 주신 부분은 코멘트 남겨두었어요. 고민해보시고 의견 및 반영부탁드려요~

2022-05-25 00:56 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/domain/property/AgeTest.java
> +import org.junit.jupiter.api.Test;
전체 테스트 중에서 깨지는게 있는거같은데 한번 확인부탁드려요!

2022-05-25 00:56 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/ExtraFareEdge.java
> +    public ExtraFareEdge(Fare extraFare) {
> 노선별 추가 금액을 계산하기 위해 DefaultWeightedEdge를 상속한 ExtraFareEdge 클래스를 만들어 사용하였는데요. 라이브러리를 사용하는 것 자체도 어색한 상황에서, 상속까지 하고 나니 뭔가 '라이브러리에 너무 의존적인가?' '이래도 괜찮나?' 라는 의문이 들었는데요. 혹시 관련해서 해주실 조언 있으시면 남겨주시면 감사하겠습니다.

정답은 없지만 개인적으로는 요금을 넣으려고 상속을 쓰지는 않을거같아요. 저 요금이 부모클래스의 무언가와 연결고리가 없어보여요.
길을 찾아주는 역할을 하는 클래스가 경로와 요금을 가지고 있는 구조로 방향을 잡으면 어떨까하는 생각이 있는데 한번 고민해보시고 의견주세요~

2022-05-25 00:56 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/property/Age.java
> +    private static final int ADULT_AGE_THRESHOLD = 19;
나이도 포장해보셨네요!

2022-05-25 00:56 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/Path.java
> +    private final Distance distance;
Path도메인의 역할이 거의 없는거같은데 단순히 데이터를 저장하는 용도를 의도하셨을까요?
도메인이라면 역할에 맞는 로직을 수행하는 부분이 있어야할것같은데 한번 고민해보면 어떨까요?

2022-05-25 07:27 UTC, cjlee38 commented on src/test/java/wooteco/subway/domain/property/AgeTest.java
> +import org.junit.jupiter.api.Test;
제 로컬에서는, 빌드 툴 gradle / intellij 둘 다 돌려봐도 잘 돌아가더라구요.. 다른 크루한테 부탁해서 여쭤보니 인수테스트에서 dto를 변환하는 과정에서 에러가 났다는데, 혹시 이 부분이 맞을까요? 어느 부분에서 깨지는지 잘 확인이 안되서 이 부분 확인 한번 부탁드리겠습니다. (기본 생성자를 일단 추가해놓긴 했습니다)

2022-05-25 07:30 UTC, cjlee38 commented on src/main/java/wooteco/subway/domain/path/ExtraFareEdge.java
> +    public ExtraFareEdge(Fare extraFare) {
PathFinder가 List<Section>과 List<Fare>를 가지고 있는 케이스를 말씀하시는 걸까요? 개인적으로는 그렇게 할 경우 "요금 계산"이라는 context에 너무 의존적이라는 느낌을 지울수가 없어서.. 조금 애매하다고 느껴졌습니다.

요금 계산과 경로 조회가 둘 다 공통으로 필요로 하는 부분이 있고(e.g. distance), 또 개념상으로도 같이 묶을 수 있을 것 같은 느낌이 많이 들었는데요. 최대한 이 개념을 구분하고, 책임을 분리하고자 해보았습니다. 아직도 이게 가장 적절한 형태인지는 잘 판단이 되지 않네요..

혹시 생각하셨던 그림에 대해서 조금 더 자세히 말씀해주실 수 있을까요?

2022-05-25 07:30 UTC, cjlee38 commented on src/main/java/wooteco/subway/domain/path/Path.java
> +    private final Distance distance;
이 부분은 위쪽 피드백을 반영하면서 같이 수정되었습니다! 참고바랍니다 :)

2022-05-25 16:06 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/domain/property/AgeTest.java
> +import org.junit.jupiter.api.Test;
넵 확인해보니 그부분이 맞습니다!

2022-05-26 13:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/ExtraFareEdge.java
> +    public ExtraFareEdge(Fare extraFare) {
list와 list를 가진다는게 어떤 말씀이신가요?

> 요금 계산과 경로 조회가 둘 다 공통으로 필요로 하는 부분이 있고(e.g. distance), 또 개념상으로도 같이 묶을 수 있을 것 같은 느낌이 많이 들었는데요

넵 같이 묶는건 문제가 안되는데 이걸 상속구조로 가져가는게 어색해보여서요. 코드를 다시 보니 사라지긴했네요

2022-05-26 13:25 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/property/fare/FarePolicies.java
> +    }
여기는 쓰이지 않는것같네요! 정책을 찾는 메서드가 필요하다면 모든 정책을 반환하는메서드보다 조건에 맞는 정책을 반환하는 메서드만있어도 될거같아요.

2022-05-26 13:25 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/domain/property/AgeTest.java
> +import org.junit.jupiter.api.Test;
다시 잘 통과하네요!

2022-05-26 13:26 UTC, JunHoPark93 approved these changes
안녕하세요 차리!
리뷰 반영하느라 고생많으셨어요.
구조 관련해서 궁금증이 남아 있다면 다시 말씀주세요!
다음 미션도 화이팅입니다!

2022-05-26 13:26 UTC, merged

2022-05-27 00:46 UTC, cjlee38 commented on src/main/java/wooteco/subway/domain/path/ExtraFareEdge.java
> +    public ExtraFareEdge(Fare extraFare) {
텍스트가 깨진걸 못봤네요. `List<Station>` 과 `List<Fare>` 를 가지고 있는 구조를 말씀드렸습니다 ㅎㅎ;

약간 지금 머릿속이 혼란스러워서.. 조금 정리해보면 다음과 같습니다.

가장 먼저, pathfinder가 가질 수 있는 필드의 종류는 총 4가지로 볼 수 있을 것 같은데요. 전체 노선도에 대한 그래프 정보를 담고있는 `WeightedMultigraph` ,그리고 이를 받아 다익스트라 알고리즘을 활용해 최단거리를 찾아주는 `DijkstraShortestPath`, 그 중에서 출발지와 도착지를 기준으로, 경로를 갖는 `GraphPath`, 마지막으로 `GraphPath`에서 얻어내는 `List<Station> 등` 이렇게 입니다.

처음에는 `WeightedMultiGraph` 혹은 `DijkstraShortestPath` 를 갖고 있어야 적절하다고 생각했는데요. 그 이유는 전체 노선에 대한 경로를 갖고 있고, source와 destination(=target)가 매 호출마다 달라질 수 있기 때문이라고 생각했습니다. 전체 노선에 대한 정보를 담고 있는 lineseries, 그리고 source와 destination 이 세 가지를 한번에 받아내서 `GraphPath` 혹은 `List<Station> 등` 을 가질수도 있는데요. 저는 `그렇게 시도할 수 있는 근거가,  경로 조회마다 외부(service)에서 pathfinder의 객체를 매 번 새로 만든다는 사실을 알고 있기 때문` 이라고 보았기 때문입니다. 즉, pathfinder가 스스로 자기 자신이 언제 생성되는지에 대해서 알고 있고, 그에 따라 행동하는 것은 어색하다고 생각했어요.

그런데 경로에 대한 정보는 계속 갱신될 수 있다는 점을 감안하면, pathfinder가 "매번 새로 만들어야한다" 라는 사실을 알아도 무관할 것 같다는 생각이 들었고, 그에 따라 `GraphPath`, 혹은 `List<Station> 등` 을 가질 수 있는 선택지도 생겼습니다. List<Station> 과 같은 결과 정보를 미리 담고 있는 것 또한, 위에서 말씀드렸던 것과 비슷한 맥락으로 너무 특정한 context에 얽매인다는 생각이 들었습니다. 즉, `List<Station>` 이나, `List<Fare>` 를 돌려주는 것은 "path finder가 할 수 있는 일 중 하나" 일 뿐이지, pathfinder가 해당 정보를 필드로 갖고있고 이를 getter로 돌려주는 것은 "어떤 객체가 나를 호출할 계획인지" 에 대해서 알고 있는 것처럼 느껴졌습니다. 적절한 표현인지는 모르겠지만, 캡슐화가 이루어지지 않은 것 같았구요.

---
그리고, Edge의 상속에 대한 이야기입니다.
말씀주신대로, Edge를 상속해서 Fare만 담는 것은, "간선"이라는 맥락과 연결고리가 많이 떨어진다는 느낌을 받았는데요. 그렇다고 해서 Section을 넣어준다고 할 지라도, Section에 Fare에 관한 정보가 없기 때문에, 결국 Fare를 넣어줄 수 밖에 없었습니다. 물론, Fare를 뺀다고하면 Section을 기반으로 다시 line을 조회하면서 알아낼 수는 있는데요. 이는 두 가지 문제점이 있을 것으로 보았습니다. 첫 째는, 모든 노선과 간선에 대한 정보를 field로 갖고있어야 한다는 점이고(만약 갖지 않는다면, 외부(=service)에서 조회하는 로직을 다시 호출해야 합니다.), 둘 째는, 어찌되었든 결국 line을 다시 반복하면서 fare를 찾아야 하는 로직이 불필요하게 발생한다는 점입니다.

결국 최종적으로는, 상속받은 Edge가 Section과 Fare를 갖도록 수정했는데요. 외부에서 사용될 일이 없도록 PathFinder(정확히는 JgraphtPathFinder) 내부에 private static class로 선언해두었습니다.

2022-06-02 11:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/path/ExtraFareEdge.java
> +    public ExtraFareEdge(Fare extraFare) {
요거 늦게봤네요. 머지가 된 이후에 달리는 글을 f/up하기가 힘드네요. 잘 생각해주셨어요! 👍