[Spring 경로 조회 - 2단계] 쿼리치(정석윤) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #293
Opened 2022-05-23 11:13 UTC by meatsby

안녕하세요 로운! 꼼꼼한 리뷰 너무 감사드립니다!
덕분에 학습할 키워드도 많이 얻었고 테스트에 대한 생각도 좀 더 깊어진 것 같아요!
남은 기간도 잘 부탁드리겠습니다! 🙇🏻‍♂️

[질문 및 리뷰 반영 정리해두었습니다!](https://github.com/woowacourse/atdd-subway-path/pull/217)

2022-05-24 07:07 UTC, lowoon requested changes
반가워요 쿼리치! 2단계도 잘 부탁해요 😄 
질문에 답변달았습니다~
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점이 생기면 언제든지 DM 혹은 댓글남겨주세요 ^-^

2022-05-24 07:07 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Path.java
> +        WeightedMultigraph<String, DefaultWeightedEdge> graph = new WeightedMultigraph(DefaultWeightedEdge.class);
정적팩토리 메서드 좋은데요.
Path를 만들기 위해서 static 메서드가 너무 많아지는거 같아서요.
내부 필드나 생성자를 어떻게 가져가면 좀더 단순화 할 수 있을까요?
최단 거리를 계산 하는 것은 메서드가 호출되었을 때 진행할 수도 있지 않을까요?

2022-05-24 07:07 UTC, lowoon commented on src/main/java/wooteco/subway/domain/farepolicy/FarePolicy.java
> +
전략패턴 좋네요 👍  
다만 if문으로 policy를 분기하기 보다 enum으로 관리하면 좀더 명확하지 않을까요?
그리고 enum에서 기준을 관리하면 역할에 좀 더 부합하지 않을까요?
기준들은 상수로 관리하면 더 좋을거 같아요~

2022-05-24 07:07 UTC, lowoon commented on src/main/java/wooteco/subway/domain/FareCalculator.java
>  public class FareCalculator {
현재의 구조라면 FareCalculator가 아닌 Fare로 도메인을 가져가도 되지 않을까 싶구요.
거리에 따른 추가 요금은 여기에서 계산되는데, 기준이 추가되거나 구간이 변경되었을 때에는 코드 변경으로 인한 영향이 크지 않을까요?
요금할인처럼 추가요금도 전략으로 가져가면 변경에 더 유연한 구조가 되지 않을까요?

2022-05-24 07:07 UTC, lowoon commented on src/test/java/wooteco/subway/service/LineServiceTest.java
>          Station upStation = stationDao.save(new Station("강남역"));
SpringBootTest로 진행하기 위해서 먼저 설정해주어야하는 것들이 많을 거에요.
그래서 유지보수를 하는데 쉽지 않을 수 있습니다.
그래서 Service나 Controller 중 하나에서는 mock, 하나에서는 spring boot test로 진행해서 유지 보수에 용이하도록 하는것 같아요!
저는 개인적으로 Service에서 mock테스트를 진행하는데요.
어느 곳에서 어떤 테스트를 진행하면 좋을지 고민해보고 쿼리치만의 기준을 세우면 좋을것 같아요!

2022-05-24 11:09 UTC, meatsby commented on src/main/java/wooteco/subway/domain/Path.java
> +        WeightedMultigraph<String, DefaultWeightedEdge> graph = new WeightedMultigraph(DefaultWeightedEdge.class);
Sections 를 받아 Path 객체를 생성하여 사용하도록 변경해봤어요! 주입받은 Sections 를 통해 다익스트라 객체를 필드값으로 갖게끔 바꿔 최단경로나 최단거리 계산을 호출이 들어왔을 때 수행할 수 있도록 변경했습니다!

2022-05-24 11:44 UTC, meatsby commented on src/main/java/wooteco/subway/domain/farepolicy/FarePolicy.java
> +
조건에 만족하는 나이 범위를 enum 으로 변경해봤어요! 또한, 팩토리 클래스를 구현하여 제공된 나이에 맞춰 알맞는 정책을 반환하도록 구현해보았습니다!

2022-05-25 02:49 UTC, meatsby commented on src/test/java/wooteco/subway/service/LineServiceTest.java
>          Station upStation = stationDao.save(new Station("강남역"));
mock에 대해서 많은 고민이 있었는데요!

Service 내부에서 mock 을 통해 테스트를 수행하게 된다면 @SpringBootTest 를 적용하지 않아도 된다는 장점이 있지만, 개인적인 생각으론 Service 테스트는 실제 Repository 레이어와 소통하는 과정을 테스트해야 한다고 생각했어요.

mock 을 사용하게 된다면 Service 가 Repository 와 소통하는 과정을 미리 명시해주어야하는데, 예상과 다르게 Dao 가 작동하게 된다면 테스트에서 잡히진 않지만, 실제 상황에선 전혀 다른 결과가 발생할수도 있을 것 같아요.

막상 또 인수테스트나 Controller 테스트를 통해 실제 결과를 확인할 수 있겠지만, Service 테스트에서 Service 가 잘못 작동하는 것을 잡아내지 못한다는 것이 어색한 것 같아요!

로운은 이 부분에 대해 어떻게 생각하시는지 궁금합니다!

2022-05-25 03:02 UTC, meatsby commented on src/main/java/wooteco/subway/domain/FareCalculator.java
>  public class FareCalculator {
Fare 로 도메인을 변경하고 할인정책과 같이 거리당 FarePolicy 를 적용해서 기준 추가나 구간 변경에 유연할 수 있도록 변경해보았습니다!

2022-05-25 12:17 UTC, lowoon commented on src/test/java/wooteco/subway/service/LineServiceTest.java
>          Station upStation = stationDao.save(new Station("강남역"));
dao에서 기본적인 기능은 테스트를 진행하지 않지만 복잡한 쿼리의 경우에는 테스트를 만들어야할 텐데요.
dao에서 오류가 발생하는 경우라면 dao test에서 잡히지 않을까요?
통합테스트와 단위테스트의 목적이 다르다고 생각하는데요.
통합테스는 전체적으로 정상동작하는 것을 테스트를 목적으로 하고, 단위테스트는 그 단위에서 진행해야하는 로직이 정상적으로 동작하는지에 집중하는 것을 목적으로 한다고 생각해요.
현재의 구조에서는 crud가 주이기 때문에 repository가 잘 동작하는 것이 중요하다고 생각할 수 있지만, 주문을 하고 고객에게 카톡 알림을 보내고 업주에게 주문을 전달하는 로직이 진행된다고 하면, repository에 집중하기보다 실제로 주문을 받은 후에 고객과 업주에게 전달이 제대로 되는지를 테스트해야하지 않을까요? 다른 부분은 정상적으로 동작하고 실제로 메서드내에서 동작해야하는 로직에 집중을 하는 것인데 이 집중은 controller와 service 중 어디에서 하는것이 좋을까요??
한번 고민해보시고 쿼리치만의 기준을 세우면 좋을것 같아요!

참고하시면 좋을것 같아요!
https://tecoble.techcourse.co.kr/post/2021-05-25-unit-test-vs-integration-test-vs-acceptance-test/

2022-05-25 12:22 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Path.java
> +        WeightedMultigraph<String, DefaultWeightedEdge> graph = new WeightedMultigraph(DefaultWeightedEdge.class);
저는 정적팩토리 메서드를 사용하면서 메서드 역할 분리를 말씀드렸던 건데요 😅 
지금 구조도 좋습니다! 어떻게 하는게 좋을지는 한번 생각해봐주세요ㅎㅎ

2022-05-25 12:38 UTC, lowoon approved these changes
안녕하세요 쿼리치!😄
이제 그만 spring 경로 조회 미션을 마무리해도 될 것 같아요.
간단한 코멘트만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 spring 경로 조회 미션 수고하셨습니다!

2022-05-25 12:38 UTC, lowoon commented on src/main/java/wooteco/subway/domain/discountpolicy/DiscountPolicyFactory.java
> +public class DiscountPolicyFactory {
factory로 관리 좋네요 💯 
역할이 작으면 enum에서 policy를 함께 관리해주는 방법도 있을 수 있겠다라고 참고만 하시면 좋을 것 같아요ㅎㅎ

2022-05-25 12:38 UTC, lowoon commented on src/main/java/wooteco/subway/domain/farepolicy/FarePolicy.java
> +    int calculate(int distance);
의미를 생각했을때 fare인 요금 보다는 surcharge와 같은 부가요금이 좀 더 맞는 이름이지 않을까요?

2022-05-25 12:38 UTC, lowoon commented on src/main/java/wooteco/subway/service/dto/LineServiceRequest.java
> +    public LineServiceRequest(String name, String color, Long upStationId, Long downStationId, int distance,
이 부분은 1단계 코멘트에 대한 답변을 보고 한번 생각해보시면 좋을것 같아요ㅎㅎ

2022-05-25 12:38 UTC, merged