[Spring 경로 조회 - 2단계] 그린론(유재서) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #299
Opened 2022-05-23 12:26 UTC by jaejae-yoo

카일 안녕하세요! 
이전 단계에서 꼼꼼한 리뷰 남겨주셔서 감사드려요 🙏🏼 
[1단계](https://github.com/woowacourse/atdd-subway-path/pull/186)에 남겨주신 리뷰에 대한 답변 남겨 놓았어요! 
다시 한번 감사합니다. 😄

브라운의 ATDD 강의를 듣고 이번 미션을 구현하면서, `컨트롤러 테스트`를 추가해 봤어요!

인수 테스트가 있어서 컨트롤러 테스트를 작성해야 하는지 의문이 있었는데, 
MockMvc를 사용하니 컨트롤러만 슬라이스하여 요청과 응답만 테스트할 수 있어서 이점이 있다는 생각이 들었습니다.
반면 서비스 테스트에서 Dao를 Mock으로 사용하는 것은 장점을 느끼지 못해 구현했다가 제거했어요.
정해준 값을 그대로 반환하는 것보다, 실제 객체를 사용해서 비즈니스 로직을 테스트 하는 것이 맞다고 생각했습니다.
해당 과정을 통해 Mock을 어디까지 사용해야 하는지 고민해 볼 수 있었던 것 같아요.

추가로 이번 단계에서는 여러 전략을 사용할 수 있는 경우가 많았던 것 같아요. (거리별 요금 계산, 연령별 요금 할인)
현재는 복잡한 로직이 없어 인터페이스가 아닌 enum 클래스(Fare, Age 클래스)로 구현해 보았어요.

이번 미션도 잘 부탁드려요 카일! 
많은 피드백 부탁드립니다. 🙌😄

2022-05-26 02:53 UTC, KIMSIYOUNG requested changes
안녕하세요 그린론! 
2단계도 잘 구현해주셨네요. 
몇가지 코멘트 남겼는데 확인 부탁드립니다.
궁금하신 내용은 편하게 말씀해주세요!

2022-05-26 02:53 UTC, KIMSIYOUNG commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
주석까지 있으니까 // spring 하위로 옮기는게 어떨까요ㅎㅎ

2022-05-26 02:53 UTC, KIMSIYOUNG commented on docs/README.md
> +- 연령별 요금 할인
이런 정책에서 5세이하는 어떻게 처리될건지, 80세이상은 어떻게 처리할건지 등을 의심(?)하고 정책이 미비하다면 그린론만의 정책을 정하는 것도 좋을 것 같아요🙂

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/DijkstraPathStrategy.java
> +public class DijkstraPathStrategy implements PathStrategy {
도메인이 인프라를 의존하지 않도록 인터페이스를 통해 잘 구현해주셨네요🙂 조금 더 나아가서 아래의 두가지도 고민해보면 좋을 것 같아요.

1. 현재 이 클래스가 도메인 패키지에 있는게 적절할까요?
2. SectionWeightEdge 클래스도 결국 상속관계로 인프라에 의존하는데 어떻게 변경해보면 좋을까요?

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/DijkstraPathStrategy.java
> +    private static GraphPath initPathGraph(List<Section> sections, Set<Long> ids, Long source, Long target) {
ids라는 변수명은 너무 포괄적인 것 같아요🙂 모든 메소드가 독립적이라고 생각할 필요는 없지만, 그래도 네이밍을 통해 조금 더 어떤 값이 필요한지 의미를 잘 작성해주면 그린론 이외에 다른 사람이 해당 코드를 유지보수할 떄도 더 편할 것 같아요.

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/DijkstraPathStrategy.java
> +        } catch (IllegalArgumentException exception) {
라이브러리에서 던지는 예외를 잡아서 커스텀하게 잘 수정해주셨네요👏

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Path.java
> +        int lineExtraFare = findMostExpensiveExtraFare(lines);
거리를 기반으로 Fare를 찾아왔는데, 아래에서는 다시 fare.calc(distance)를 호출하고 있네요. 조금 부자연스럽지 않나요?

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Path.java
> +                .findAny().orElseThrow(() -> new ClientException("존재하지 않은 line id입니다."))
여기도 줄바꿈 해주시면 좋을 것 같아요.

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Path.java
> +                .filter(line -> line.getId() == id)
== 비교가 맞나요? 필드값은 Long인데 게터는 long을 리턴하고 있네요. 

어떤 사이드이펙트가 있을 수 있을까요?

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Age.java
> +    public static Age find(Long number) {
Enum을 통해 나이별로 달라지는 것들을 잘 구현해주셨네요🙂 

파라미터의 네이밍이 적절하지 않은 것 같아요. findByAge 또는 find(Long age)형태가 적절할 것 같아요.

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Age.java
> +                .filter(age -> number <= age.boundary)
만약에 CHILDREN 이 INFANT 앞에 선언되어있다면 어떤 이슈가 있을 수 있을까요?

정렬된 순서내에서 이들을 찾아온다는 것이 드러나지 않는데 저는 개인적으로 드러내는 것을 좋아해요. 아래의 두가지중 편하신거로 변경해보시면 좋을 것 같아요. 

1. 현재 구조에서 소팅을 추가한다
2. 정렬되지 않더라도 찾을 수 있는 형태로 변경한다.

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Fare.java
> +        distance -= previousSection;
기존 값을 변경하는 것보다 새로운 값을 할당하는게 사이드이펙트 방지에 유리할 것 같아요.

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/SectionWeightEdge.java
> +    public double getWeight() {
라이브러리를 잘 이해하고 사용하고 계시네요🙂

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/dto/PathRequest.java
> +    @NotNull(message = "출발역을 입력해주세요.")
벨리데이션👏

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/domain/DijkstraPathStrategyTest.java
> +    @DisplayName("Path 객체 반환 확인")
이 부분은 무엇을 테스트하고자 하는걸까요?

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/domain/PathTest.java
> +    void findShortestPathFromVarious() {
갈 수 있는 경로가 2개이상인 경우는 어떻게 처리되는지 추가해주면 좋을 것 같아요.

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/ui/PathControllerTest.java
> +class PathControllerTest {
컨트롤러 테스트도 잘 작성해주셨네요🙂 응답값으로 어떤 값들이 와야하는지 테스트하는 것도 추가해주면 좋을 것 같아요.

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +    void findShortestPath() {
이미 다른 단위테스트에서 도메인에 대해선 검증하고 있지만, PathResponse에 값들이 잘 매핑되었는지 확인하기위해선 다른 값들도 검증결과에 추가해줘야할 것 같아요🙂

2022-05-26 02:53 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +@Sql(scripts = {"classpath:schema.sql"}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
안녕하세요 그린론! 너무 좋은 고민을 하고 계신 것 같습니다. 이유는 같이 말씀을 안해주셨는데, 왜 그렇게 느끼셨는지 공유해주실 수 있나요?

```MockMvc를 사용하니 컨트롤러만 슬라이스하여 요청과 응답만 테스트할 수 있어서 이점이 있다는 생각이 들었습니다. 반면 서비스 테스트에서 Dao를 Mock으로 사용하는 것은 장점을 느끼지 못해 구현했다가 제거했어요.```

2022-05-26 11:21 UTC, jaejae-yoo commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
81a3fcd846f7bf29fbaab207c90289bb7b98c2a6 순서 변경하였습니다! 👍

2022-05-26 11:22 UTC, jaejae-yoo commented on docs/README.md
> +- 연령별 요금 할인
caf5e16c2cc1c620f8fc89523722f2200b824959
c8e65b34d9fc35c7fc092e6df048fda7bdf9c986

기능 요구 사항에 추가하지 않았었네요.. 😅 추가로 80세 이상인 경우도 추가하였습니다!

2022-05-26 11:25 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/DijkstraPathStrategy.java
> +public class DijkstraPathStrategy implements PathStrategy {
1) 외부 라이브러리에 의존하고 있는 현재 클래스를 servcie/infra 패키지로 이동하였습니다!
2) 06e62d679d9ec77193e925e47cbf8b3919516035 도메인 객체 Path가 `SectionWeightEdge` 클래스에 의존하고 있던 것을 제거했습니다! 현재는 `DijkstraPathStrategy`클래스에만 연결되어 있습니다.

2022-05-26 11:26 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/DijkstraPathStrategy.java
> +    private static GraphPath initPathGraph(List<Section> sections, Set<Long> ids, Long source, Long target) {
5ea9dc04de819c7c394db50c9b765db736bf407c 더 명확하게 변경해보았습니다. 😄

2022-05-26 11:28 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/Path.java
> +        int lineExtraFare = findMostExpensiveExtraFare(lines);
d276ff40451b0a0a46bb4093a77ddda653a2bf14 제가 작성한 코드이다 보니 어색한 부분을 잘 느끼지 못했던 것같아요.. 😅

하나의 메서드에서 처리하는 것이 좋을 것같아, `calculateFare`라는 메서드를 추가했습니다!

2022-05-26 11:29 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/Path.java
> +                .findAny().orElseThrow(() -> new ClientException("존재하지 않은 line id입니다."))
놓쳤던 부분이네요..! 🫢

2022-05-26 11:36 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/Path.java
> +                .filter(line -> line.getId() == id)
line.getId()의 리턴 타입을 `Long`으로 변경했습니다! 

해당 방식은 비교를 위해 언박싱하는 과정에서 NPE문제가 발생할 수 있을 것같아요!

2022-05-26 11:38 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/Age.java
> +    public static Age find(Long number) {
ed2fc1d44ecc3cf59a65a39896f9c6cb067e9ec0 `findByAge`로 변경해 보았습니다 :)

2022-05-26 11:39 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/Age.java
> +                .filter(age -> number <= age.boundary)
둘의 순서가 달라지면 의도하지 않은 Age가 나오네요.. 🥲
5b06ca65a6d6da045cd388e5c2870a28e9f57eed 정렬하도록 개선했습니다!

2022-05-26 11:40 UTC, jaejae-yoo commented on src/main/java/wooteco/subway/domain/Fare.java
> +        distance -= previousSection;
904668887aa8bf00de78d3ed80d0525cd54c38c7 파라미터 값을 변경하지 않도록 수정했습니다!

2022-05-26 11:41 UTC, jaejae-yoo commented on src/test/java/wooteco/subway/domain/PathTest.java
> +    void findShortestPathFromVarious() {
17492b73c8217ae54af93859cc8b528c57c9fd40 경로 조회 예외 추가하였습니다! 👍

2022-05-26 11:42 UTC, jaejae-yoo commented on src/test/java/wooteco/subway/ui/PathControllerTest.java
> +class PathControllerTest {
117fafb92557fc9784937ae1b8cf18fe4540fe7e 응답 값 테스트 전체적으로 추가했습니다 😄

2022-05-26 11:43 UTC, jaejae-yoo commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +    void findShortestPath() {
89e7df5a653dc1109b2c18f261a9ee7f81582708 객체로 검증하도록 개선해 보았습니다!

2022-05-26 11:50 UTC, jaejae-yoo commented on src/test/java/wooteco/subway/domain/DijkstraPathStrategyTest.java
> +    @DisplayName("Path 객체 반환 확인")
DijkstraPathStrategy 클래스의 findPath 메서드에서 경로를 찾고 Path 객체를 반환하도록 구현되어 있는데, 잘 생성이 되는지 검증해보고 싶어서 생성한 테스트였어요! 
그런데 다시 생각해보니 객체가 생성되는지 확인하는 것보다, 객체의 데이터를 확인하는 것이 더 좋을 것같아 변경하였습니다. 6ffbbee0d92706b7d87782ede7137ccd88f868f7

2022-05-26 12:09 UTC, jaejae-yoo commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +@Sql(scripts = {"classpath:schema.sql"}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
`컨트롤러 테스트 MockMvc 사용`
현재 제 코드에서는 Acceptance 클래스에서 시나리오를 작성하여 RestAssured를 사용하여 실제 요청을 보내서 전체적인 로직을 테스트하고 있는데요.
컨트롤러 테스트를 해야하는 지에 대해 고민하다, `컨트롤러 테스트와 인수 테스트의 차이점`에 대한 의문이 들었습니다.
인수 테스트에서는 요청을 보내 End-to-End로 전체적인 비즈니스 로직을 테스트하고 있습니다.
그렇다면 `컨트롤러 테스트에서도 결국 API 접점을 검증하는 E2E 테스트를 하게 되는 것이 아닌가?`라는 생각을 했어요.
위의 이유 때문에 컨트롤러 테스트의 필요성을 느끼지 못했습니다.
그러던 중 MockMvc에 대해 학습하게 되었는데요.
MockMvc를 사용하니, 컨트롤러단만 슬라이스하여 요청과 응답을 테스트할 수 있게 되었습니다.
이렇게 되면 요구 사항의 전체적인 테스트는 인수 테스트에서 수행하고, 비즈니스 로직은 도메인과 서비스, 요청과 응답은 컨트롤러에서 테스트하면 각자 테스트해야 하는 역할을 잘 수행하고 있다고 생각해서, 컨트롤러 테스트를 하는 의미가 있다고 생각했습니다.

`서비스 테스트 Mock 사용`
서비스 테스트에서 Dao를 Mock 객체로 테스트하였었는데요.
Mock을 사용하니 DB와 연결하지 않기 때문에 테스트가 외부 요인에 영향을 받지 않는다는 장점은 있었지만, 각각의 동작마다 기대하는 값을 지정해 주어서 테스트하는 방법이 올바른 방법인가?라는 생각을 했어요. 
이렇게 되면 `실제 서비스에서 잘 동작하지 않을 수 있다`는 생각이 들었어요. 따라서 테스트용 DB를 분리하여, 실제 동작과 최대한 유사한 환경에서 테스트하는 것이 더 좋은 방법이 아닌 것인지 생각했습니다!

카일의 의견도 여쭙고 싶어요! 🙏🏼

2022-05-26 12:11 UTC, jaejae-yoo commented
카일 안녕하세요 ~ 
꼼꼼한 피드백 정말 감사드려요! 
남겨주신 리뷰에 대한 답변과 질문 남겨 놓았어요.
이번 리뷰도 잘 부탁드려요. 감사합니다! 😄

2022-05-28 01:40 UTC, KIMSIYOUNG commented on docs/README.md
> +- 연령별 요금 할인
엇 실제로 기능요구사항에 없는 내용입니다🙂 개발할 때 정책적으로 애매한 부분들을 어떻게 처리할건지 고민하는 습관을 가지면 좋을 것 같아서 말씀드린거였어요ㅎㅎㅎ

2022-05-28 02:02 UTC, KIMSIYOUNG approved these changes
안녕하세요 그린론!
리뷰 반영도 잘해주시고 커밋번호도 친절하게 남겨주셔서 감사합니다. 
덕분에 리뷰하기가 많이 수월했던 것 같아요. 
미션은 여기서 머지할게요! 몇가지 코멘트와 답변 달았는데 확인 부탁드립니다.
궁금하신 내용은 언제든 편하게 말씀해주세요🙂

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Age.java
> +                .orElse(ELDER);
요런 부분도 사소한 부분이지만 위의 바운더리에 걸리지 않는 값이 있다면 ELDER로 처리하는게 맞을지 고민해보면 좋을 것 같아요. 왜냐면 찾지 못하면 모두 0원처리 될테니까요. 

추가로 음수에 대한 처리도 필요할 것 같아요🙂

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Path.java
> +        return Age.findByAge(age).calc(lineExtraFare + Fare.calculateFare(distance));
요 부분에서 `lineExtraFare + Fare.calculateFare(distance)` 해당 로직은 인라인으로 사용하지 않고 변수로 선언하는게 의미가 더 잘 전달될 것 같아요. 

거리요금을 먼저 계산하고 해당 요금에서 나이조건에 따른 할인율을 적용하는 것이기 떄문에 자연스럽게 읽히도록 선언해주면 좋을 것 같아요.

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Path.java
> +                .stream()
취향이긴한데 같은 줄에 있어도 괜찮지 않을까요🙂

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/infra/DijkstraPathStrategy.java
> +public class DijkstraPathStrategy implements PathStrategy {
인프라라는 패키지로 잘 분리해주셨어요🙂 조금 더 나아가서 서비스내에 인프라가 있어야할까요 인프라는 서비스와 동등한 수준의 패키지레이어를 가져도 괜찮을까요?

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/PathService.java
> +        return new PathResponse(stations, path.getDistance(), path.calculateFare(lineDao.findAll(), pathRequest.getAge()));
중요한 비즈니스 로직을 호출하는 행위는 개인적으로 인라인으로 적지 않고 선언하는 편이에요 참고만 해주세요🙂

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/PathService.java
> +    private final SectionDao sectionDao;
서비스에서 다른 다오에 직접 접근하는 것에 대해서 혹시 어떻게 생각하시나요? 서비스 > 서비스 의존과 서비스 > 다오 의존에 대해서요!

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Age.java
> +public enum Age {
`Age`혹은 `Fare`는 값객체를 연상시키지 않나요? 

해당 로직은 나이에 따른 `요금을 결정`하는 로직이니까 네이밍을 수정해보면 어떨까요ㅎㅎ

2022-05-28 02:02 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +@Sql(scripts = {"classpath:schema.sql"}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
좋은 의견 공유해주셔서 감사합니다🙂 제 의견도 같이 말씀드리면 좋을 것 같아요.

1. 컨트롤러 테스트 MockMvc 사용
- Mocking없는 컨트롤러 테스트와 인수테스트는 모두 `통합테스트`라는 관점에서 비슷하다고 볼 수 있고 그 때문에 오해가 생길 수 있을 것 같아요. 둘다 E2E테스트를 의미하는 것은 맞지만, 인수테스트는 어떠한 시나리오에 따른 전체 동작에 대한 검증이고 컨트롤러는 API하나에 대한 검증을 의미하기에 인수테스트 과정에서 컨트롤러 테스트가 포함될 수 있겠죠. 그렇게 되는 경우 중복된 테스트로 느낄 수도 있을 것 같구요. 말씀하신 대로 요구사항의 전체적인 테스트는 인수테스트에서 수행한다면 컨트롤러는 목킹을 통해 요청과 응답에 대한 테스트만 수행하는 것이 자연스러운 결론인 것 같아요.

2. 서비스 테스트 Mock 사용
- 저도 동일하게 생각합니다🙂 이상적으로 생각했을 때 `각 레이어가 자신의 역할을 독립적으로 잘 수행한다면, 레이어간 연결되었을 때도 문제 없이 수행되어야 한다 ` 라고 생각할 수 있지만 실제로는 그렇지 않은 경우가 너무 많은 것 같습니다. 그렇기에 레이어가 많이 깊어진다면 어디부터는 목킹처리할 것인가? 에 대한 고민을 해야겠지만 현재와 같이 서비스와 레파지토리 두가지의 레이어라면 통합으로 연결까지 테스트하는 것이 `이상적이진 않지만` 현실적으로 더 좋은 방법이라고 생각해요. 이 연결에 대한 것을 인수테스트를 통해 연결을 확인할 수 있다고 생각할 수 있지만 인수테스트란 시나리오 기반이지, 모든 예외 케이스를 검증하려는 목적이 아니니까요

2022-05-28 02:02 UTC, merged