[Spring 경로 조회 - 2단계] 라라(박세은) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #307
Opened 2022-05-23 19:16 UTC by sure-why-not

미르 안녕하세요!! 👋🏻👋🏻👋🏻

1단계에서 미르의 피드백을 통해 생각해보지 못했던 부분까지 꼼꼼하게 확인하고 깊게 생각해볼 수 있었습니다!!
감사합니다!! 😆👍🏻👍🏻👍🏻

추가로  2단계 요구사항을 구현해보았습니다!!
최대한 변경점 없이 구현해보려 했는데 1단계에서 Line 에 ExtraFare(추가요금) 을 갖고있지 않다가
2단계에서 추가하니 테스트코드의 Line 객체들이 다 깨져서 변경 파일이 많습니다. 😭

[이 피드백](https://github.com/woowacourse/atdd-subway-path/pull/222#discussion_r878889465)에 대해서 궁금한 점이 있습니다!! 🥺
미르 말씀대로 클래스의 네이밍으로 해당 문맥을 명확하게 파악할 수 있는 장점이 굉장히 좋아보이더라구요!! 👍🏻👍🏻👍🏻
한편으론 사소한 상황까지 클래스 네이밍을 정해야하기 때문에 관리해야할 Exception 이 굉장히 많아지고, 네이밍으로 전달하는데 한계가 있을 수 있지 않을까? 라는 생각도 들어서요!! 🤔🤔🤔 
비슷한 예외상황들을 묶고, 메세지로 더 상세하게 예외 상황을 전달하는 것이 효과적이지 않을까란 생각도 들더라구요,,,,🧐 
미르는 이런 비용을 감안하더라도 동일한 예외 메시지를 전달하는 상황이 아니라면 다른 Exception을 만드는 것에 대해 긍정적으로 생각하시는지 궁금합니다!!! 

이 외에도 부족한 점들이 많을텐데 리뷰 잘 부탁드립니다!! 🤗😬🤓🥰

2022-05-24 00:18 UTC, ddu0422 requested changes
안녕하세요 라라 ! 미르예요 :)

새벽까지 열심히 구현해주셨네요 👍🏻 정말 고생하셨어요 !
간단한 코멘트 남겨드렸으니 확인해주시면 감사하겠습니다 :)

궁금한 점은 코멘트 남겨주시거나 언제든지 DM주세요 😎

---
### Q&A

> 한편으론 사소한 상황까지 클래스 네이밍을 정해야하기 때문에 관리해야할 Exception 이 굉장히 많아지고, 네이밍으로 전달하는데 한계가 있을 수 있지 않을까? 라는 생각도 들어서요!! 🤔🤔🤔
비슷한 예외상황들을 묶고, 메세지로 더 상세하게 예외 상황을 전달하는 것이 효과적이지 않을까란 생각도 들더라구요,,,,🧐
미르는 이런 비용을 감안하더라도 동일한 예외 메시지를 전달하는 상황이 아니라면 다른 Exception을 만드는 것에 대해 긍정적으로 생각하시는지 궁금합니다!!! 😄

네! 저는 사소한 상황에서도 에러 메시지를 따로 작성하는 편입니다.
가장 큰 이유는 유지보수할 때 유용하다고 생각하기 때문이예요.

ExtraFare 클래스 에러 메시지를 변경하는 경우 누군가가 ExtraFare 클래스를 수정해야한다고 가정해볼게요.
두 명이 동일한 파일을 수정하면 conflict가 날 수 있어요.
이런 상황은 상당히 사소해요. 하지만 스트레스를 지속적으로 받을 수 있기 때문에 장기적인 관점에서 좋지 않다고 판단했어요.

보통, 에러 메시지가 동일한 경우를 많이 봤지만 외부에서 주입 받는 형태로 구현되어 있는 경우 변경하기 너무 어렵더라구요 😢 

또한, 각자 책임을 지니게 하면서 라라의 의견대로 테스트 코드에서 작성을 하지 않을 수도 있다고 생각해요. 
에러 메시지를 테스트하는 것도 중요하지만, 어떤 값이 들어와서 에러가 발생했는지가 더 중요하다고 생각해요 !

외부에서 주입 받는 형태에서 에러 메시지가 변경되면, 테스트 코드도 수정을 해야하기 때문에 비용이 배로 늘어가지 않을까요?

하지만, 현재 Application이 작아 동일한 메시지도 없고 사용하는 부분이 많지 않아 괜찮을 것 같아요 !
`저는 이런 생각을 가지고 있어요~` 정도로만 봐주시면 될 것 같아요 ㅎ_ㅎ

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Fare.java
> +    private static int calculateFareByDistance(final Distance distance) {
Distance도 DistanceAndAgePolicy처럼 if 문을 제거해보는 방향으로 변경해볼 수 있지 않을까요?

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return List.copyOf(value);
값을 복사하여 반환하셨네요 ! 👍🏻 👍🏻

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/SubwayMap.java
> +            throw new NoSuchPathException(sourceStation.getName(), targetStation.getName());
어떤 값이 와서 에러가 발생했는지 알기 쉬워졌네요 ! 👍🏻 👍🏻

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/PathController.java
> +    public ResponseEntity<PathResponse> showPath(final @Valid PathRequest pathRequest) {
객체고 묶어주셨군요 ! 👍🏻 👍🏻 
PathRequest 앞에는 어떤 Annotation이 생략되어있을까요?

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +    );
저는 보통 변수를 왼쪽에 놓고 사용해요..!

왼쪽에서 선언된 변수를 보고 age >= 6을 읽고 age < 13에서 머리속에서 자연스레 age를 생략하고 < 13을 읽는 방식으로 읽는게 자연스럽더라구요 😄
변수를 주로 왼쪽에 선언하는 방식으로 구현해서 익숙하더라구요 ㅎ_ㅎ..

라라가 익숙하신 방식으로 작성하시면 될 것 같아요 !

```suggestion
    BABY_POLICY(
            (fare) -> 0,
            (age) -> age >= 1  && age < 6
    ),
    KIDS_POLICY(
            (fare) -> (int) Math.ceil((fare - 350) * 0.5),
            (age) -> age >= 6  && age < 13
    ),
    TEENAGER_POLICY(
            (fare) -> (int) Math.ceil((fare - 350) * 0.8),
            (age) -> age >= 13 && age < 19
    ),
    ADULT_POLICY(
            (fare) -> fare,
            (age) -> age >= 19
    );
```

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +    ),
나이 정책이 변하는 경우와 요금 할인 정책이 변하는 경우 해당 객체가 변하지 않을까요?
둘을 분리해보는건 어떨까요?

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +                .orElseThrow();
어떤 에러가 발생하는지 작성해보는건 어떨까요?

2022-05-24 00:18 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +                .orElseThrow();
에러가 발생하는 테스트도 작성하는건 어떨까요?

2022-05-24 02:48 UTC, sure-why-not commented on src/main/java/wooteco/subway/ui/PathController.java
> +    public ResponseEntity<PathResponse> showPath(final @Valid PathRequest pathRequest) {
@ModelAttribe 어노테이션입니다!! 어노테이션이 없을 경우 @ModelAttribe 로 간주하기 때문에 생략했습니다! 생각해보니 명시적으로 작성하는 것이 좋을까요.,..?🤔🧐

2022-05-24 02:48 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/SubwayMap.java
> +            throw new NoSuchPathException(sourceStation.getName(), targetStation.getName());
좋은 피드백 주셔서 감사합니다!! 😆👍🏻 👍🏻👍🏻

2022-05-25 09:08 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +    );
변수를 왼쪽에 두니 age 가 1보다 작고 라고 매끄럽게 읽히는 것 같네요!! 😆👍🏻

2022-05-25 09:09 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +                .orElseThrow();
앗!! 이 부분을 빼먹었네요🥺 추가했습니다!!👍🏻

2022-05-25 09:11 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +                .orElseThrow();
이 부분이 원시값 int age 가 아닌 enum AgeType 으로 들어와서 해당하지 않는 경우가 없어서 테스트할 수가 없어졌어요...!!!😦
만약 테스트 가능한 상황이면 추가하도록 하겠습니다!! 감사합니다 👍🏻

2022-05-25 09:12 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +    ),
앗 그렇네요!! 나이별 할인 정책과 거리별 정책을 모두 분리하였습니다!!
감사합니다 👍🏻

2022-05-25 09:15 UTC, sure-why-not commented
미르 안녕하세요!!😆
피드백 주신 내용 반영했습니다!! 
일단 요금 관련 정책들을 분리하고, 나이별 정책은 전략패턴을 사용하여 적용했습니다!!
조금 시간이 모자라서 부족한 부분이 많은 것 같습니다.😭

일하느라 바쁘실텐데 1,2단계에서 유익한 피드백 주셔서 정말 감사했습니다! 😆👍🏻👍🏻

2022-05-25 14:51 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/PathController.java
> +    public ResponseEntity<PathResponse> showPath(final @Valid PathRequest pathRequest) {
그건 팀 컨벤션마다 다르겠지만, 저는 기본값은 작성하지 않는 방향을 선호하고 있어요 😎

2022-05-25 14:54 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/DiscountByAgePolicy.java
> +    );
엇.. 큰일이네요 🥺  age가 1보다 크다라고 읽혀야 하는데요..! ㅎㅎㅎㅎ 오타인걸로 알고 넘어갈게요 !

2022-05-25 15:14 UTC, ddu0422 requested changes
안녕하세요 라라 ! 미르예요 :)

피드백 반영 감사합니다 :) 잘 구현해주셨네요 ㅎ_ㅎ
간단한 코멘트 남겼으니 확인해주시면 감사하겠습니다 🙏🏻 

궁금한 점이 있다면 언제든디 코멘트 남겨주시거나 DM 주세요 😎

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Fare.java
> +        return new Fare((int) Math.ceil((value) * percent));
테스트 코드를 작성해보는건 어떨까요?

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Fare.java
> +                .applyDiscount(this);
훌륭하네요 ! 👍🏻 👍🏻

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/SubwayMap.java
> +                .orElseThrow();
여기도 어떤 에러가 발생했는지 알기 어렵지 않을까요?

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/age/AgeType.java
> +                .filter(it -> it.isType(age))
it 대신 ageType이나 type 등으로 변경해보는건 어떨까요?

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/age/AgeType.java
> +    public static AgeType from(final int age) {
예외 테스트도 작성해보는건 어떨까요?

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/age/BabyDiscountPolicy.java
> +        return new Fare(0);
fare에게 0원을 만드는 책임을 지니게 할 수 있지 않을까요?

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/age/FareByAgePolicy.java
> +                .filter(it -> it.ageType.equals(ageType))
현재는 발생할 수 없지만 ageType.equals(it.ageType)으로 작성하면 NPE가 발생할 수 있지 않을까요?
저는 그래서 보통 enum끼리 비교할 때는 ==을 선호하긴합니다!

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/age/KidsDiscountPolicy.java
> +        return fare.minus(350).discount(0.5);
매직넘버를 제거해보는건 어떨까요?

2022-05-25 15:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/dto/path/PathRequest.java
> +    private final Integer age;
만약 Client에서 source와 target만 요청하는 경우(1단계에서 구현한 API)가 있다면, 해당 내용을 추가할 때 어떤 상황이 벌어질까요?

2022-05-25 15:16 UTC, ddu0422 commented on src/main/java/wooteco/subway/dto/path/PathRequest.java
> +    private final Integer age;
@sure-why-not  우선 나머지는 간단하게 보고 넘어가보면 될 것 같고 해당 내용을 우선 순위 높여 확인해주시면 될 것 같아요 !

2022-05-26 08:25 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/age/FareByAgePolicy.java
> +                .filter(it -> it.ageType.equals(ageType))
앗 그렇네요!! enum 의 경우 == 로 비교하는 것이 null 로부터 안전해질 수 있겠네요!! 
습관적으로 객체는 equals 로 비교했는데,, 생각하지 못한 부분 피드백 주셔서 감사합니다😆 👍🏻

2022-05-26 08:28 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/age/BabyDiscountPolicy.java
> +        return new Fare(0);
앗 그렇네요!! 100퍼센트 할인하도록 Fare 에게 책임을 지니게 할 수 있겠네요!!
`fare.discount(100)` 와 같이 변경했습니다. 감사합니다 👍🏻👍🏻

2022-05-26 11:13 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/age/KidsDiscountPolicy.java
> +        return fare.minus(350).discount(0.5);
앗 그렇네요!! 
```
private static final int EXCLUDED_AMOUNT = 350;
private static final double DISCOUNT_PERCENT = 50;

```
와 같이 분리했더니 훨씬 가독성도 높아지네요. 감사합니다😀 👍🏻

2022-05-26 11:13 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/age/AgeType.java
> +    public static AgeType from(final int age) {
앗 추가했습니다 !! 🙄

2022-05-26 11:19 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/SubwayMap.java
> +                .orElseThrow();
앗 !! 🙄 꼼꼼하지 못했네요. ㅠㅠ AgeType , DistanceType 을 찾지 못하는 경우에도 예외메세지 작성했습니다!!

2022-05-26 11:20 UTC, sure-why-not commented on src/main/java/wooteco/subway/dto/path/PathRequest.java
> +    private final Integer age;
이 부분에 대해서는 디엠 드린 내용처럼 age 필드에 @NotNull을 추가하고, BAD_REQUEST 를 던지도록 수정했습니다!! 
다양한 생각을 해볼 수 있게 제안해주셔서 감사합니다😆👍🏻👍🏻👍🏻

2022-05-26 11:21 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Fare.java
> +        return new Fare((int) Math.ceil((value) * percent));
앗 너무 급하게 추가했네요.😭
add , minus , discount 에 대한 테스트를 추가했습니다!!

2022-05-28 05:49 UTC, ddu0422 approved these changes
안녕하세요 라라 ! 미르예요 :)

이번 미션 구현 잘해주시고 충분히 깊게 고민했다고 생각하여 머지할게요 !
간단한 코멘트 남겼으니 확인해주시면 감사하겠습니다 🙏🏻 

경로 조회 미션 고생하셨습니다 ! 마지막 미션도 화이팅이예요 🎆

2022-05-28 05:49 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Fare.java
> +        return new Fare((int) Math.ceil((value) * (100 - percent) / 100));
명확한 네이밍이 되었네요 👍🏻 👍🏻 

매직넘버를 제거해보는건 어떨까요?

2022-05-28 05:49 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/age/FareByAgePolicy.java
> +                .orElseThrow(() -> new IllegalInputException("해당하는 나이 타입을 찾을 수 없습니다."));
null을 넣는다면 에러 관련 테스트를 진행할 수 있지 않을까요??

2022-05-28 05:49 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/distance/DistanceType.java
> +                .orElseThrow(() -> new IllegalInputException("해당하는 거리 유형을 찾을 수 없습니다."));
에러 테스트도 작성해보면 어떨까요?

2022-05-28 05:49 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/distance/FareByDistancePolicy.java
> +    }
FareByAgePolicy처럼 구조를 변경해도 괜찮지 않을까요?

2022-05-28 05:49 UTC, merged