[Spring 경로 조회 - 2단계] 루나(남민정0) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #310
Opened 2022-05-24 02:53 UTC by RunaNam

안녕하세요 스티치! 😀

조금 늦은 것 같아서 일단 빠르게 구현하고 PR 드립니다..!
1단계때 리뷰 주신 내용 기반으로 `추가 운임` 및 `연령 별 운임 할인` 기능을 추가하였습니다.

리펙토링하면서 더 나은 코드로 바꿔보도록 하겠습니다! 

늘 바쁜데도 친절하게 리뷰주셔서 감사합니다 👍

2022-05-26 05:53 UTC, kang-hyungu requested changes
루나 몇 가지 피드백 남겼어요
수정해보시고 리뷰 재요청 주세요.
궁금한 점 생기면 코멘트 남기거나 오프라인으로 질문주세요.

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Fare.java
> +
1. Fare 클래스에서 FARE_DISTANCE_LIMIT_FIRST라는 상수를 처음 본 다른 개발자는 어떤 뜻인지 의미를 파악할 수 있을까요? 변수명을 봤을 때 어떤 값인지 쉽게 알 수 있는 적절한 이름을 붙여보세요
2. 새로운 요금체계가 추가되면 계속 상수가 늘어나겠네요. enum으로 관리할 방법 없을까요?

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Fare.java
> +        if (6 <= age && age < 13) {
마찬가지로 새로운 요금체계가 추가될 때마다 if 조건이 늘어나겠네요.
더 나은 방법 없을지 고민해보시기 바랍니다.

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Fare.java
> +    private static Fare getFare(int age, int fare) {
get이라는 메서드명이 적절한가요?
메서드명에 어떤 기능을 하는지 표현되지 않아 코드를 뜯어봐야 파악할 수 있네요

---

클린코드
p32
메서드 이름
... 접근자(Accessor), 변경자(Mutator), 조건자(Predicate)는 javabean 표준에 따라 값 앞에 get, set, is를 붙인다.

p49
서술적인 이름을 사용하라!
... 코드를 읽으면서 짐작했던 기능을 각 루틴이 그대로 수행한다면 깨끗한 코드라 불러도 되겠다.

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Fare.java
> +        if (age < 19) {
클린코드 386p
G25: 매직 숫자는 명명된 상수로 교체하라
아마 소프트웨어 개발에서 가장 오래된 규칙 중 하나라 여겨진다.
60년대 후반 COBOL, FORTRAN, PL/1 매뉴얼에서 읽었던 기억이 난다.
일반적으로 코드에서 숫자를 사용하지 말라는 규칙이다.
숫자는 명명된 상수 뒤로 숨기라는 의미다.

예를 들어, 86,400 이라는 숫자는 SECONDS_PER_DAY라는 상수 뒤로 숨긴다.
쪽 당 55줄을 인쇄한다면 숫자 55는 LINES_PER_PAGE 상수 뒤로 숨긴다.

어떤 상수는 이해하기 쉬우므로, 코드 자체가 자명하다면, 상수 뒤로 숨길 필요가 없다.
...

클린코드 p387
'매직 숫자'라는 용어는 단지 숫자만 의미하지 않는다.
의미가 분명하지 않은 토큰을 모두 가리킨다. 예를 들어,

```java
assertEquals(7777, employee.find("John Doe").employeeNumber());
```

위 assert 코드에서 매직 숫자는 두 개다. 하나는 7777이고, 다른 하나는 "John Doe"이다.
둘 다 의미가 분명하지 않다.

실제로 "John Doe"는 직원 #7777의 이름이다.
우리 팀이 만든 테스트 데이터베이스를 위해 자주 사용하는 예제다.
우리 팀은 테스트 데이터베이스에 모두가 잘 아는 값과 속성을 넣어둔다.
그래서 테스트 데이터베이스에 연결하면 어떤 정보가 있으리라는 사실을 팀원 모두가 알고 있다.
우리 테스트 데이터베이스에서 "John Doe"는 시급 직원이다.
따라서 위 코드는 다음과 같이 해석된다.

```java
assertEquals(
    HOURLY_EMPLOYEE_ID,
    Employee.find(HOURLY_EMPLOYEE_NAME).employeeNumber());
);
```

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Path.java
>  public class Path {
클래스명이 적합한가요?
이 클래스가 맡은 책임이 경로라는 이름으로 표현이 될까요?
경로와 관련된 모든 처리를 맡고 있지 않은 것 같은데 더 나은 이름을 찾아보시기 바랍니다.

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Path.java
> +    public List<Station> getStations(Station upStation, Station downStation) {
메서드명에 getter가 아니면 get을 붙이지 마세요.
어떤 기능을 하는 메서드인지 메서드명에 표현해주세요

현재 클래스의 모든 메서드를 점검해보시기 바랍니다.

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/service/PathService.java
>      private Path getPath() {
PathService에서 이 메서드를 제거해보시기 바랍니다.
Path 객체를 생성하는데 필요한 값만 db조회해서 생성자에게 전달하고 나머지 처리는 Path 객체 내부에서 처리하시기 바랍니다.

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/service/PathService.java
>      private void addAllSections(Path graph) {
이 메서드도 db 조회하는 부분만 잘 처리하면 Path 클래스 내부로 옮길 수 있겠네요

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/service/PathService.java
> +                .map(lineId -> lineDao.findById(lineId)
stream 안의 stream이네요
2중 for문과 비슷해보이네요
메서드 추출로 코드 복잡도를 낮춰보세요.

그리고 잘 뜯어보니 필요한 line 아이디만 db 조회해서 요금 계산의 책임을 갖는 객체에게 계산을 맡길 수 있겠네요.
메서드명에서 get도 제거하시고 조회와 요금계산을 적절한 객체로 옮겨보시기 바랍니다.

2022-05-26 05:53 UTC, kang-hyungu commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +    private final LineRequest 수인분당선2 =
클린코드 25p

의미 있게 구분하라
컴파일러나 인터프리터만 통과하려는 생각으로 코드를 구현하는 프로그래머는 스스로 문제를 일으킨다.
예를 들어, 동일한 범위 안에서는 다른 두 개념에 같은 이름을 사용하지 못한다.
그래서 프로그래머가 한쪽 이름을 마음대로 바꾸고픈 유혹에 빠진다.
어떤 프로그래머는 철자를 살짝 바꿨다가 나중에 철자 오류를 고치는 순간 컴파일이 불가능한 상황에 빠진다.(예를 들면 변수명을 klass로 짓는 경우)
컴파일러를 통과할지라도 연속된 숫자를 덧붙이거나 불용어(noise word)를 추가하는 방식은 적절하지 못하다.
이름이 달라야 한다면 의미도 달라져야 한다.
연속적인 숫자를 덧붙인 이름(a1, a2, ... aN)은 의도적인 이름과 정반대다.
이런 이름은 그릇된 정보를 제공하는 이름도 아니며, 아무런 정보를 제공하지 못하는 이름일 뿐이다.
저자 의도가 전혀 드러나지 않는다.
다음 코드를 살펴보자.

```java
public static void copyChars(char a1[], char a2[]) {
    for (int i = 0; i < a.length; i++) {
        a2[i] = a1[i];
    }
```
함수 인수 이름으로 source와 destination을 사용한다면 코드 읽기가 훨씬 더 쉬워진다.

불용어를 추가한 이름 역시 아무런 정보도 제공하지 못한다.
Product라는 클래스가 있다고 가정하자.
다른 클래스를 ProductInfo 혹은 ProductData라 부른다면 개념을 구분하지 않은 채 이름만 달리한 경우다.
Info나 Data는 a, an, the와 마찬가지로 의미가 불분명한 불용어다.
a나 the와 같은 접두어를 사용하지 말라는 소리가 아니다.
의미가 분명히 다르다면 사용해도 무방하다. 예를 들어, 모든 지역 변수는 a를 사용하고 모든 함수 인수는 the를 사용해도 되겠다.
요지는 zork라는 변수가 있다는 이유만으로 theZork라 이름 지어서는 안 된다는 말이다.

2022-05-26 05:53 UTC, kang-hyungu commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +            = new PathService(StationDaoImpl.getInstance(), SectionDaoImpl.getInstance(), LineDaoImpl.getInstance());
StationDaoImpl
Impl을 붙이는게 적절한 클래스명일까요?

2022-05-26 05:53 UTC, kang-hyungu commented on src/main/java/wooteco/subway/service/PathService.java
> +    public PathResponse findShortestPath(Long upStationId, Long downStationId, int age) {
메서드가 10줄이 넘지 않도록 개선해보시기 바랍니다.

2022-05-26 08:31 UTC, RunaNam commented on src/main/java/wooteco/subway/domain/Fare.java
> +
아래에서 말씀해주신 연령별 요금체계와 동일하게 `Enum`으로 관리하는 것이 더 나은 방식일 것 같습니다.

2022-05-26 08:32 UTC, RunaNam commented on src/main/java/wooteco/subway/domain/Fare.java
> +    private static Fare getFare(int age, int fare) {
평소에 get~ 형태의 메서드를 종종 썼었는데 말씀해주신 내용들을 참고해보니 get보다는 더 서술적인 이름을 쓰는 편이 이해하기 좋겠네요. 감사합니다! 👍

2022-05-26 08:33 UTC, RunaNam commented on src/main/java/wooteco/subway/domain/Fare.java
> +        if (age < 19) {
Enum으로 분리하면서 매직넘버나 상수와 관련된 부분의 문제들이 많이 해결되는 것 같습니다. 감사합니다. :)

2022-05-26 08:34 UTC, RunaNam commented on src/main/java/wooteco/subway/domain/Path.java
>  public class Path {
경로와 관련된 모든 처리를 맡지 않는다는 말씀은 무엇일까요...? 일단 수정 과정에서 기존에 PathService에 분산되어있던 부분을 마저 Path로 가져와 수정하였습니다. 클래스명의 경우에는 더 고민해보도록 하겠습니다. 감사합니다!

2022-05-26 08:34 UTC, RunaNam commented on src/main/java/wooteco/subway/domain/Path.java
> +    public List<Station> getStations(Station upStation, Station downStation) {
앞서 말씀해주신 내용과 동일하게, get과 관련된 메서드들을 수정하였습니다. 감사합니다!

2022-05-26 08:35 UTC, RunaNam commented on src/main/java/wooteco/subway/service/PathService.java
> +    public PathResponse findShortestPath(Long upStationId, Long downStationId, int age) {
적다보니 메서드 길이가 넘었었네요 😂 수정하겠습니다...!

2022-05-26 08:36 UTC, RunaNam commented on src/test/java/wooteco/subway/service/PathServiceTest.java
> +            = new PathService(StationDaoImpl.getInstance(), SectionDaoImpl.getInstance(), LineDaoImpl.getInstance());
해당 부분은 테스트에서 사용하는 FakeDao이므로 FakeStationDao 와 같은 방식으로 네이밍 수정하도록 하겠습니다.

2022-05-26 08:39 UTC, RunaNam commented on src/main/java/wooteco/subway/service/PathService.java
>      private Path getPath() {
Dao에 접근해야 하는 부분들이 필요해서 부득이하게 메서드를 나눴던 부분인데요, Id 값을 넣는 방식으로 수정하여 Path 객체 생성 시 전달하는 값을 수정하도록 하겠습니다. 
이후, id값에서 객체값을 가져오는 로직 (ex. `findPassedLines`) 들이 추가하였습니다.

2022-05-26 08:39 UTC, RunaNam commented on src/main/java/wooteco/subway/service/PathService.java
>      private void addAllSections(Path graph) {
위의 내용과 같이, DB에서 가져온 id값들을 바로 보내는 방식으로 수정하였습니다 :)

2022-05-26 14:03 UTC, RunaNam commented on src/main/java/wooteco/subway/service/PathService.java
> +                .map(lineId -> lineDao.findById(lineId)
where in을 활용해 id만으로 DB 조회하여 extraFare만 가져오도록 수정하였습니다! 요금 계산의 책임 역시 fare에 있는 것이 올바른 방향이라고 생각되어 fare에서 계산하도록 수정하였습니다.

2022-05-26 14:04 UTC, RunaNam commented on src/test/java/wooteco/subway/acceptance/PathAcceptanceTest.java
> +    private final LineRequest 수인분당선2 =
테스트코드 수정 중 다 수정되지 않았던게 있었나보네요..! 변수명에 앞으로 더 신경써서 작성하겠습니다. 감사합니다!

2022-05-26 15:03 UTC, RunaNam commented
안녕하세요 구구! 
리뷰 주신 내용 기반으로 고민하면서 수정해보았습니다...!
시간 내주셔서 꼼꼼하게 리뷰 남겨주셔서 정말 감사합니다! 

각 리뷰에 대한 내용은 댓글에 달아놓았습니다.
변수명이나 메서드 명을 더 꼼꼼히 고민해봐야 된다는 것을 한번 더 생각해보게 된 것 같네요!
매번 감사합니다. 🙇‍♀️🙇‍♀️

2022-05-27 07:10 UTC, kang-hyungu requested changes
루나 몇 가지 코멘트 남겼는데요
깃헙에 코드가 안나와서 추가 피드백은 오프라인으로 말씀드릴게요

2022-05-27 07:10 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/DistanceFare.java
> +    MIDDLE_DISTANCE(1250,11, 5, 100),
```suggestion
    MIDDLE_DISTANCE(1250, 11, 5, 100),
```

2022-05-27 07:10 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/DistanceFare.java
> +    BASIC_DISTANCE(1250,1, 1, 0)
```suggestion
    BASIC_DISTANCE(1250, 1, 1, 0)
```

2022-05-27 07:10 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Path.java
> +            graph.addEdge(section.getUpStationId(), section.getDownStationId(),
객체 생성은 변수로 따로 분리해주는게 코드 읽기에 더 좋지 않을까요

```suggestion
            final var shortestPathEdge = new ShortestPathEdge(section.getLineId(), section.getDistance());
            graph.addEdge(section.getUpStationId(), section.getDownStationId(), shortestPathEdge);
```

2022-05-27 07:10 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Path.java
>  public class Path {
이 클래스가 실제 하는 일은 최단경로를 찾는 일입니다.
최장, 중간 경로 등등 모든 경로를 처리하는게 아닌데 Path라고 정하면 의도를 알기가 어렵겠죠

2022-06-02 08:51 UTC, RunaNam commented
안녕하세요 구구!
리뷰 요청이 늦어져 정말 죄송합니다 🙇‍♀️🙇‍♀️🙇‍♀️
말씀해주신 테스트 관련 내용 및 id를 객체로 수정하는 과정을 진행하였습니다. 

수정 과정에서 페어 코드가 아닌 제 코드로 다시 수정하여서 코드의 수저이 다소 많습니다. 
매번 꼼꼼하게 피드백 주셔서 정말 감사합니다. 👍

2022-06-07 01:27 UTC, kang-hyungu approved these changes
루나 피드백 반영 잘 해주셨어요
pr은 머지 처리할게요. 추가로 남긴 코멘트는 참고만 하세요.
수고하셨어요

2022-06-07 01:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        final String sql = "SELECT * FROM LINE WHERE id = ?";
[SELECT * 쓰지 말자](https://hyewoncc.github.io/2022/05/25/sql-no-wildcard.html)

2022-06-07 01:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/service/LineService.java
> +        checkDuplicateName(lineDao.isExistName(name));
```suggestion
        checkDuplicateName(lineDao.existName(name));
```

2022-06-07 01:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Sections.java
> +        LinkedList<Station> result = new LinkedList<>();
```suggestion
        List<Station> result = new LinkedList<>();
```

2022-06-07 01:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Sections.java
> +        Station station = value.get(0).getUpStation();
객체지향 생활체조
한 줄에 한 점만 찍는다.

2022-06-07 01:27 UTC, merged