[Spring 경로 조회 - 2단계] 범고래(조충범) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #314
Opened 2022-05-24 08:26 UTC by cndqjacndqja

안녕하세요 에단! 범고래입니다 😊 
2단계 리뷰 요청 드립니다~!
1단계 때 꼼꼼한 리뷰 정말 감사드립니다.. 생각해 보지 못했던 부분들도 많이 생각해 볼 수 있었습니다 :)
구현하는데에는 오래 걸리진 않았지만, 기존에 변경하고 싶었던 구조를 변경하느라 시간이 좀 오래 걸렸네요

변경사항은 다음과 같습니다.
- Service에 도메인과 관련된 비즈니스 로직을 최대한 줄이고 싶어서 기존의 로직을 Sections로 이동시켰습니다.
- Section에 LineId가 아닌 Line으로 변경했는데요. 이때 기존의 Dao에서 외래키로 접근해서 Line을 만들지 아니면 Repository를 만들어서 각 Dao에 요청하여 만들지 고민하다가 후자를 선택했습니다.(처음에는 외래키를 사용해서 구현했었는데요! 아직 외래키를 언제써야하고 그에 따른 장단점이 무엇인지.. 적용해 봐도 와닿지 않더라구요 ㅠㅠ 그래서 다시 후자의 방식으로 바꾸었습니다.)

그리고 이전에 질문 주셨던 코멘트에 대해서도 생각해 보았는데요.
이전에 제가 말씀드렸던 상황이 구체적이지 않고, 제가 봐도 전달력이 부족했던 것 같아서 노션에 따로 정리했습니다.
아마 잘못 생각한 부분들도 있을 것 같은데, 시간이 되신다면.. 이 부분도(잘못 생각한 부분이 없는지) 피드백 주신다면 정말 감사합니다🥹
[피드백](https://github.com/woowacourse/atdd-subway-path/pull/193#discussion_r878696245)
[노션 링크](https://sage-collar-475.notion.site/DTO-ad0e97097c494d698d41de9fd6f319c2)

2022-05-24 12:38 UTC, Laterality requested changes
안녕하세요 범고래.

잘 구현해주셨어요 👍 

간단한 코멘트 남겨드렸으니 확인 부탁드려요.

## Q&A

노션에 남겨주신 질문에 의견 드리면, 두 번째 케이스에서 아래와 같이 설명하셨네요.

> 여기서도 똑같이 Line에 extraFare가 추가된 상황을 보겠습니다.
>
> 이럴 경우, Service 계층에서만 변경이 일어나게 됩니다. Controller는 Service DTO를 그대로 반환하고 있으니까요!

이는 다르게 생각하면, **컨트롤러에 아무런 변경이 없었음에도 불구하고 뷰까지 변경사항이 전파**된 것으로 봐야 하지 않을까요?

다른 예시로, 서비스의 DTO가 이미 존재하는 필드명을 바꾸는 경우에도 마찬가지로 뷰에서는 아무런 변경이 없었음에도 불구하고 변경된 필드명으로 응답하게 될 텐데요.

서비스(MVC의 모델 영역이겠네요)의 변경으로 인한 영향이 그대로 컨트롤러의 응답을 따라 뷰에 전파되는 것을 바람직한 변경으로 볼 수 있을까요?

2022-05-24 12:38 UTC, Laterality commented on src/main/java/wooteco/subway/domain/DiscountFactory.java
> +    CHILD(new ChildrenDiscountPolicy(), (age) -> age >= 6 && age < 13),
"`CHILD`는 `DiscountFactory`의 인스턴스이다"라는 문장은 자연스러운가요?

2022-05-24 12:38 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private void validateUpdateDistance(Section section, Section insertSection) {
이름이 다소 추상적이네요. 무엇을 검증하는지를 나타내면 어떨까요?

2022-05-24 12:38 UTC, Laterality commented on src/main/java/wooteco/subway/domain/farediscount/SpecialDiscountPolicy.java
> +public class SpecialDiscountPolicy extends AgeDiscountPolicy {
무임승차라면 Special보다는 Free나 FreeRide 같은 용어는 어떨까요?

2022-05-24 12:38 UTC, Laterality commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +
빈 줄은 하나만 넣어주세요.

2022-05-24 12:38 UTC, Laterality commented on src/main/java/wooteco/subway/domain/farediscount/TeenagerDiscountPolicy.java
> +        int i = percentageCalculate(price);
의미있는 변수명을 사용하면 어떨까요?

2022-05-24 12:38 UTC, Laterality commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        LineRequest lineRequest = new LineRequest("3호선", "bg-orange-600", station1, station2, 4, 0);
여러 테스트에 비슷한 코드가 등장하네요. 중복을 제거할 수 있을까요?

2022-05-25 04:17 UTC, cndqjacndqja commented on src/main/java/wooteco/subway/domain/DiscountFactory.java
> +    CHILD(new ChildrenDiscountPolicy(), (age) -> age >= 6 && age < 13),
"CHILD_DISCOUNT는 DiscountType이다"라는 문장을 생각해서 변경해 보았습니다!

2022-05-25 04:30 UTC, cndqjacndqja commented
안녕하세요 에단!
빠른 피드백 감사드립니다~ :)
피드백 반영해서 다시 리뷰 요청 드립니다~!

### Q&A 답변

`서비스(MVC의 모델 영역이겠네요)의 변경으로 인한 영향이 그대로 컨트롤러의 응답을 따라 뷰에 전파되는 것을 바람직한 변경으로 볼 수 있을까요?`

네 저도 바람직한 변경은 아니라고 생각합니다! (이 부분이 제가 단점으로 생각했던 Controller가 Service계층의 DTO까지 신경써야 한다는 점과 같은 부분이라 생각했습니다.) 정답이 없는 부분이라고 생각하지만, 
다른 방안들에 대한 각각의 장단점을 생각해 보았을 때, 현재의 방식을 선택했습니다!

정답이 없다는 것은 느껴지지만, 혹시 에단이라면 어떤 방식을 생각하셨을지 궁금합니다😊

2022-05-25 12:15 UTC, Laterality approved these changes
안녕하세요 범고래.

피드백 빠르게 반영해주셨네요 👍 

이번 미션은 이만 머지하도록 하겠습니다.

복잡한 요구사항이었는데 잘 구현해주셨어요. 

고생 많으셨습니다. 다음 미션도 화이팅하세요!

 ## Q&A

서비스는 뷰의 관심사를 반영하는 계층이 아니기 때문에 뷰의 요구사항을 모두 수용하기는 어려워요. 여러 컨트롤러가, 심지어 같은 도메인을 다루는 버전만 다른 두 컨트롤러가 같은 서비스에 의존하면서 서로 응답 형식이 다르기도 하니까요.

```
/**
 * [LineService]는 어느 컨트롤러의 요구사항에 반환 DTO를 맞춰야 할까?
 * [findAllV1], [findAllV2]처럼 메서드를 나누거나 [LineV1Service], [LineV2Service]처럼 서비스도 버전을 나눠야 할까?
 * 응답 형식만 다르고 기능이 동일하다면 중복이 아닐까?
 */
LineV1Controller \
                   -> LineService -> ...
LineV2Controller /
```

2022-05-25 12:15 UTC, Laterality commented on src/main/java/wooteco/subway/domain/DiscountFactory.java
> +    CHILD(new ChildrenDiscountPolicy(), (age) -> age >= 6 && age < 13),
나이에 관한 할인 유형만 갖는다면 `AgeDiscountType` 같은 이름도 괜찮겠네요!

2022-05-25 12:15 UTC, Laterality commented on src/main/java/wooteco/subway/domain/Sections.java
> +        Long downStationId = findDownTerminalStationId();
`Long` 타입으로 변경된 이유가 있을까요?

2022-05-25 12:15 UTC, merged