[Spring 경로 조회 - 2단계] 주디(윤주리) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #321
Opened 2022-05-24 17:24 UTC by jurlring

코니 안녕하세요 주디입니당 😸
제가 리뷰 요청이 너무 늦었네요 ㅠ.ㅠ 죄송합니당

이번 미션에서는 기능 요구사항 구현 및 serviceTest 방식 변경(Fake -> test db사용)과 설계 부분에서 머리를 굴려본 것 같은데.. 썩 마음에 들지는 않네용 ㅠㅅ ㅠ

service test 방식을 변경한 이유는 다음과 같습니다.

service test에서 제가 중요하다고 생각하는 부분은 3가지입니다.
1. 서비스 객체에 대한 비지니스 로직 검증
2. 서비스 객체에 의존성이 주입되는 객체에서 변경이 일어난 경우, test 변경을 최소화
3. 실제 서비스와 비슷한 환경에서의 신뢰성

그리고 제가 생각하기에 service를 테스트 하는 방법은 총 3가지인데요.
각각의 장점과 단점을 고려하여 service test방법을 변경하였습니다.

1. Mock 이용 
단점 
의존성 주입 객체의 변경을 test에서 직접 수정해야함 → 까먹을 가능성 다수..
test에서 의존성을 주입 받는 객체의 행위가 코드로 드러남

장점
가장 격리된 상황에서 service 를 test함

2. Fake 객체 이용 
단점
의존성 주입 객체의 변경을 test dao에서 직접 수정해야함 → 따로 로직을 구현해야함

장점
의존성 주입 객체 편리하게 변경 가능

3. test DB이용 
단점
service 자체를 격리하여 test하지 못함

장점
의존성 주입을 이용
프로덕션 코드를 사용하므로 셋 중에 변경이 적음
실제 dao로직을 사용하므로 더 신뢰성이 있음

실제 db에 가깝게 ⇒ 실제 dao에 가깝게 구현하는 것이 service test에 적합하다고 생각

그런데, 이렇게 구현할 경우 LineService를 test한다고 했을 때, station의 저장이 수반되어야 하는데 이 부분을 어떻게 하면 깔끔하게 처리될지 모르겠습니다!
현재는 sql파일을 이용하여 사용하고 있는데 가독성 측면에서 단점이 있다고 생각됩니다.
코니는 어떻게 생각하시나요?!

설계과정에서도 궁금한 점이 있는데 코드에 리뷰를 달아서 질문 드릴게요!! ❤️‍🔥 

바쁘신 와중에 제 코드 리뷰를 해주셔서 감사해요 🐈 
나중에 척척학사 개발자가 되어서 24배로 갚겠습니다!

2022-05-24 18:07 UTC, jurlring commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +public class PathFinder {
service에 비지니스 로직을 줄이는 것이 가독성이 좋다고 판단됐고, path를 찾는 책임을 가지는 객체가 있어도 되겠다는 생각이 들어서 PathFinder라는 객체를 만들었어요.

이렇게 설계를 했을 때, 추후에 생길 문제점이 있을까요?

2022-05-25 13:22 UTC, choihz requested changes
안녕하세요, 주디!

2단계 구현해 주신 부분을 확인하고 피드백을 남겨 두었습니다. 궁금한 점 또는 의견이 있으실 땐 편히 코멘트 또는 DM 주세요~

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/ui/ControllerAdvice.java
> +        exception.printStackTrace();
> `e.printStackTrace()` 메소드를 호출하면 서버에서 스택 정보를 취합하여야 하기 때문에 서버에 많은 부하가 발생하게 된다. 만약 여러분의 어플리케이션이 복잡하게 구성되어 있다면, 최대 100개의 스택 정보가 프린트 되기 위해서 서버에 부하를 줄 것이다. ([[Book] 자바 성능을 결정짓는 코딩 습관과 튜닝 이야기](https://time8292.tistory.com/11))

로그에 대해 학습하고 적용해 보아도 좋을 것 같아요~

2022-05-25 13:22 UTC, choihz commented on src/test/java/wooteco/subway/domain/fare/FareByAgeTest.java
> +}
<img width="420" alt="스크린샷 2022-05-13 오전 3 03 28" src="https://user-images.githubusercontent.com/18049492/170255764-7d797b61-e955-4f3e-9057-f778d37ca519.png">

이 설정을 켜는 건 어떨까요? 무엇을 위한 것일까요?

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/graph/SubwayGraph.java
> +            subwayGraph.addEdge(upStation, downStation, edge);
5fc6e23c 커밋을 비롯하여 적지 않은 커밋들이 메시지와 관련 없는 작업을 다수 포함하고 있는 것 같아요. 커밋에도 조금 더 신경 써 보아요~

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/fare/FareByAge.java
> +    ADULT(age -> age > 18 && age < 65, fare -> fare);
람다식이 붙어 있어서 읽고 파악하기가 쉽지 않은 것 같아요 😓

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/fare/FareByAge.java
> +    TEENAGER(age -> age > 12 && age < 19, fare -> (int) ((fare - 350) * 0.8)),
나이 관련 조건식에서의 숫자는 맥락을 보고 이해할 수 있지만, `350`, `0.5`, `0.8` 같은 숫자는 어떤가요?

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/fare/FareByAge.java
> +    public static int findFare(final int age, final int fare) {
요금을 찾는다기보다는 계산하고 있는 것 같아요.

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/exception/NotLinkPathException.java
> +public class NotLinkPathException extends ClientException {
`ClientException`은 너무 추상적인 이름을 갖고 있는 것 같아요. 또한, 이렇게 예외의 계층 구조를 설계했다면 `@ExceptionHandler`와 함께 이것을 좀 더 활용할 수도 있어 보이네요!

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/graph/ShortestPathEdge.java
> +    public ShortestPathEdge(final Long lineId, final int distance) {
`final`을 붙이는 작업을 해 주셨는데요, 어떤가요? 장점을 느끼셨나요?

2022-05-25 13:22 UTC, choihz commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +        stations.forEach(station -> System.out.println(station.getId()));
😮

2022-05-25 13:22 UTC, choihz commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    private final static int EXTRA_FARE = 0;
상수화하신 이유가 무엇일까요?

2022-05-25 13:22 UTC, choihz commented on src/test/java/wooteco/subway/domain/fare/FareByDistanceTest.java
> +    @DisplayName("SECOND_EXTRA_FARE distance 일 때, 최종 요금을 계산한다.")
`SECOND_EXTRA_FARE` 같은 용어를 테스트 이름에서 사용한다면, 테스트의 맥락을 정확히 파악하기 위해서는 반드시 코드까지 찾아봐야 할 것 같은데요, 주디의 생각은 어때요?

2022-05-25 13:22 UTC, choihz commented on src/test/java/wooteco/subway/domain/fare/FareByAgeTest.java
> +    @DisplayName("FREE_AGE age 의 최종 요금을 계산한다.")
요금 계산은 우리 애플리케이션에서 중요한 로직인데요, 지금은 단편적으로 거리에 의한 요금이나 나이에 의한 요금 등 하나의 조건만 확인하거나, `PathFinderTest`에서처럼 다른 것과 합쳐 너무 큰 범위를 테스트하고 있는 것 같아요. 그러다 보니 다양한 테스트 케이스로 확인하기도 어렵고요.

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/service/PathService.java
> +        GraphPath<Station, ShortestPathEdge> graph = findGraph(source, target);
그래프를 "찾는다"는 표현이 적절한지 고민이 되네요 🤔

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/path/PathFinder.java
> +    }
> service에 비지니스 로직을 줄이는 것이 가독성이 좋다고 판단됐고, path를 찾는 책임을 가지는 객체가 있어도 되겠다는 생각이 들어서 PathFinder라는 객체를 만들었어요.
> 
> 이렇게 설계를 했을 때, 추후에 생길 문제점이 있을까요?

추후에 생길 문제라는 것은 잘 모르겠지만, 이 구현을 보고 의문이 드는 부분은 조금 있는 것 같아요.
1. `Path`는 길, 경로라는 의미의 단어인데 `fare`까지 알고 있는 것이 맞을까?
2. `PathFinder`는 이름만 봐서는 경로를 계산하여 찾는 역할을 할 것으로 예상되는데, 실제로 그런가?

2022-05-25 13:22 UTC, choihz commented on src/test/java/wooteco/subway/domain/path/PathFinderTest.java
> +                () -> assertThat(path.getStations().size()).isEqualTo(4));
최단 경로를 검증하는데 최종 거리와 역의 개수만 확인하는 것으로 충분할까요?

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/graph/SubwayGraph.java
> +        GraphPath<Station, ShortestPathEdge> path = pathFinder.getPath(source, target);
구간으로 연결되어 있지 않은 역으로 최단 경로를 구하려 할 때 어떤 일이 일어나고 있나요?

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/line/Lines.java
> +                .orElseThrow(() -> new LineNotFoundException("Line이 존재하지 않습니다."));
출발지와 도착지를 같게 입력했을 때 어떻게 되나요?

2022-05-25 13:22 UTC, choihz commented on src/main/java/wooteco/subway/domain/fare/FareByAge.java
> +                .orElseThrow(() -> new PositiveDigitException("나이는 음수일 수 없습니다."))
실제로 나이에 음수를 입력했을 때 이 예외가 발생하고 있나요? 또한, 나이는 음수만 아니면 되나요?

2022-05-26 01:41 UTC, jurlring commented on src/test/java/wooteco/subway/domain/fare/FareByAgeTest.java
> +}
파일 끝에 자동으로 개행을 추가하기 위해 켜는 옵션이군용!!!
코니 덕에 이런게 있는줄 알았네요 😭 
깜빡하던 부분이였는데, 알려주셔서 감사합니다!

2022-05-26 06:22 UTC, jurlring commented on src/main/java/wooteco/subway/domain/fare/FareByAge.java
> +    TEENAGER(age -> age > 12 && age < 19, fare -> (int) ((fare - 350) * 0.8)),
매직 넘버네요 😢 
수정하겠습니다.

2022-05-26 06:23 UTC, jurlring commented on src/main/java/wooteco/subway/domain/fare/FareByAge.java
> +    ADULT(age -> age > 18 && age < 65, fare -> fare);
메서드로 분리하는게 더 가독성이 있을 것 같네요!

2022-05-26 07:11 UTC, jurlring commented on src/main/java/wooteco/subway/domain/graph/ShortestPathEdge.java
> +    public ShortestPathEdge(final Long lineId, final int distance) {
해당 파라미터에 변경을 가해선 안된다는 것을 명시 + 강제 한다고 생각해서 사용했어요.
해당 변수가 불변해야 한다는 것을 파악하는데 도움이 된 것 같습니당

2022-05-26 08:09 UTC, jurlring commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    private final static int EXTRA_FARE = 0;
거리나 추가요금에 관한 부분은 다른 곳에서 검증하므로 항상 같은 값이 들어가서 상수화 해뒀었는데, 테스트를 추가하면서, 빠진 부분이 많네요 😿 
추가하겠습니당

2022-05-26 08:21 UTC, jurlring commented on src/main/java/wooteco/subway/service/PathService.java
> +        GraphPath<Station, ShortestPathEdge> graph = findGraph(source, target);
GraphPath를 PathFinder의 상태로 수정하고, findGraph을 init으로 수정했습니당!

2022-05-26 08:27 UTC, jurlring commented on src/test/java/wooteco/subway/domain/fare/FareByDistanceTest.java
> +    @DisplayName("SECOND_EXTRA_FARE distance 일 때, 최종 요금을 계산한다.")
앗 그렇네요.
저만 보는 테스트가 아니라는 것을 명심하겠습니당 🐰

2022-05-26 15:11 UTC, jurlring commented on src/main/java/wooteco/subway/domain/graph/SubwayGraph.java
> +        GraphPath<Station, ShortestPathEdge> path = pathFinder.getPath(source, target);
exception을 발생시키도록 하였습니다!

2022-05-26 15:24 UTC, jurlring commented on src/test/java/wooteco/subway/domain/path/PathFinderTest.java
> +                () -> assertThat(path.getStations().size()).isEqualTo(4));
어떤 역인지 확인하는 부분이 있으면 좋을 것 같네요 :)

2022-05-28 15:19 UTC, choihz approved these changes
안녕하세요, 주디!

마지막까지 피드백 반영해 주신 부분을 확인하고 몇 가지 코멘트를 더 남겨 두었습니다. 이제 이번 미션은 마무리해도 될 것 같아요.

그동안 정말 고생 많으셨고, 다음에 다시 만나요~ 👋

2022-05-28 15:19 UTC, choihz commented on README.md
> +- [x] PathFinder test 검증부 station 모두 검증하도록 수정
😍

2022-05-28 15:19 UTC, choihz commented on src/main/java/wooteco/subway/ui/ControllerAdvice.java
>      }
이 두 메서드의 형식을 맞춰 주시면 좋을 것 같아요~ (애너테이션)

2022-05-28 15:19 UTC, choihz commented on src/main/java/wooteco/subway/domain/fare/FareCalculator.java
> +    }
`FareCalculator`는 왜 `lineIds`를 인스턴스 변수로 갖게 되었을까요? `age`, `distance`, `lines`와 `lineIds`에는 어떤 차이가 있었던 걸까요?

2022-05-28 15:19 UTC, choihz commented on src/test/java/wooteco/subway/domain/fare/FareCalculatorTest.java
> +                        new Line(3L, "", "", 0)));
테스트 코드이고 여기 들어가는 데이터가 의미 없는 상황이긴 하지만, 그래도 웬만하면 데이터를 잘 채워 주도록 하죠 😉

2022-05-28 15:19 UTC, choihz commented on src/test/java/wooteco/subway/domain/path/PathFinderTest.java
> +                new Line(4L, "4호선", "black", 0)));
불필요한 코드가 남아 있네요.

2022-05-28 15:19 UTC, choihz commented on src/test/java/wooteco/subway/domain/path/PathFinderTest.java
> +                )));
가독성을 조금 더 개선할 수 있는 방법은 없는지 찾아 보아도 좋을 것 같아요.

2022-05-28 15:19 UTC, merged