[Spring 경로 조회 - 2단계] 토닉(최우석) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #322
Opened 2022-05-24 18:09 UTC by tonic523

안녕하세요 미르!
2단계 미션 피드백도 잘 부탁드립니다 ㅎㅎ
리팩토링할 부분은 많지만 곧 미션 마감이라 구현을 마치고 PR 올리는 점 양해부탁드립니다 ㅠㅠ
추가 요구사항을 구현하면서 느낀점과 제가 리팩토링해야겠다고 생각되는 부분을 작성해놓겠습니다.
---
> 역할을 중심으로 분리된 객체

이번 요구사항에서는 Line에 추가 요금이라는 필드가 추가되었습니다. 이 과정에서 기존에 노선에 구간을 관리하는 책임을 가지는 Line에 필드를 추가해야겠다고 생각했습니다. 이렇게 구현하다보니 레벨1 때 배웠던 객체지향적인 설계가 아닌 Line의 내부 데이터를 중심으로 역할을 부여하게 되서 하나의 객체가 여러 역할을 가지는 형태로 구현하게 되었어요.
- Line은 자신이 가지는 구간들을 관리한다.
- Line은 추가 요금이라는 데이터를 가지고 있다.
사실 Line은 이 추가 요금에 대한 것으로 어떤 비즈니스 로직을 수행하지 않기 때문에 객체지향적인 관점에서 이 데이터는 Line이 가질 필요가 없다고 생각합니다. 추가 요금이라는 데이터는 경로를 계산해주는 객체에게 필요하기 때문에 Line과는 별개로 따로 요금과 노선도의 데이터를 가지는 객체를 만들어볼 예정이에요!

> 1. Line이 Sections 가지기 vs 2. Section이 Line 가지기

사실 위 처럼 고민한건 `1번`으로 구현했기 때문입니다. 만약 후자로 구현되었다면 앞서 말한 고민을 하지 않고 그냥 Sections로 경로를 계산해주었을 것 같아요. 이번 미션에서는 `1번`의 설계로 하니 구현하기 힘들다는 것을 경험했습니다. 이번 요구사항에서만 그럴 뿐이지 무조건 `2번`이 좋은 방법이다! 라고 정의할 순 없다고 생각이 드는데요. 추가로` Line은 반드시 Section을 하나 이상 포함해야 한다`는 비즈니스 로직이 있습니다.
- 비즈니스 로직이기 때문에 도메인 객체의 역할이다.
- DB에 해당 데이터가 있는지를 물어보는 것이기 때문에 DB의 역할이다.

페어와 위 2가지로 얘기를 해봤는데요 저는 DB에 데이터가 있는지에 대한 검증이라고 생각이 들어 아직은 2번의 방법이 괜찮다고 생각이 듭니다. 미르는 어떻게 생각하시나요?

2022-05-25 12:21 UTC, ddu0422 requested changes
안녕하세요 토닉 ! 미르예요 :)

2단계 미션도 구현 잘 해주셨네요 ㅎ_ㅎ
간단한 코멘트 남겼으니 확인해주시면 감사하겠습니다 🙏🏻 

궁금한 점은 언제든지 DM주시거나 코멘트 남겨주세요 😎 

### Q&A
> Line은 반드시 Section을 하나 이상 포함해야 한다는 비즈니스 로직이 있습니다.

> 1. 비즈니스 로직이기 때문에 도메인 객체의 역할이다.
> 2. DB에 해당 데이터가 있는지를 물어보는 것이기 때문에 DB의 역할이다.

> 페어와 위 2가지로 얘기를 해봤는데요 저는 DB에 데이터가 있는지에 대한 검증이라고 생각이 들어 아직은 2번의 방법이 괜찮다고 생각이 듭니다. 미르는 어떻게 생각하시나요?

비즈니스 로직이라고 명시하셨는데 비즈니스 로직의 책임은 누구의 책임일까요?

> 경로를 계산해주는 Path 객체가 Lines를 받는 구조인데 Lines는 모든 Sections에 대한 정보 뿐만 아니라 이름, 색깔 데이터도 가지고 있어요.
Path 객체는 구간들 마다 추가 요금이 얼마인지만 데이터를 주는게 더 좋다고 생각해서 이에 맞는 데이터를 DB에서 가공하여 쿼리문으로 가져오려고 했습니다.

> Map<Section, Fare> 같은 형식으로

> 제가 생각대로 구현이 되었을 때의 장점은 Line 리스트에서 getter를 통해 데이터를 가져오는 로직을 줄일 수 있고 불필요한 정보를 전달할 필요가 없다고 생각해요. 저는 이 문제가 도메인으로 다루는 객체가 DB와 깊게 연관이 되다보니 데이터를 저장하고 있는 역할도 하고 있어서 라고 생각하는데 결국 현업에서는 DB와 연동된 객체에 비즈니스 로직이 담길 것이라고 생각하는데 이정도는 감수하고 하는게 괜찮을까요? 아니면 그럼에도 불구하고 도메인의 역할에 맞는 데이터를 뽑아 전달하는게 좋을까요?

현업이라면 너무 다양하다고 생각해요. 이렇게 생각하는 분들도 계시고, 저렇게 생각하시는 분들도 계시기 때문이예요. 그래서 제 경험을 기반으로 이야기할 수 밖에 없는 점 양해 부탁드립니다. 제 말이 모두 옳은 것은 아니며, 현재 제가 다니는 회사의 속한 팀 기준으로 설명드리기 때문에 이론적인 부분과 다른 회사에 취업하셨을  때 상당히 다른 경험을 하실 수 있어요.

저희 팀은 Application을 보호하기 위해 DB, 3rd party 등 (Application에 방해되는 요소들)을 분리해요.
DB에 저장되는 객체는 Application에서 비즈니스 로직을 처리하는 객체와 구분하고 있어요.

이유는 DB에 의존하며 비즈니스 로직을 작성하면 객체 지향적이지 않다고 생각하고, 유지보수하기 힘들다고 생각하기 때문이예요.

시간적 여유가 없다면, DB에서 필요한 정보를 가져오며 빠르게 구현하는 방법도 괜찮다고 생각해요.

이론을 적용하면 시간이 오래 걸리지 않을까요?
제 때 기능 출시를 하지 못하여 비즈니스에 영향이 가면 어떻게 될까요?

혹은 제 때 기능 출시를 하려고 엉망으로 코드 작성한다면 어떻게 될까요?
요구사항이 변경되는 경우 깔끔하게 작성했을 때보다 2배, 3배 혹은 그 이상의 시간을 소요하여 변경된 요구사항을 적용하고 있지 않을까요?

이렇듯 상황마다 어떤 방식으로 개발할 지 다르다고 생각해요. ㅎ_ㅎ
너무 고민할 요소가 많아보이네요.. 천천히 고민하시면서 정해도 된다고 생각해요 !

현재는 `배움이 목적`이니 현업에선 이런 방식으로도 생각하는구나 정도로 생각하고 기존에 배운 내용들을 기반으로 best practice가 무엇일지 고민해보면 어떨까요?

2022-05-25 12:21 UTC, ddu0422 commented on docs/step2.md
> +- [ ] getter 최대한 피하기
목표 ! 달성하셨을까요? ㅎ_ㅎ

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/distance/Kilometer.java
>      }
0도 양수일까요!?

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Line.java
> +    public Line(Long id, String name, String color, List<Section> sections, Integer extraFare) {
> 사실 Line은 이 추가 요금에 대한 것으로 어떤 비즈니스 로직을 수행하지 않기 때문에 객체지향적인 관점에서 이 데이터는 Line이 가질 필요가 없다고 생각합니다. 추가 요금이라는 데이터는 경로를 계산해주는 객체에게 필요하기 때문에 Line과는 별개로 따로 요금과 노선도의 데이터를 가지는 객체를 만들어볼 예정이에요!

좋습니다 ! 리팩토링을 진행해보아요.
경로를 계산해주는 내용과 요금을 계산하는 객체를 따로 분리할 수도 있지 않을까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/fare/AgeFarePolicy.java
> +    MORE_THAN_20(age -> age.moreThan(19)) {
나이 조건이 변경되면 변수명도 수정되어야하지 않을까요?
클라이언트에서 구체적인 조건을 아는 방향이 좋을까요? 🤔
[서울교통공사](http://www.seoulmetro.co.kr/kr/page.do?menuIdx=354)를 참고하여 적절한 변수명으로 변경해보는건 어떨까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/fare/AgeFarePolicy.java
> +    abstract public Fare apply(Fare fare, Age age);
Age를 사용하지 않고 있는데 선언한 특별한 이유가 있을까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/fare/Fare.java
> +    }
메서드의 위치가 적절할까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/fare/Fare.java
> +        return new Fare((int) (value / 100.0) * (100 - percent));
매직넘버를 제거하는건 어떨까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/dto/request/LineRequest.java
> +    }
기본값을 제공하여 많은 부분에서 변경이 일어나지 않도록 하셨군요 👍🏻 👍🏻

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/controller/PathController.java
>              @RequestParam int source, @RequestParam int target, @RequestParam int age) {
객체로 받아보는건 어떨까요? 
객체로 받으면 어떤 이점이 있을까요?
먄약, 해당 API를 사용중인경우 age를 추가한다면 어떤 일이 발생할까요?

사용중 예시) `http://localhost:8080/paths?source=1&target=2`

2022-05-25 12:21 UTC, ddu0422 commented on src/test/java/study/JgraphtTest.java
> +    void test() {
어떤 내용을 학습 테스트한 내용인지 작성하면 어떨까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/test/java/wooteco/subway/domain/fare/AgeFarePolicyTest.java
> +     */
불필요한 내용은 삭제하는건 어떨까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/fare/AgeFarePolicy.java
> +                    .discountPercent(50);
fare가 350보다 작은 경우 어떤 일이 발생할까요?

2022-05-25 12:21 UTC, ddu0422 commented on src/test/java/wooteco/subway/domain/path/PathTest.java
> +public class PathTest {
해당 클래스에 DisplayName을 설정하신 특별한 이유가 있을까요?

2022-05-26 15:39 UTC, tonic523 reviewed
미르 현업에 비유해서 상세하게 설명해주셔서 정말 감사합니다!
지금은 배우는 것이 목적이니 미션의 기한에 쫓기지 않는 선에서는 최대한 객체지향적인 이론을 고민해보면서 설계해나가겠습니다.
> 비즈니스 로직이라고 명시하셨는데 비즈니스 로직의 책임은 누구의 책임일까요?

도메인 책임이라고 생각합니다. 그런데 Line이 Section을 포함해야 한다라는 검증을 위해 다른 비즈니스 로직을 처리하는 객체의 데이터를 DB에 의존하게 되는 것 같아 고민이 됐어요.
추가로 생각이 든 것은 Section이 Line을 가져도 앞서 말한 검증을 충분히 했다라고 얘기할 수 있겠네요. 제가 말한 예시나 지금의 미션은 DB에 의존적인 객체에 비즈니스 로직을 담아도 크게 지장이 없다고 생각이 드네요.
DB와 도메인을 위한 객체를 어떻게 구분하고 객체지향적으로 설계를 해야할지는 앞으로 미션을 해나아가면서 고민을 해보겠습니다.

---
### 추가 구현
- ExceptionAdviser에 printStackTrace()로 예외 발생 시 콘솔에 출력하도록 구현

인수 테스트를 하다 ExceptionAdviser가 예외를 처리하고 있어서 리팩토링 과정에서 시간 소요를 많이 했었습니다 ㅠㅠ 베포를 하거나 서비스를 운영할 때에는 위 메서드가 성능에 문제를 일으킬 수 있다고 들어 로깅을 따로 구현해주어야 하지만 개발 과정에서는 위 처럼 콘솔에 예외가 발생한 스택을 추적하기 쉽게 콘솔에 출력하는게 좋은 것 같아요.

2022-05-26 15:39 UTC, tonic523 commented on docs/step2.md
> +- [ ] getter 최대한 피하기
달성하고 싶었는데 하지 못했네요 .. 피드백 반영하면서 달성한 목표는 체크하겠습니다!

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/distance/Kilometer.java
>      }
등호 표시 추가하겠습니다!

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/fare/AgeFarePolicy.java
> +    MORE_THAN_20(age -> age.moreThan(19)) {
네 나이가 변경될 때 마다 상수의 값이 변경되면 유지보수하기 힘들 것 같아요
참고로 보내주신 링크에 맞게 아이, 청소년, 어른, 노인에 맞는 상수 이름으로 수정하겠습니다. 추가로 노인에 대한 요금 정책도 추가로 구현했습니다.

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/fare/AgeFarePolicy.java
> +    abstract public Fare apply(Fare fare, Age age);
Age는 어떤 enum 객체를 사용할지에 대해 사용되고 Fare에 대해서만 로직이 수행되는군요! 만약 나이에 따라 또 요금이 변하는 로직이 생긴다면 매개변수로 받아야 할 것 같아요! 지금은 필요없으니깐 수정하도록 하겠습니다

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/fare/Fare.java
> +        return new Fare((int) (value / 100.0) * (100 - percent));
로직을 조금 수정하여 100.0을 상수처리했습니다. 추가로 100 이상의 값이 들어올 경우를 처리하고 Fare 생성 시 음수값이 들어올 때 예외상황도 추가 구현했습니다.

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/fare/Fare.java
> +    }
네 오버라이팅 메서드와 getter 메서드 위로 수정하겠습니다.
### 클래스 내부 메서드 순서
- public 메서드(public에 사용되는 private 메서드)
- getter 메서드
- 오버라이딩 메서드

위 순서로 수정했습니다.

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/dto/request/LineRequest.java
> +    }
한가지 생각드는건 필드나 request가 받아야 할 데이터의 종류가 달라질 때마다 부 생성자를 추가하는 상황이 생길 것 같아요
그렇지만 부 생성자가 많아진다고 다른 생성자에 큰 영향을 주진 않는다고 생각이 되어 위처럼 구현했습니다.

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/ui/controller/PathController.java
>              @RequestParam int source, @RequestParam int target, @RequestParam int age) {
객체로 받지 않았다면 쿼리스트링이 늘어날 때마다 매핑된 컨트롤러 메서드의 인자값이 늘어나고 서비스에 전달할 값도 늘어나 수정할 코드가 많아지는 것 같습니다. dto로 변환하여 받는다면 컨트롤러에서는 받은 dto를 서비스 계층에 전달만 하면되고 서비스는 dto 스펙에 맞게 사용하면 됩니다. 또한 쿼리스트링에 맞춰 dto 객체만 수정하면 되는 이점이 있다고 생각합니다.

2022-05-26 15:39 UTC, tonic523 commented on src/test/java/study/JgraphtTest.java
> +    void test() {
jgrapht에 커스텀한 클래스를 적용할 수 있는지에 대한 테스트를 작성하면 좋을 것 같아요.
단순 학습 테스트여서 가볍게 넘어갔는데 제가 어떤 학습 테스트를 했는지 적어놓으면 나중에 이해하기 편하고 다른 사람이 볼 때에도 어떤 학습을 했는지 알 수 있도록 작성하겠습니다.

2022-05-26 15:39 UTC, tonic523 commented on src/test/java/wooteco/subway/domain/fare/AgeFarePolicyTest.java
> +     */
enum의 상수에 어떤 연령대인지 알려주도록 수정하여 파악할 수 있지만, 테스트 코드만 봤을 때 MethodSource에 들어가는 값들이 어떤 걸 의미하는지 파악하기 힘들다고 생각했어요. 이럴 땐 주석을 통해 설명하면 가독성에 더 좋다고 생각하는데 그래도 주석을 사용하는건 최대한 피하는게 좋을까요?

2022-05-26 15:39 UTC, tonic523 commented on src/test/java/wooteco/subway/domain/path/PathTest.java
> +public class PathTest {
특별한 이유는 없었습니다.. 다른 테스트 클래스에는 없으니 통일되도록 삭제하겠습니다!

2022-05-26 15:39 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/Line.java
> +    public Line(Long id, String name, String color, List<Section> sections, Integer extraFare) {
경로라는 객체에 나이를 알려주고 요금이 얼마나 나왔는지 알려주는 책임이 있다고 생각했어요.
얘기로 하면 괜찮다고 생각했는데 만약 다른 개발자가 수정을 해야한다고 생각하면 요금에 대한 로직을 Fare 관련해서 찾아보는게 더 빠를 것 같습니다! 현재 구현된 로직과 연결하려다 보니 Fare가 FarePolicy들에 의존되고 FarePolicy가 Fare에 의존하는 관계로 양방향 의존을 갖게 됐습니다. 이러한 결합도를 끊기 위해 다른 방법을 생각해보다가 결국 요금과 요금 정책이라는 것은 결합도가 높을 수 밖에 없는 관계라고 결론을 내렸습니다. 이 부분은 더 좋은 방법이 있지 않을까 생각은 하고 있지만 아직 떠오르지 않네요..

2022-05-26 15:42 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/fare/AgeFarePolicy.java
> +                    .discountPercent(50);
예외를 발생시켜야겠군요.. 객체의 상태를 변환할 때에는 바뀐 상태가 유효한지에 대한 예외 상황을 고려하겠습니다!

2022-05-28 03:44 UTC, ddu0422 commented on src/test/java/wooteco/subway/domain/fare/AgeFarePolicyTest.java
> +     */
주석이 항상 나쁜건 아니라고 생각해요!
다만, 현재 나이 정책이 주석에 포함이 되어 있는데 나이 정책이 변경된다면 해당 내용이 변경되어야하는데 대부분 신경을 쓰지 못해서.. 올바르지 못한 정보를 제공한다고 생각해요 😎

2022-05-28 09:07 UTC, ddu0422 approved these changes
안녕하세요 토닉 ! 미르예요 :)

이번 미션 구현 잘해주시고 충분히 깊이 고민해주셨다고 생각하여 머지할게요 !
간단한 코멘트 남겼으니 확인해주시면 감사하겠습니다 🙏🏻 

경로 조회 미션 고생하셨습니다 ! 마지막 미션도 화이팅이예요 🎆

2022-05-28 09:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/controller/ExceptionAdviser.java
> +        exception.printStackTrace();
> 인수 테스트를 하다 ExceptionAdviser가 예외를 처리하고 있어서 리팩토링 과정에서 시간 소요를 많이 했었습니다 ㅠㅠ 베포를 하거나 서비스를 운영할 때에는 위 메서드가 성능에 문제를 일으킬 수 있다고 들어 로깅을 따로 구현해주어야 하지만 개발 과정에서는 위 처럼 콘솔에 예외가 발생한 스택을 추적하기 쉽게 콘솔에 출력하는게 좋은 것 같아요.

개발 시에 사용하면 개발할때 편할 수 있겠죠.. 하지만 배포 이후에는 불필요하기 때문에 다른 방법을 찾아보는 걸 추천드려요.
로깅을 제대로 잘하거나 or 디버깅모드로 실행하여 한단계씩 디버깅을 한다면 exception.printStackTrace()이 없어도 충분히 디버깅을 할 수 있다고 생각해요 !
만약, 로깅이나 디버깅 모드를 활용하기 어렵다면 로컬 환경에서만 사용 후 제거하여 배포하면 어떨까요?

2022-05-28 09:07 UTC, merged