[Spring 지하철 경로 조회 - 1,2단계] 인비(김태희) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #56
Opened 2021-05-12 12:45 UTC by taehee-kim-dev

### 안녕하세요, 미립!!

JWT와 Vue.js를 처음 접해서 많이 낯설었네요. 😅 

잘 했는지 모르겠습니다.

소중한 시간 내어 코드리뷰 해 주셔서 감사합니다!! 🙇

2021-05-13 07:16 UTC, seok-2-o requested changes
안녕하세요 😄  이번 미션을 함께 할 미립입니다.

구현 정말 잘해주셨어요. 몇가지 코멘트 남겨 놓았으니 확인 부탁드려요

앞으로 과정 진행하면서 저와 의견이 다르거나 궁금한점 있으면 편하게 코멘트 또는 DM 남겨주세요.

인비와 함께 할 수 있게 되어 무척 기쁜 마음입니다. :)
모쪼록 다음 코드 기대하며 기다리고 있을게요. 🙇

2021-05-13 07:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/MemberController.java
> +    public ResponseEntity<Void> updateMemberOfMine(@AuthenticationPrincipal Member member, @RequestBody MemberRequestDto memberRequestDto) {
생성과 수정이 같은 MemberRequestDto 를 쓰는것에 대해서 어떻게 생각하시나요?
둘이 달라질 일은 없을까요?

2021-05-13 07:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/config/WebMvcConfiguration.java
> +    }
👍

2021-05-13 07:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/dto/request/MemberRequestDto.java
> +    public MemberRequestDto(String email, String password, Integer age) {
이름을 변경하신 이유가 궁금해요 🤔

2021-05-13 07:16 UTC, seok-2-o commented on src/main/java/wooteco/member/service/AuthService.java
> +    public Member getUserInfo(String principal, String credentials) {
외부에서 호출하지 않는 메소드라면 private 으로 변경하는건 어떤가요?

2021-05-13 07:16 UTC, seok-2-o commented on src/main/java/wooteco/member/service/AuthService.java
> +        if (!jwtTokenProvider.validateToken(token)) {
부정(!) 을 사용하기보다 부정형 메소드를 만들어서 사용하면 어떤 장점이 있을까요 ?

2021-05-13 07:16 UTC, seok-2-o commented on src/main/java/wooteco/subway/controller/dto/response/LineResponseDto.java
> +            .map(it -> StationResponseDto.of(it))
```suggestion
            .map(StationResponseDto::of))
```

2021-05-13 07:16 UTC, seok-2-o commented on src/main/java/wooteco/subway/domain/Sections.java
> +            .filter(it -> it.getDownStation().equals(section.getDownStation()))
디미터의 법칙 위반하셨네요, 객체 지향 생활 체조에선 한줄에 점 하나라는 규칙으로 표현하고 있어요.

2021-05-13 09:23 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/MemberController.java
> +        return ResponseEntity.ok().body(new MemberResponseDto(member));
반영 했습니다!

2021-05-13 09:28 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/MemberController.java
> +        return ResponseEntity.ok().build();
저도  No Content가 더 적합하다고 생각합니다!
수정하였습니다!

2021-05-13 09:30 UTC, taehee-kim-dev commented on frontend/src/pages/member/JoinPage.vue
> +        const response = await fetch("/api/members", {
```javascript
async function postData(url = '', data = {}) {
    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(data)
    })
    return response.json();
}
```

이런식으로 메서드 추출을 통해 중복 부분들을 제거할 수 있을 것 같습니다!!
그런데 현재 프론트 코드들이  추상화가 많이 되어있어 수정하기가 어렵네요ㅠ

2021-05-13 09:34 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/MemberController.java
> +    public ResponseEntity<Void> updateMemberOfMine(@AuthenticationPrincipal Member member, @RequestBody MemberRequestDto memberRequestDto) {
저도 달라질 일이 충분히 있을거라 생각합니다. 하지만 지금은 이상태로도 괜찮다고 생각합니다.

저번 미션에서도 RequestDto가 주어진 상태로 시작했는데,
추후 구현 하면서 CreateRequest와 UpdateRequest 각각이 필요한 경우가 생겼었습니다.
필요한 경우가 생길 때 분리하면 될 것 같아요!

2021-05-13 09:36 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/dto/request/MemberRequestDto.java
> +    public MemberRequestDto(String email, String password, Integer age) {
처음에는 패키지에 Dto라는 뜻이 명시 되어있어서 안쓰는 편이었는데,
몇몇 책을 보면서 이런식으로 작성 하는 경우를 많이 보았어요.
그래서 저도 어느순간부터 이렇게 쓰게 되더라고요!

혹시 이것에 대한 컨벤션 같은게 있을까요?
미립은 어떤 방식으로 하시나요?

2021-05-13 09:36 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/service/AuthService.java
> +    public Member getUserInfo(String principal, String credentials) {
반영했습니다!

2021-05-13 09:40 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/service/AuthService.java
> +        if (!jwtTokenProvider.validateToken(token)) {
이전 미션에서 부정형 메소드를 만들어서 사용했었어요.

그 때 받은 피드백중 하나가 부정형 메소드를 사용하면, 한 번 더 생각해야 하고
긍정형만 사용했을때와 다르게 일관성이 떨어진다고 하더라구요.

긍정형으로만 사용 하되, (!)을 붙여서 부정의 의미를 전달 하는것이 더 좋게 느껴지는데,
미립 생각은 어떠신가요?

2021-05-13 09:43 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/controller/dto/response/LineResponseDto.java
> +            .map(it -> StationResponseDto.of(it))
앗, 주어진 코드였는데 놓쳤네요!!
수정했습니다!!

2021-05-13 09:51 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/domain/Sections.java
> +            .filter(it -> it.getDownStation().equals(section.getDownStation()))
수정했습니다!

2021-05-13 12:05 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/MemberController.java
> +    public ResponseEntity<Void> updateMemberOfMine(@AuthenticationPrincipal Member member, @RequestBody MemberRequestDto memberRequestDto) {
좋네요 필요한 경우에 분리한다! 저도 좋아하는 접근 방식입니다.
미리 분리해놓을 필욘 없죠 !!

2021-05-13 12:06 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/dto/request/MemberRequestDto.java
> +    public MemberRequestDto(String email, String password, Integer age) {
보통 이런경우는 회사 컨벤션을 따르고 저는 DTO 없이 표현하는 편입니다
Request 나 Response 자체를 DTO 의미를 내포하고 있다고 정의해놓고 사용하는 편이에요 :)

2021-05-13 12:07 UTC, seok-2-o commented on src/main/java/wooteco/member/service/AuthService.java
> +        if (!jwtTokenProvider.validateToken(token)) {
저는 ! 가 개인적으로 가독성이 좋다고 생각하지 않아서 부정 메소드를 제공하는 것을 선호하는 편입니다.
정답이 있는 문제는 아니니 인비가 좋다고 생각하는 방법을 사용하시면 될 것 같아요.

추가로 저는 일관성을 위해 긍정과 부정 메소드를 모두 제공합니다 : )

2021-05-13 12:16 UTC, seok-2-o requested changes
피드백 빠르게 잘 반영해주셨네요.
인터셉터 부분에서 몇가지 코멘트  남겨놓았어요. 
인비의 생각이 궁금하네요. 해당 부분 확인해주세요 🙇

2021-05-13 12:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/AuthController.java
> +    @PostMapping("/login/token")
로그인의 방식을 구지 명시해줄 필요가 있을지 고민해보면 좋을 것 같아요.

2021-05-13 12:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/AuthController.java
> +    public ResponseEntity<TokenResponseDto> loginWithToken(@RequestBody TokenRequestDto tokenRequestDto) {
TokenRequestDto 네이밍이 고민이 되는 부분이긴하네요.
인비 어떻게 생각하시나요 ?

2021-05-13 12:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/config/LonginInterceptor.java
> +        String accessToken = request.getHeader("Authorization");
`Bearer` 가 붙어서 나와 에러를 발생시킬 것 같은데 해당 인터셉터에 대한 테스트 코드도 작성해보는건 어떤가요?

2021-05-13 12:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/config/LonginInterceptor.java
> +        String accessToken = request.getHeader("Authorization");
AuthorizationExtractor.extract 를 활용하는것도 좋은 방법일 것 같아요.

2021-05-13 12:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/config/LonginInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
```suggestion
        return true;
```
super.preHandle 를 확인해보면 위와 동일한 동작일 것 같아요. 그래도 super 를 호출하는 것이 좋을까요?

2021-05-13 12:16 UTC, seok-2-o commented on src/main/java/wooteco/member/controller/config/LonginInterceptor.java
> +public class LonginInterceptor implements HandlerInterceptor {
로그인 여부를 확인하는 부분과 리졸빙을 잘분리해주셨네요 👍

2021-05-13 13:55 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/AuthController.java
> +    @PostMapping("/login/token")
그렇네요!! 보안상에도 안 좋을 것 같아요.
바로 반영했습니다!! :)

2021-05-13 13:58 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/AuthController.java
> +    public ResponseEntity<TokenResponseDto> loginWithToken(@RequestBody TokenRequestDto tokenRequestDto) {
미립의 피드백을 듣고 생각해보니 저도 그런 것 같아요.
LoginToken으로 수정했습니다!!

2021-05-13 14:11 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/config/LonginInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
앗 그렇군요! 타고 들어가서 상위 인터페이스 default 메소드를 확인해 보니, true를 반환하고 있네요.
바로 반영했습니다!! 감사해요!!

2021-05-13 14:12 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/config/LonginInterceptor.java
> +public class LonginInterceptor implements HandlerInterceptor {
감사합니다!! 😆

2021-05-13 14:28 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/controller/config/LonginInterceptor.java
> +        String accessToken = request.getHeader("Authorization");
앗 정말 그러네요!! 제가 LonginInterceptor API 접근 경로 설정을 잘못 해놔서 테스트가 작성되어 있음에도 불구하고 아예 LonginInterceptor를 타지 않아  몰랐었어요 😢 

바로 수정했어요!! 정말 감사합니다!!

2021-05-13 14:31 UTC, taehee-kim-dev commented
### 안녕하세요, 미립!! 😃 

소중하고 세심한 코드 리뷰 정말 감사합니다!!
덕분에 LonginInterceptor에 관한 버그도 고칠 수 있었어요ㅠㅠ
감사합니다!!

2021-05-14 00:05 UTC, seok-2-o requested changes
피드백 반영 잘해주셨네요 👍 

마지막으로 알아두시면 좋을 것 같은 부분이 있어 코멘트로 남겨 놓았습니다.
확인 후 리펙토링 해주세요 :)

2021-05-14 00:05 UTC, seok-2-o commented on src/main/java/wooteco/member/dao/MemberDao.java
>      private JdbcTemplate jdbcTemplate;
이번 미션과 큰 상관이 없는 주제지만 [NamedParameterJDBCTemplate](https://rkaalstu.tistory.com/43)
를 적용해보는 건 어떤가요. 지금보다 유지보수하기에 용이한 코드가 될 것 같아요.

2021-05-14 00:05 UTC, seok-2-o commented on src/main/java/wooteco/member/dao/MemberDao.java
> +        String query = "select * from MEMBER where email = ? and password = ?";
보통 password 는 데이터베이스에 암호화되어 저장되기때문에 지금과 같은 방식으로 비교하기는 어려울 것 같아요.
이를 해결하기 위해선 어떻게 해야 할까요 ?

2021-05-14 00:46 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/dao/MemberDao.java
> +        String query = "select * from MEMBER where email = ? and password = ?";
비밀번호는 보통 hash 알고리즘으로 단방향 암호화가 되고, 암호화 된 비밀번호 자체를 비교하는 방식을 사용합니다.

1. 회원가입 시, 암호화 된 비밀번호가 DB에 저장됩니다.
2. 사용자가 로그인을 요청합니다. (raw password 전달)
3. 서버에서 로그인 요청의 raw password를 encrypted password로 hash 변환합니다.
4. DB에 있는 encrypted password와 로그인 요청으로 받은 password의 encrypted password가 일치하는지 확인합니다.
5. 일치하다면, 로그인을 허용합니다.

이런 방식으로 암호화된 회원가입과 로그인을 하는 것으로 알고 있어요.

그래서 위의 방식으로도 암호화된 password 비교가 가능하다고 생각합니다.

미립의 피드백은 어떤 부분인지 알 수 있을까요?

2021-05-14 04:39 UTC, taehee-kim-dev commented on src/main/java/wooteco/member/dao/MemberDao.java
>      private JdbcTemplate jdbcTemplate;
반영했습니다!
매개 변수의 순서를 숫자가 아닌 문자로 표기해, 더 직관적이네요!! :)

2021-05-14 04:41 UTC, taehee-kim-dev commented
피드백 반영했습니다!
감사합니다. :)

2021-05-14 06:15 UTC, seok-2-o approved these changes
피드백 반영 잘 해주셨네요

DM으로 남겨 놓았지만 기록을 위해 여기 다시 한번 남겨 놓을게요
![image](https://user-images.githubusercontent.com/34270397/118229530-1ba19d00-b4c7-11eb-8037-2df7ec3459fa.png)

위 이미지를 보면 동일한 원문이지만 각기 다른 결과를 보여주는것을 확인 할 수 있습니다.
(Spring sec 에서 기본적으로 사용하는 BCrypt 를 이용했어요)

동일한 암호에 항상 같은 결과를 만든다면 레인보우 어택등에 취약점이 발생하여
솔팅/키스트레칭을 더해 암호화를 진행합니다. 
해당 암호에는 결과에는 풀 수 있는 정보들이포함되어 있는 것이 특징입니다.

더 알고 싶다면 위 키워드를 통해 검색 진행해보면 좋을 것 같아요.

이번 미션은 워낙잘해주셔서 빠르게 머지할 수 있도록 할게요 🙇

2021-05-14 06:15 UTC, merged

2021-05-17 04:40 UTC, taehee-kim-dev commented
### 학습로그
- [우아한테크코스 3기 백엔드 Lv2 [지하철 미션] 학습로그](https://velog.io/@taehee-kim-dev/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-3%EA%B8%B0-%EB%B0%B1%EC%97%94%EB%93%9C-Lv2-%EC%A7%80%ED%95%98%EC%B2%A0-%EB%AF%B8%EC%85%98-%ED%95%99%EC%8A%B5%EB%A1%9C%EA%B7%B8)