[Spring 지하철 경로 조회 - 1,2단계] 오즈(오주형) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #72
Opened 2021-05-13 09:35 UTC by ohjoohyung

안녕하세요 휴!!!
지하철 경로 조회 미션으로 처음 뵙게 된 오즈라고 합니다!!
이번 미션도 미리 프론트, 서버 코드가 구현이 되어있고 학습 테스트를 참고하면서 진행할 수 있어 생각보다 빠르게 끝난거 같습니다..!! 다만 프론트 부분이나 jwt와 같이 거의 처음 접한 내용에서는 어려움을 겪었습니다..ㅠ.ㅠ

이번 미션을 진행하다 몇 가지 궁금한 점이 있습니다!
**첫 번째로** DTO의 범위에 대해서입니다.
사실 이 부분은 저번 미션 때 고민을 했고 질문도 했었는데요. 이번에 다시 한번 페어와 이야기를 나누게 되어 질문드립니다.
presentation layer에 속하는 dto가 서비스에서도 사용이 되어 dto를 domain으로 변환하는 작업 또는 반대 작업을 서비스에서 하는게 좋을까요? 아니면 컨트롤러에서 해주는게 좋을까요?
크루들과 이야기를 나눠보고 인터넷에 검색도 해보니 정답은 없다고 생각이 됩니다만 휴의 의견을 듣고 싶습니다!!! 일단 이번 미션은 서비스에서 dto, domain 변환 작업을 해주었습니다!!

**두 번째로** 토큰 검증 위치에 대한 내용입니다.
지금은 AuthenticationPrincipalArgumentResolver에서 AuthService를 호출해서 토큰에 대한 검증을 하고 있는데 이 토큰 검증을 현재 위치에서 해줘야할지 인터셉터나 필터를 이용해서 해야하는지가 궁금합니다. 어디서 해주는게 좋을까요?? 
사실 이 부분은 이번에 처음 접한 내용이라 아직까지 리졸버, 인터셉터, 필터에 대해 거의 모르는거와 다름없어 질문 내용이 모호할 수 있습니다ㅠ.ㅠ

**세 번째**로 토큰의 저장 위치에 대한 내용입니다.
제가 vue에 대해 잘 알지 못해 정확히 맞는 것인지는 잘 모르겠습니다만 현재 accessToken을 vuex를 사용해 전역 변수로 관리를 하고 있는 것으로 알고 있습니다.
검색을 해보니 로컬 스토리지나 세션 스토리지 또는 쿠키로 저장을 하는 방식도 존재한다고 적혀있던데 어디에 저장하는 것이 좋을까요??
물론 각자 장, 단점이 있는 것으로 알고 있습니다만 현재 프로젝트에서는 어떻게 구현을 하는게 좋을지 궁금합니다!!

**마지막으로** 현재 구현한 페이지는 로그인을 하고 새로고침 시 로그인이 풀리는 현상이 나타납니다..!! 
새로고침을 하더라도 로그인을 유지하는 방법이 있을까요??
키워드를 알려주시면 찾아보고 리팩토링을 해 볼 생각입니다!!

그럼 리뷰 잘 부탁드립니다!!!
감사합니다~~

2021-05-14 15:43 UTC, Hue9010 requested changes
반갑습니다 오즈! 이번 리뷰를 맡은 휴입니다. 😄
남겨주신 질문에 대한 답변과 피드백 남겼는데 궁금한건 언제든 질문 주세요!
개인적으로 평일보다 주말이 더 여유로우니 주말 신경쓰지 않으셔도 됩니다. 😉

2021-05-14 15:43 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        String id = authService.getPayload(accessToken);
Q.
두 번째로 토큰 검증 위치에 대한 내용입니다.
지금은 AuthenticationPrincipalArgumentResolver에서 AuthService를 호출해서 토큰에 대한 검증을 하고 있는데 이 토큰 검증을 현재 위치에서 해줘야할지 인터셉터나 필터를 이용해서 해야하는지가 궁금합니다. 어디서 해주는게 좋을까요??
사실 이 부분은 이번에 처음 접한 내용이라 아직까지 리졸버, 인터셉터, 필터에 대해 거의 모르는거와 다름없어 질문 내용이 모호할 수 있습니다ㅠ.ㅠ

A.
너무 고민하지 말고 보죠.
우선 리졸버
[spring web HandlerMethodArgumentResolver](http://wonwoo.ml/index.php/post/1092)
> HandlerMethodArgumentResolver 인터페이스의 역할은 간단하다. 컨트롤러에서 파라미터를 바인딩 해주는 역할을한다.

단순하게 파라미터에 대한 바인딩이 필요할 때 사용한다고 생각해주세요. LoginMember가 되겠네요.
이때 토큰 검증은 사실 바인딩과 직접 상관 있는 작업은 아니죠.

이제 인터페이스를 볼까요?

[Interface HandlerInterceptor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/HandlerInterceptor.html)
> Workflow interface that allows for customized handler execution chains. Applications can register any number of existing or custom interceptors for certain groups of handlers, to add `common preprocessing` behavior without needing to modify each handler implementation.
> 번역기 : 사용자 지정 처리기 실행 체인을 허용하는 워크 플로 인터페이스입니다. 애플리케이션은 특정 핸들러 그룹에 대해 기존 또는 사용자 정의 인터셉터를 등록하여 각 핸들러 구현을 수정할 필요없이 공통 `전처리` 동작을 추가 할 수 있습니다.


> This mechanism can be used for a large field of preprocessing aspects, e.g. for `authorization checks`, or common handler behavior like locale or theme changes. Its main purpose is to allow for factoring out repetitive handler code.
> 번역기 : 이 메커니즘은 예를 들어 `권한 확인` 또는 로케일 또는 테마 변경과 같은 일반적인 핸들러 동작과 같은 전처리 측면의 넓은 분야에 사용될 수 있습니다. 주요 목적은 반복적 인 핸들러 코드를 제거하는 것입니다.

질문만 놓고 봤을 떄 HandlerInterceptor document에는 친절하게 authorization checks 언급이 있네요. 😄
토큰 검증을 어디서 할지는 고민할 필요가 갑자기 사라졌네요...? 🤣 

그래도 인터페이스에 대해 조금 더 생각해보자면 저 전처리기라는 개념에만 집중해주시면 될 것 같아요.

필터도 전처리 작업이라 생각할 수 있는데 우선 스프링 전/후로 컨텍스트 자체가 다르답니다.
[[Spring] Filter, Interceptor, AOP 차이](https://velog.io/@sa833591/Spring-Filter-Interceptor-AOP-%EC%B0%A8%EC%9D%B4-yvmv4k96) - aop는 지금 신경쓰지 마세요. 😉 

---

잠깐 정리해보자면 HandlerMethodArgumentResolver는 말 그대로 파라미터를 바인딩해주는 존재이고, HandlerInterceptor는 Spring doc에서 공식적으로 authorization checks를 하는 애라고 지정해준 존재입니다. 🙄

여러모로 학습 차원에서도 인터셉터를 적용해보는게 좋을 것 같아요. 다만 꼭 적용할 필요는 없으니 진행할지는 오즈가 선택해주시면 됩니다. 😉

2021-05-15 09:41 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        member.validatePassword(tokenRequest.getPassword());
앗.. 그런 의도는 아니었습니다ㅎㅎ;;
처음엔 입력한 email과 password를 이용해서 한번에 조회를 해 같은 멤버가 있는지를 비교했었는데
뭔가 너무 db에 의존적인거 같아 조금 더 객체지향스럽게 member를 email을 통해 불러오고 password가 일치하는지 member 객체에게 물어보는 식으로 수정했던 것이었습니다!!

db 데이터 암호화에 대해 말씀해주시니까 잘 수정했다는 생각이 드네요!!
그렇다면 만약에 db에 password를 암호화해서 저장해주었을 때는 이런 로직으로 로그인 검증이 진행되는 건가요?

1. 회원가입 시 입력 회원 정보들이 저장되는데 password는 암호화해서 저장
2. 로그인 시 email과 password를 입력
3. email을 통해 member를 불러옴
4. member의 password를 복호화시켜 입력한 password와 비교
5. 같다면 로그인 성공 or 다르다면 로그인 실패

2021-05-15 09:51 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/application/exception/MemberNotFoundException.java
> +@ResponseStatus(HttpStatus.UNAUTHORIZED)
이 예외를 만들어준 이유가 password 비교에 AuthorizationException을 쓰다보니 중복이 싫어 다른 예외를 만들어주는게 좋을거같아 만들었습니다. 
게다가 처음부터 구현이 되어있던 테스트 코드의 에러 상태가 UNAUTHORIZED여서 이거에 맞추다보니 ResponseStatus(HttpStatus.UNAUTHORIZED)를 사용하게 되었습니다.
근데 생각해보니 email 비교나 password 비교나 전부 로그인 인증과 관련된 내용이기에 AuthorizationException을 같이 사용해도 되겠다고 생각해 AuthorizationException을 사용하고 MemberNotFoundException을 삭제했습니다!!
만약 후에 MemberNotFoundException을 만든다면 404로 만드는 것이 적당할 거 같네요!!

2021-05-15 09:52 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/application/exception/AuthorizationException.java
> +    }
앗..!! 깜빡하고 에러 메시지를 적지 않았네요ㅎㅎ;;
사용하도록 만들어주었습니다!!

2021-05-15 09:55 UTC, ohjoohyung commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    private Long id;
페어와 저도 id만 있는데 LoginMember라는 이름을 사용해도 괜찮을까하고 생각했습니다만 요구사항에 LoginMember라고 적혀있어 LoginMember로 만들었습니다..
그래서 피드백에 맞게 일단 LoginMemberId로 수정했습니다!! 괜찮나요??

2021-05-15 09:56 UTC, ohjoohyung commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
아하! 이 생성자는 private으로 변경할 수 있군요! 수정했습니다~~

2021-05-15 10:08 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    public TokenResponse createToken(TokenRequest tokenRequest) {
아하...!!!
생각해보니 Service에서 Service를 사용할 때 그런 불편함이 생길 수가 있군요!!
저도 처음에는 휴와 같이 Service layer에서는 dto를 사용하지 않아야 한다라고 생각을 했었는데
제가 굉장한 팔랑귀를 가지고 있다보니..
https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md
이러한 글을 읽고 나니 Service에서 변환 해주는거도 좋은거 같은데?? 라는 생각도 들더라고요ㅠ.ㅠ

그래서 다른 크루들과 더불어 휴의 생각도 들어보고 싶었습니다!!
사실 아직까지도 무엇이 좋은지 결론은 나지 않지만 마지막 말이 인상적이네요!!
```
어떤 방식을 선택하는지 보다는 일관성을 지키는게 중요하다고 생각해요
```
둘 중 한 방식을 선호하더라도 프로젝트를 진행할 때는 팀원들과 이야기를 나누어 하나를 정해 프로젝트의 일관성을 지키는 것!! 그러한 유연성을 가지는 것이 좋다고 생각이드네요!!!
감사합니다~~~

2021-05-15 10:17 UTC, ohjoohyung commented on frontend/src/pages/member/LoginPage.vue
> +        this.setAccessToken(token.accessToken);
프론트 영역도 구현을 해야하다보니 토큰을 저장해야하는데 어디다 저장해야하지 하고 고민했던 부분이라 휴한테 여쭤봤던 것이었습니다!!
역시 정답은 없군요ㅎㅎ;;

그리고 해주신 말씀 다 맞는 말씀인거 같아요ㅋㅋㅋㅋ
이번 미션은 인증/인가를 위해 백엔드에서 어떠한 요청과 응답의 흐름이 진행되고 이 때 토큰(JWT를 사용하였기에)은 어떻게 생성되고 사용되는가..!! 이게 핵심인거 같습니다!!
조금 더 이 흐름에 대해 집중을 해야겠습니다!!!
링크 주신 사이트 감사합니다!!!

2021-05-15 10:34 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        String id = authService.getPayload(accessToken);
이렇게 좋은 자료와 답변을 해주시다니..ㅠ.ㅠ 감사합니다..!!!
정말 고민할 필요가 사라졌네요..!!
HandlerMethodArgumentResolver는 단순하게 파라미터에 대한 바인딩이 필요할 때(이번 미션과 같이 로그인된 멤버를 컨트롤러의 파라미터로 가져올 때),
HandlerInterceptor는 클라이언트 요청과 관련있는 전처리(로그인, 인증, 권한 등)에 사용되는 것이었군요!!!
만들어진 목적이 있었는데 이를 제대로 찾아보지 않았네요..ㅠㅠ
Filter의 경우는 컨텍스트 자체가 다르고 목적도 인코딩 변환 처리, XSS 방어를 개발할 때 사용이 되는군요!!

목적에 맞게 나눠서 구현을 했어야 했는데 한 곳에서 처리를 해주고 있었네요..
그래서 인터셉터를 만들어 분리를 했습니다!!!
근데 이렇게 되니 코드적으로 조금 아쉬운 부분이 생겼는데요.

```java
public class AuthInterceptor implements HandlerInterceptor {
    private final JwtTokenProvider jwtTokenProvider;

    public AuthInterceptor(JwtTokenProvider jwtTokenProvider) {
        this.jwtTokenProvider = jwtTokenProvider;
    }

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        String accessToken = AuthorizationExtractor.extract(request);
        validateToken(accessToken);
        return true;
    }

    private void validateToken(String accessToken) {
        if (!jwtTokenProvider.validateToken(accessToken)) {
            throw new AuthorizationException("토큰이 유효하지 않습니다.");
        }
    }
}
```

```java
public class AuthenticationPrincipalArgumentResolver implements HandlerMethodArgumentResolver {
    private AuthService authService;

    public AuthenticationPrincipalArgumentResolver(AuthService authService) {
        this.authService = authService;
    }

    @Override
    public boolean supportsParameter(MethodParameter parameter) {
        return parameter.hasParameterAnnotation(AuthenticationPrincipal.class);
    }

    @Override
    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
        String accessToken = AuthorizationExtractor.extract((HttpServletRequest) webRequest.getNativeRequest());
        String id = authService.getPayload(accessToken);
        return new LoginMemberId(id);
    }
}
```

위에는 인터셉터, 아래는 리졸버의 코드인데 보시는 바와 같이 accessToken을 추출하기 위한 메서드가 두 번 반복되고 있습니다.. 원래 제가 작성했던 코드에서는 리졸버에서만 사용이 되었고요!
토큰 값의 전달이 불가능할거 같아 각각의 역할에 맡게 나누기 위해서는 불가피한 선택인거 같은데 이렇게 적용 되는게 괜찮은가요??
뭔가 토큰 값이 두 번 추출되는거에 조금 불편함을 느껴 질문드립니다..!!

2021-05-15 10:43 UTC, ohjoohyung commented
휴!!! 정말 좋은 피드백 감사합니다!!!
덕분에 많은 공부가 되었습니다!!!

다만, 마지막 질문을 깜빡하신거 같아 다시 질문드릴게요ㅋㅋㅋㅋ

로그인 후 새로고침 시 로그인 유지에 대한 질문이었는데 vue는 찾아보니 vuex-persistedstate라는 걸 이용한다고 하더라고요.
사실 이 부분은 너무 vue 쪽이기에 그냥 그렇구나 하고 넘어가려고 하는데
새로고침 후 로그인을 유지하기 위한 부분은 프론트 영역이라 그렇구나 하는 정도로 넘어가면 될까요??

2021-05-15 12:16 UTC, Hue9010 approved these changes
오즈! 피드백을 빠르게 반영해주셨네요. 👏 
워낙 잘해주셔서 추가로 드릴 피드백이 없네요. 💯  😄
이번 단계는 여기서 머지할게요!
몇가지 코멘트를 남기긴 했으니 확인하고 궁금한건 질문 주세요!!

2021-05-15 12:16 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        String id = authService.getPayload(accessToken);
지금은 AuthInterceptor와 AuthenticationPrincipalArgumentResolver가 사용되는 곳이 동일하지만 독릭접으로 사용하게 될 수도 있다는걸 염두해 둬야할 것 같아요. 서로가 서로의 존재를 모르고 있는 상태로 의존성도 가지고 있지 않죠.

그래도 HttpServletRequest에 넣어줄까도 고민했는데 넣을 수야 있지만 이곳이다 하는 무언가가 안떠오르네요. 😢

2021-05-15 12:17 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    private Long id;
넵, 괜찮습니다. 어떤식으로 확장할지는 몰라서 아직은 어떤게 맞다는 없고 어떻게 생각하고 있는지가 중요할 것 같아요. 😉

2021-05-15 12:20 UTC, Hue9010 commented
머지하기 전 코멘트 답변드리다보니 
> 사실 이 부분은 너무 vue 쪽이기에 그냥 그렇구나 하고 넘어가려고 하는데
> 새로고침 후 로그인을 유지하기 위한 부분은 프론트 영역이라 그렇구나 하는 정도로 넘어가면 될까요??

이걸 또 깜박했네요!! 😱
잠시 다시 체크해볼게요. 🙏

2021-05-15 13:10 UTC, Hue9010 commented
[vuex-persistedstate 덕분에 Vue.js 화면을 새로고침 해도 안전해요.](https://uxgjs.tistory.com/207)
> vuex-persistedstate는 이 state에 저장된 변수와 값을 그대로 웹브라우저의 localstorage에 업데이트를 해 줍니다.

[웹 스토리지 (Web Storage)의 특성과 사용법](https://untitledtblog.tistory.com/47)

넵, 그래도 나온김에 브라우저의 스토리지 영역에 대한 기본적인 부분만 보고 넘어가면 될 것 같아요. 
애매하다 싶으면 거꾸로 생각해보죠. `프론트 과정분이 서버의 이것까지 알 필요가 있나?` `개념적인것까지 아는건 좋지만 구현적인 부분까지 학습할 필요가 있을까?` 이런 차원에서 넘어가도 된다고 봐요. 😄

2021-05-15 13:10 UTC, merged

2021-05-16 08:53 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        member.validatePassword(tokenRequest.getPassword());
아!!! 생각해보니 정말이네요!!!!
여러가지 사이트를 이용하며 단 한 번도 비밀번호 찾기를 본 적이 없는거같아요..
임시 비밀번호 발급, 비밀번호 수정만 봤지..😂😂

제가 잘못 생각하고 있었군요ㅎㅎ
비밀번호 복호화는 못하게 하고 단방향으로 저장만 하는게 일반적인 경우인거 같습니다!!
복호화가 된다면 보안에 위험하니까요!!
더불어 해시와 솔트에 대한 글도 알려주시다니..
감사합니다~~

2021-05-16 08:55 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    public TokenResponse createToken(TokenRequest tokenRequest) {
ㅋㅋㅋㅋㅋㅋㅋ맞습니다..
이것저것 사용해보며 스스로 비교해봐야 나름의 신념이 생길 것 같습니다!!
감사합니다!!!👍👍👍

2021-05-16 08:57 UTC, ohjoohyung commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        String id = authService.getPayload(accessToken);
마땅한 방법이 없군요..!!
일단 각각 자신만의 역할을 가지고 있기에 목적에 맞게 나누어서 사용해보는것!!
그거에 집중해 공부해보았다!!!
이걸로 만족하겠습니다!!!