[Spring 지하철 경로 조회 - 1,2단계] 루트(김준근) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #85
Opened 2021-05-13 22:06 UTC by Junroot

안녕하세요 휴! 오랜만에 다시 리뷰를 받게되어서 기뻐요!
경로조회는 3단계라 경로조회 관련 테스트는 실패하는 상태입니다!
아래는 미션을 진행하면서 생긴 질문들이에요.

## JWT에서 비밀 키를 사용하는 이유

뼈대 코드 중에 `createToken()`과 `getPayload()`를 보고 생긴 의문입니다. JWT에서는 토큰을 생성할 때, 토큰의 무결성을 만족시키기 위해 HMAC 으로 토큰에 서명을 함께 붙여 전송하는 것으로 이해했습니다. 하지만 HMAC을 사용할 때 비밀 키로 사용하는 이유가 궁금합니다. 서버가 다시 받은 토큰을 검증할 때도 비밀 키만 사용되고 있어 공개 키가 사용될 일이 없어보입니다. 어차피 이렇게 키 하나만 사용하면 대칭키를 사용해도 문제가 없다는 생각이 드는데 왜 굳이 비대칭키인 비밀키를 사용할까요?

이 외에도 좋은 피드백 잘 부탁드립니다!!!

2021-05-14 02:29 UTC, Junroot commented
수업을 들어보니 제가 secret key를 private key로 착각했네요!! 😂

2021-05-15 08:23 UTC, Hue9010 requested changes
루트 반가워요! 잘지내셨나요? 😄 
요구사항에 맞게 잘해주셨네요. 💯 
피드백 드릴 부분은 적어 간단한 내용 몇개만 남겼어요.
질문에 대한 답변 포함해서 확인하고 궁금한건 언제든 질문 주세요!
(주말이 더 편하니 주말 걱정 말고 질문 주세요. 😉 )

2021-05-15 08:23 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private JwtTokenProvider jwtTokenProvider;
Q.
HMAC을 사용할 때 비밀 키로 사용하는 이유가 궁금합니다. 서버가 다시 받은 토큰을 검증할 때도 비밀 키만 사용되고 있어 공개 키가 사용될 일이 없어보입니다. 어차피 이렇게 키 하나만 사용하면 대칭키를 사용해도 문제가 없다는 생각이 드는데 왜 굳이 비대칭키인 비밀키를 사용할까요?

A.
비대칭 키가 공개키고 HMAC엔 대칭키(비밀키)를 사용하지 않나요? 🤔 
질문을 한번 다시 정리해주세요!! 혹은 공유 키라는 키워드와 헷갈린걸까요?

그전에 앞서 [[웹툰03] SSL이란 무엇인가? 1/2](https://minix.tistory.com/395?category=429082)를 보면 좋을 것 같아요.
2편은 이걸 참고해주세요. https://blog.daum.net/kimkwangeun/46

2021-05-15 08:23 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
>  }
여기의 내용은 아니지만 남기자면! `경로조회는 3단계라 경로조회 관련 테스트는 실패하는 상태입니다!`

테스트에서 제외할 메서드가 있다면 `@Disabled`를 추가해주면 됩니다. 😉

2021-05-15 08:36 UTC, Junroot commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +        memberDao.deleteById(loginMember.getId());
사실 `deleteMember` 라는 API가 현재는 인증이 필요없이 처리되고 있어서 나중에 지워도 되지않을까라는 생각으로 의존하지 않는 형태로 만들어 뒀어요. 그런데 서비스 내에서는 재활용해도 문제가 없다는 생각이 되네요!

2021-05-15 08:43 UTC, Junroot commented on src/main/java/wooteco/subway/auth/domain/LoginMember.java
> +    private final Long id;
현재는 내부에 id만 가지고 있기는 하지만, 현재 로그인 되어있는 멤버를 나타내기 위한 필드는 충분히 바뀔 수 있다라고 생각이 들었어요.
사실 처음 미션을 진행할 때는 `LoginMember` 안에 이메일은 저장하는 식으로 구현하다가, id가 더 명확해 보여서 수정한 것 입니다. 이처럼 현재 토큰으로 얻을 수 있는 것은 "로그인 중인 멤버"라고 표현하는 것이 더 명확해 보여서 이렇게 네이밍을 했어요.

2021-05-15 13:42 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/domain/LoginMember.java
> +    private final Long id;
`현재 로그인 되어있는 멤버를 나타내기 위한 필드는 충분히 바뀔 수 있다라고 생각이 들었어요.` 저도 이 이유때문에 ID와 관련된 이름으로 바꾸는걸 선뜻 제안드리지 못했네요. 👍

2021-05-15 14:13 UTC, Junroot commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private JwtTokenProvider jwtTokenProvider;
네네 비대칭 키를 한국어로 공개 키(public key)와 비밀 키(private key)라고 하는데, secret key를 비밀 키라고 생각해서 제가 잘못 질문한거였어요! 부끄럽네요 😅
https://github.com/woowacourse/atdd-subway-path/pull/85#issuecomment-840963983

2021-05-15 15:59 UTC, Junroot commented on src/main/java/wooteco/subway/member/ui/MemberController.java
>  }
JUnit 학습할 때 공부해놓고 사용할 생각을 못했네요! 오늘도 공부하는 것과 적용하는 건 다르다는 것을 체감하네요 ㅠㅠ

2021-05-15 16:00 UTC, Junroot commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +            throw new AuthenticationException();
비즈니스 로직을 Dao안에 넣어버렸네요! 분리시키도록 하겠습니다!

2021-05-15 16:09 UTC, Junroot commented on build.gradle
> +	implementation 'javax.xml.bind:jaxb-api:2.3.0-b170201.1204'
페어의 노트북 환경에서 계속 오류가 나서 넣었어요. 그 땐 jdk 버전도 확인했는데 문제가 없어서 임시로 넣었어요 ㅠㅠ 현재 제 환경에서는 일단 문제가 없으니 의존을 제거하도록 하겠습니다!

2021-05-16 13:57 UTC, Hue9010 approved these changes
피드백 반영을 잘해주셨네요. 👍
이번 단계는 여기서 머지할게요!
제가 답변하지 않은 질문이나 궁금한게 있으면 말씀주세요. 😉

2021-05-16 13:57 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private JwtTokenProvider jwtTokenProvider;
용어들이 헷갈리긴 합니다. 😭

2021-05-16 13:57 UTC, merged

2021-05-16 15:25 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
>  }
한번 본 걸 다 기억하고 활용하면 다들 카이스트, 포스텍, 서울대 갔을거라고 생각합니다. 😋

2021-05-16 15:25 UTC, Hue9010 commented on build.gradle
> +	implementation 'javax.xml.bind:jaxb-api:2.3.0-b170201.1204'
이런문제가 가장 어렵죠. 😭

2021-05-17 16:42 UTC, Junroot commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private JwtTokenProvider jwtTokenProvider;
다시보니 미닉스님 웹툰이었네요! 한 때 책도 직접사서 재밌게 읽었어요!!

2021-05-17 17:12 UTC, Junroot commented
# 학습 로그
## 대칭키와 비대칭키
- 대칭키와 비대칭키의 차이를 이해하고 JWT에서 사용 중인 비밀키가 어떤 종류를 사용하는 것인지 이해했다.
- https://minix.tistory.com/395?category=429082
- https://blog.daum.net/kimkwangeun/46
## 태그
- 보안

## JWT
- JSON Web Token을 사용하여 사용자 인증을 안전하게 처리할 수 있었다.
- http://velopert.com/2389
## 태그
- 보안

## HandlerMethodArgumentResolver
- `HandlerMethodArgumentResolver`를 구현하여 요청으로 오는 데이터를 가공시켜 인자로 받을 수 있다.
- https://jaehun2841.github.io/2018/08/10/2018-08-10-spring-argument-resolver/
## 태그
- Spring

2021-05-17 17:28 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private JwtTokenProvider jwtTokenProvider;
전 아직 다 읽지는... 🤣