[Spring 지하철 경로 조회 - 1, 2단계] 와일더(강규한) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #86
Opened 2021-05-14 02:58 UTC by lns13301

안녕하세요. 휴!
로또미션때 뵙고 또 뵙네요. ☺️
친절한 피드백이 인상적이어서 또 리뷰어로 뵙고 싶었습니다. 😆

생소한 기능들을 써보니 제대로 사용한 것인지 모르겠네요.. 🧐
일단 만들고 고쳐보겠습니다!! 🛠

2021-05-15 08:48 UTC, Hue9010 requested changes
와일더 다시 만나서 반가워요! 😄
구현을 잘해주셨네요! 👍
몇가지 피드백 남겼는데 확인하고 궁금한건 언제든 질문주세요!
이번 단계는 코드상에서 피드백 드릴 부분이 적은 느낌이라 학습하면서 이해되지 않는 부분을 질문 주셔도 좋을 것 같아요. 😉
(주말이 평일보다 더 편하니 주말 고려치 말고 질문 주세요!)

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/domain/Member.java
> +    public boolean isNotSamePassword(String password) {
`isNot`SamePassword 👍

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/handler/SubwayAdvice.java
> +    }
커스텀 예외 추가에다가 예외 처리까지 잘해주셨네요. 👍

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/ui/AuthController.java
>      // TODO: 로그인(토큰 발급) 요청 처리하기
private 접근 제어자!
그리고 완료된 TODO는 제거해주세요! 😉

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private void validateLogin(TokenRequest tokenRequest) {
[Clean Code - 형식 맞추기(Form)](https://nesoy.github.io/articles/2018-01/CleanCode-Form)
> 종속 함수
> 한 함수가 다른 함수를 호출한다면(종속 함수) 두 함수는 세로로 가까이 배치한다. 가능하면 호출되는 함수를 호출하는 함수보다 뒤에 배치한다. (프로그램이 자연스럽게 읽힐 수 있도록) 이러한 규칙을 일관되게 적용한다면 독자는 방금 함수에서 호출한 함수가 잠시 후에 정의될 것이라고 자연스레 예측한다.

수직거리 부분 읽어보면 좋습니다. 😉

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        if (foundMember.get().isNotSamePassword(tokenRequest.getPassword())) {
코드 예시까지 드릴려다 지웠는데 😋 
Optional을 더 잘 활용해볼 수 있을 것 같아요. 힌트를 드리자면 Line 48, 50을 하나로 합칠 수 있겠네요. 😉

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +    public Optional<Member> findByEmailWithPassword(String email, String password) {
사용되지 않는 코드는 바로 지워주죠. 😉

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +    public Optional<Member> findByEmail(String email) {
Optional 👍

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +        String token = AuthorizationExtractor.extract(request);
[2단계 - 회원 관리 기능](https://techcourse.woowahan.com/s/U8wOamCU/ls/bEELCCPw)의 힌트를 참고해서 
AuthenticationPrincipalArgumentResolver를 구현하는 것도 해보죠.  😉

2021-05-15 08:48 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +    public ResponseEntity<MemberResponse> deleteMemberOfMine(HttpServletRequest request) {
```suggestion
    public ResponseEntity<Void> deleteMemberOfMine(HttpServletRequest request) {
```

2021-05-15 10:22 UTC, lns13301 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private void validateLogin(TokenRequest tokenRequest) {
만약 클래스 내부의 여러 메서드에서 동일한 내부 메서드를 사용할 경우에는 어디에 배치하는게 좋나요?

```java
public class Temp {

    public void a() {
        d();
    }

    public void b() {
    }

    public void c() {
        d();
    }

    private void d() {
    }
}
```

2021-05-15 13:39 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    private void validateLogin(TokenRequest tokenRequest) {
만약 클래스 내부의 여러 메서드에서 동일한 내부 메서드를 사용할 경우에는 어디에 배치하는게 좋나요?

```java
public class Temp {

    public void a() {
        e();
    }

    private void e() {
    }

    public void b() {
    }

    public void c() {
        e();
    }

    public void d() {
    }
}
```

c의 위치는 고민되지만 우선 이렇게 배치하겠네요.

2021-05-16 13:38 UTC, Hue9010 approved these changes
피드백 반영 잘해주셨네요. 👍
이번 단계는 여기서 머지할게요.
궁금한게 있다면 언제든 질문주세요. 😉

2021-05-16 13:38 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        throw new AuthorizationException();
여기도 Optional을 제대로 활용해보죠.

2021-05-16 13:38 UTC, merged