[Spring 지하철 경로 조회 - 1, 2단계] 에드(박성진) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #95
Opened 2021-05-14 08:34 UTC by sjpark-dev

안녕하세요 코니! 😊

이번 미션을 함께할 에드입니다.
이번에 많은 것을 한꺼번에 배웠다는 느낌이 드네요.
인증과 인가의 개념부터 JWT 사용법까지 아직 모든 내용을 소화하지는 못했네요. 🤣

학습 테스트를 통해서 Handler Method Argument Resolver, Handler Interceptor를 배웠어요.
인가를 resolver 또는 interceptor에서 할 수 있을 것 같은데요.
보통 어디서하는게 좋을까요?

그리고 아래와 같이
```
@PutMapping("/members/{id}")
public ResponseEntity<MemberResponse> updateMember(@PathVariable Long id, @RequestBody MemberRequest param) {
    return ResponseEntity.ok(memberService.updateMember(id, param));
}
```
정보를 수정하는 api의 body에 정보를 담아도 되는지 궁금합니다.

리뷰 감사합니다. 👍

2021-05-16 08:52 UTC, choihz requested changes
안녕하세요, 에드! 리뷰어 코니입니다 👋

지하철 경로 조회 미션 1, 2단계를 잘 구현해 주셨네요~ 피드백 보시고 궁금한 점 또는 의견이 있으시다면 언제든 코멘트 또는 DM 주세요!

2021-05-16 08:52 UTC, choihz commented on src/test/java/wooteco/subway/member/dao/MemberDaoTest.java
> +    }
테스트가 실패하고 있어요~ 사용자를 추가하는 작업이 없네요!

2021-05-16 08:52 UTC, choihz commented on frontend/src/pages/line/LinePage.vue
> +    }
```suggestion
    if (!response1.ok) {
      throw new Error(`${response1.status}`);
    }
```

JS도 컨벤션 😉
`response1`, `response2`보다 더 괜찮은 이름 없을까요? 😢

2021-05-16 08:52 UTC, choihz commented on src/main/java/wooteco/subway/auth/infrastructure/AuthorizationExtractor.java
> +    public static String BEARER_TYPE = "Bearer";
```suggestion
    public static final String BEARER_TYPE = "Bearer";
```

2021-05-16 08:52 UTC, choihz commented on src/main/java/wooteco/subway/auth/ui/AuthController.java
>      // TODO: 로그인(토큰 발급) 요청 처리하기
구현이 완료되었으면 주석은 지워 주세요~

2021-05-16 08:52 UTC, choihz commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
>      public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
```suggestion
    public Member resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
        NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
```

도메인 `Member` 객체를 이용하고 있는데, 이렇게 구현하신 이유가 있을까요? 도메인을 직접 이용하면 어떤 문제가 발생할 수 있을까요?

2021-05-16 08:52 UTC, choihz commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +        Member member = memberDao.findById(id).orElseThrow(() -> new IllegalArgumentException("존재하지 않는 ID입니다."));
```suggestion
        Member member = memberDao.findById(id)
            .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 ID입니다."));
```

2021-05-16 08:52 UTC, choihz commented on src/main/java/wooteco/subway/member/ui/MemberController.java
>      }
> 정보를 수정하는 api의 body에 정보를 담아도 되는지 궁금합니다.

네! 필요에 따라 수정의 결과를 받아야 할 수도 있죠.

2021-05-16 08:52 UTC, choihz commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
>  public class AuthenticationPrincipalArgumentResolver implements HandlerMethodArgumentResolver {
> 학습 테스트를 통해서 Handler Method Argument Resolver, Handler Interceptor를 배웠어요.
인가를 resolver 또는 interceptor에서 할 수 있을 것 같은데요.
보통 어디서하는게 좋을까요?

> [HandlerMethodArgumentResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/method/support/HandlerMethodArgumentResolver.html)
> Strategy interface for resolving method parameters into argument values in the context of a given request.

> [HandlerInterceptor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/HandlerInterceptor.html)
> Workflow interface that allows for customized handler execution chains. Applications can register any number of existing or custom interceptors for certain groups of handlers, to add common preprocessing behavior without needing to modify each handler implementation.
>
> A HandlerInterceptor gets called before the appropriate HandlerAdapter triggers the execution of the handler itself. This mechanism can be used for a large field of preprocessing aspects, e.g. for **authorization checks**, or common handler behavior like locale or theme changes. Its main purpose is to allow for factoring out repetitive handler code.

둘은 사용 목적이 다르죠!
지금은 `AuthenticationPrincipalArgumentResolver`를 통해야만 토큰의 유효성 체크가 가능한데, 만약 토큰의 유효성 체크가 필요한 새 엔드포인트가 추가되었고 거기서는 회원 정보는 필요 없다면, 따라서 `@AuthenticationPrincipal`이 붙은 파라미터가 없다면 어떻게 인증해야 할까요?

2021-05-17 03:53 UTC, sjpark-dev commented on src/test/java/wooteco/subway/member/dao/MemberDaoTest.java
> +    }
수정하겠습니다. 👍

2021-05-17 04:18 UTC, sjpark-dev commented on frontend/src/pages/line/LinePage.vue
> +    }
Member관련 JS 파일만 수정했습니다.
나머지 노선도관련 JS 파일은 3단계에서 기능 구현 완료후 적용하겠습니다. 👍

2021-05-17 04:25 UTC, sjpark-dev commented on src/main/java/wooteco/subway/auth/ui/AuthController.java
>      // TODO: 로그인(토큰 발급) 요청 처리하기
Member관련 부분만 수정했습니다.
나머지 노선도관련 부분은 3단계에서 기능 구현 완료후 적용하겠습니다. 👍

2021-05-17 04:40 UTC, sjpark-dev commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
>      public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
DTO가 있다는 사실을 깜빡했네요. 😅
아무래도 뷰나 컨트롤러에서  도메인 기능을 조작할 수 있게 되서 원치 않는 결과를 초래할 수 있겠네요.

2021-05-17 04:57 UTC, sjpark-dev commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
>      public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
Member가 아니라 전용 DTO를 만들어야겠군요.
아무래도 뷰나 컨트롤러에서 도메인 기능을 조작할 수 있게 되서 원치 않는 결과를 초래할 수 있겠네요.

2021-05-17 05:39 UTC, sjpark-dev commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
>  public class AuthenticationPrincipalArgumentResolver implements HandlerMethodArgumentResolver {
새 엔드포인트가 추가된다면 새로운 @AuthenticationPrincipal을 만들기 보단 path로 발동되는  interceptor로 인증을하면 되겠군요. 👍

2021-05-17 05:45 UTC, sjpark-dev commented
안녕하세요 코니! 😅

리팩토링하면서 argument resolver와 controller 사이의 전용 DTO가 있어야 한다는 사실을 깨닫게 되었네요. 👍
변수명 수정과 주석제거는 Member관련 부분만 했습니다.
나머지 노선도관련 부분은 3단계 기능 구현하면서 적용하겠습니다.

리뷰 감사합니다. 👍

2021-05-17 17:12 UTC, choihz approved these changes
안녕하세요, 에드!

피드백을 잘 반영해 주셨네요~ 💯 다음 단계에서 다시 만나요! 👋

2021-05-17 17:12 UTC, choihz commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    }
EXISTS 쿼리를 써도 될 것 같아요.

2021-05-17 17:12 UTC, choihz commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    }
토큰 확인 시마다 DB 접근이 이뤄지면 JWT 사용의 장점이 퇴색되는 느낌인데요, 여기에 대해선 어떻게 생각하시나요~?

2021-05-17 17:12 UTC, merged

2021-05-18 03:10 UTC, sjpark-dev commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    }
토큰의 장점은 인증이 필요할 때 민감한 정보(이메일, 비밀번호)를 이용하지 않는 것이라고 생각합니다.
그리고 DB에서 한번 확인을 해야하지 않을까 생각합니다. 
그렇지 않으면 토큰의 payload에 엉뚱한 id가 들어 있어도 인증을 통과할 수 있을 것 같아서요.
예를 들면 사용자 A와 B가 있는데 해커가 A의 토큰을 가로챘다고 가정을하면,
DB에서 토큰의 id가 유효한지 확인을 하지 않으면 A뿐만 아니라 B의 인증도 통과할 수 있다고 생각합니다.

2021-05-19 07:16 UTC, choihz commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    }
인증이 필요할 때 민감 정보를 이용하지 않는다는 건 클라이언트 관점에서의 생각인가요? 그렇다면 토큰 뿐만 아니라 세션도 마찬가지 아닐까요?
JWT를 이용한 인증이 가진 장점 중 가장 중요한 것은 자체적으로 정보를 가지고 있을 수 있다는 점, 그리고 인증 시마다 DB 조회가 필요하지 않다는 점이라고 생각해요. 물론 JWT를 사용한다고 무조건 DB를 조회하면 안 된다는 것은 아니고 보편적으로는 그런 식으로 사용하는 것 같아요. (접근 토큰의 경우)
그런데 말씀하신 것처럼 토큰 발급 후 정보가 변경된다면, 예를 들어 로그인해 유효한 토큰을 발급한 직후 회원 탈퇴가 이뤄진다면(그리고 이 토큰을 성공적으로 탈취했다면), DB를 조회하지 않을 경우 유효 토큰으로 작업을 할 수 있게 돼요. 따라서 서비스의 특성에 따라 토큰을 사용하면서도 인증 시마다 DB를 조회하도록 구현하기도 하고(지금 에드가 구현한 방식이 되겠죠?), 아니면 블랙리스트를 관리할 수도 있어요. 토큰 자체를 만료시킬 수는 없으니 유효하지 않은 토큰을 따로 관리하는 거죠.

2021-05-22 12:07 UTC, sjpark-dev commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +    }
그렇네요, 제가 말씀드린 장점은 세션에도 해당하네요. 😅
확실히 토큰의 가장 큰 장점이 자제적으로 정보를 가지고 있을 수 있는 것인데 
DB를 접근하는 것은 이 장점을 퇴색시키는 것이네요.
특수한 상황이 아니니 보편적인 방식을 적용해보겠습니다.