[Spring 지하철 경로 조회 - 1, 2단계] 찰리(박민영) 미션 제출합니다.
woowacourse/atdd-subway-path pull request #96
Opened 2021-05-14 09:08 UTC by Gomding

안녕하세요 데이브 !
지하철 경로 조회 미션으로 다시 뵙게되어 영광이에요 👍 
이번 리뷰도 탈탈 털어주세요!!

질문이 몇가지 있어요

## 질문1
LoginInterceptor 에서 토큰을 검사한다면 토큰이 존재하는지 정도만 검사하는지 아니면 토큰의 유효성까지 검사해야하는지 궁금해요!

## 질문2
Service 에서 update 를 할 때 findById 같은 조회 메서드로 DB에서 먼저 해당 객체를 가져온뒤에
가져온 객체를 기준으로 변경한 뒤 update 에 객체를 넣어서 수정하는 방식을 선택했는데
수정 전에 DB를 조회하여 객체를 가져오는 방식이 필요한지 필요없는지 궁금해요!
저는 객체를 검색해서 가져온 뒤 상태를 변경해서 update 메서드 안에 해당 객체를 넣어주는게 맞다고 생각해요!
데이터를 가져와서 변경을 하면 안전성이 더욱 +++ 된다고 생각했어요.

## 질문 3
AuthenticationPrincipalArgumentResolver 에서 token 의 payload 안에있는 데이터를 뽑아와서
DB에서 조회를 하여 완전한 LoginMember(id, email, age 모든 필드를 데이터베이스와 일치시킴)을 만들어서 반환해주는것과

payload 안에는 ID 만 넣어서 LoginMember(id만 들어있음)을 반환하고 이후 수정, 삭제 등등의 요청에만 필요 검증을 더욱 거치는게 좋을까요?

2021-05-16 07:49 UTC, dave915 commented
>질문1
LoginInterceptor 에서 토큰을 검사한다면 토큰이 존재하는지 정도만 검사하는지 아니면 토큰의 유효성까지 검사해야하는지 궁금해요!

유효성 검사까지 진행하여 만료된 토큰인지 체크까지 해주는것이 좋을 것 같아요! 
그리고 지금은 유효성 검사만 하지만 나중에 권한 체크등의 로직이 interceptor에 들어 갈 수 있습니다 :) 

>질문2
Service 에서 update 를 할 때 findById 같은 조회 메서드로 DB에서 먼저 해당 객체를 가져온뒤에
가져온 객체를 기준으로 변경한 뒤 update 에 객체를 넣어서 수정하는 방식을 선택했는데
수정 전에 DB를 조회하여 객체를 가져오는 방식이 필요한지 필요없는지 궁금해요!
저는 객체를 검색해서 가져온 뒤 상태를 변경해서 update 메서드 안에 해당 객체를 넣어주는게 맞다고 생각해요!
데이터를 가져와서 변경을 하면 안전성이 더욱 +++ 된다고 생각했어요.

저도 찰리가 선택한 방법으로 사용하고 있어요! 

>질문 3
AuthenticationPrincipalArgumentResolver 에서 token 의 payload 안에있는 데이터를 뽑아와서
DB에서 조회를 하여 완전한 LoginMember(id, email, age 모든 필드를 데이터베이스와 일치시킴)을 만들어서 반환해주는것과
payload 안에는 ID 만 넣어서 LoginMember(id만 들어있음)을 반환하고 이후 수정, 삭제 등등의 요청에만 필요 검증을 더욱 거치는게 좋을까요?

저는 후자 같은 경우 같은 정보를 두번 조회 한다고 생각해서 `payload 안에있는 데이터를 뽑아와서
DB에서 조회를 하여 완전한 LoginMember(id, email, age 모든 필드를 데이터베이스와 일치시킴)을 만들어서 반환해주는것` 이 방법을 사용하고 있어요.

2021-05-16 08:12 UTC, dave915 requested changes
찰리 안녕하세요! 다시 만나게 되어서 반갑습니다 🎉
리뷰가 늦어서 죄송합니다 🙇‍♂️
질문에 대한 코멘트와 몇가지 피드백 남겼어요! 
궁금한점이 있다면 언제든 편하게 질문 주세요 :)

2021-05-16 08:12 UTC, dave915 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        Member member = optionalMember.orElseThrow(EmailNotFoundException::new);
따로 optionalMember를 만들지 않아도 될 것 같아요 :) 
```suggestion
        Member member = memberDao.findByEmail(tokenRequest.getEmail())
                .orElseThrow(EmailNotFoundException::new);
```

2021-05-16 08:12 UTC, dave915 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
>          return ResponseEntity.ok().build();
다른 `ResponseEntity<Void>` 를 리턴하는 메소드들과 동일하게 `ResponseEntity.noContent().build();` 해주면 좋을 것 같아요 :)

2021-05-16 08:12 UTC, dave915 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +                                                   @RequestBody MemberRequest param) {
`@Valid` 를 이용해서 유효성 체크도 해보세요!

2021-05-16 08:12 UTC, dave915 commented on frontend/src/pages/member/LoginPage.vue
> +        const token = await fetch("http://localhost:8080/login", {
`http://localhost:8080` 이 부분은 실행 환경에 따라 달라질 수 있기 때문에 보통 Path만 이용해서 호출해요!
```suggestion
        const token = await fetch("/login", {
```

2021-05-17 06:31 UTC, Gomding commented on src/test/java/wooteco/subway/auth/AuthAcceptanceTest.java
> +            .when().post("/login/token")
앗 테스트 수정을 안했었네요..
데이브가 말씀한대로 /login/token에서
path 에 "token이 만들어진다" 까지는 포함하지 않아도 될것같아서 수정했었어요!

2021-05-17 06:35 UTC, Gomding commented on src/main/java/wooteco/subway/auth/AuthenticationPrincipalConfig.java
>      public void addArgumentResolvers(List argumentResolvers) {
제네릭 타입을 명시하지 않아서 경고가 나오고 있었네요 😮 

해당 부분 타입을 명시하도록 수정했어요!

2021-05-17 07:07 UTC, Gomding commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        Member member = optionalMember.orElseThrow(EmailNotFoundException::new);
이 부분도 다른 부분에서는 잘 만들어놓고 깜빡하고 고치지 않았네요 😮 🥊

2021-05-17 07:09 UTC, Gomding commented on src/main/java/wooteco/subway/member/ui/MemberController.java
>          return ResponseEntity.ok().build();
단순하게 test 가 ok를 받으니까 응답으로 ok를 줘야지 라고 생각해버렸네요!

모든 코드를 맹목적으로 받아들이지 않게 조심해야 겠어요 :)

2021-05-17 07:10 UTC, Gomding commented on frontend/src/pages/member/LoginPage.vue
> +        const token = await fetch("http://localhost:8080/login", {
해당 부분을 /api/login 같이 호출할 수 있도록 변경했어요!

2021-05-17 08:07 UTC, Gomding commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +                                                   @RequestBody MemberRequest param) {
@Valid 애너테이션을 활용하면 Request 에서 바인딩할 때 값 검증을 진행할 수 있네요!

추가적으로 공부한 내용으로는
@Valid 는 전체 필드(유효성 검증 애너테이션을 붙인)를 한번에 검사하여 유효성을 보장하지만
부분적인 유효성 검사만 필요한 경우에는 문제가 발생하기 때문에

> ex) email, password, age 3개의 필드 중 age를 제외한 2개의 필드만 검사하고 싶은 경우

@Validated 애너테이션을 사용하면 유효성 검사 그룹을 나눠서 진행할 수 있어요!

@Valid 와 @Validated 의 차이점에 대해 제가 이해한 것이 맞을까요?!

2021-05-17 11:03 UTC, Gomding commented
안녕하세요 데이브!

이번에 피드백 반영하면서 ArgumentResolver 에서 데이터베이스의 데이터를 가져와서 LoginMember 를 만들도록 구현해봤어요!
이렇게 했을 때 LoginMember 를 Service에 넘겨줘서 사용할텐데
loginMember 는 이미 데이터베이스를 통해 검증됐다고 생각하고 사용해도 될까요?

위처럼 생각을 하고 수정을 하다보니 아래와 같이 회원 조회해서 응답으로 주는 경우에는
그냥 loginMember를 넘겨주는것으로 끝나더라구요 🤔 

```
@GetMapping("/members/me")
    public ResponseEntity<LoginMember> findMemberOfMine(@AuthenticationPrincipal LoginMember loginMember) {
        return ResponseEntity.ok(loginMember);
    }
```

2021-05-19 11:14 UTC, dave915 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +                                                   @RequestBody MemberRequest param) {
넵! :) 

https://velog.io/@damiano1027/Spring-Valid-Validated%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%9C%A0%ED%9A%A8%EC%84%B1-%EA%B2%80%EC%A6%9D#validated

2021-05-19 11:19 UTC, dave915 approved these changes
찰리 안녕하세요! 
피드백 반영 한 부분 확인 했어요 :) 
간단 한 피드백 남겨났으니 다음 단계에서 같이 반영해 보면 좋을 것 같아요!
이번 단계는 이만 머지할게요!

2021-05-19 11:19 UTC, dave915 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +        }
이 부분도 `SubwayControllerAdvice` 에서 처리되게 할 수 있어요!

2021-05-19 11:19 UTC, dave915 commented on src/main/java/wooteco/subway/SubwayControllerAdvice.java
> +    @ExceptionHandler(AuthorizationException.class)
개발자가 예상하지 못한 오류를 처리 할수 있도록 `@ExceptionHandler(Exception.class)` 도 한번 만들어 보세요 :)

2021-05-19 11:20 UTC, dave915 commented
>이번에 피드백 반영하면서 ArgumentResolver 에서 데이터베이스의 데이터를 가져와서 LoginMember 를 만들도록 구현해봤어요!
이렇게 했을 때 LoginMember 를 Service에 넘겨줘서 사용할텐데
loginMember 는 이미 데이터베이스를 통해 검증됐다고 생각하고 사용해도 될까요?

저는 검증 되었다고 생각하고 그렇게 사용하고 있습니다 ㅎㅎ

2021-05-19 11:20 UTC, merged